### ISSUE TITLE
No app name specified

### ISSUE THREAD

**Issue by mourningsun75** [Fmstrat/ownnote#1]
When i try to activate the app the following errors occurs:

No app name specified

**Comment by Fmstrat** [comment]
What version of ownCloud are you running?

**Comment by mourningsun75** [comment]
7.0.4

The permissions are ok.

**Comment by Fmstrat** [comment]
Hmm, I'm running 7.0.4 as well with no issues. Let me deploy a brand new instance and see if it happens. If not, perhaps there is something conflicting. Do/did you have another Notes application installed that used the name "Notes" in the navigation?

**Comment by mourningsun75** [comment]
"Do/did you have another Notes application installed that used the name "Notes" in the navigation?"

yes!

**Comment by Fmstrat** [comment]
Did disabling that app allow ownNote to work?

**Comment by mourningsun75** [comment]
No. :-(

**Comment by Fmstrat** [comment]
Crud. Can you let me know what apps you have installed, and which are enabled? I'm not able to reproduce this issue.

**Comment by doucettom** [comment]
I had to rename it to ownNotes (without the version postpend to the folder name...)

**Comment by qhaz** [comment]
I have same issue.  Error: "No app name specified" -  when trying to install.
I have checked permissions - ok.
I have disabled other 'note' apps.
I have renamed to . . . /owncloud/apps/ownnotes 
But the error remains.

**Comment by qhaz** [comment]
OwnCloud version 7.0.4 (stable)

**Comment by mourningsun75** [comment]
"I had to rename it to ownnotes (without the version postpend to the folder name...) to get rid of this error."

Also worked for me

**Comment by Pastafarianist** [comment]
I renamed it to "ownnotes" and the error changed to this:

![screenshot](http://i.imgur.com/gVNYpdo.png)

**Comment by mrumpf** [comment]
Removing the suffix "-0.0.1" from the folder name, which was created when running "tar xvfz 0.0.1.tar.gz" solved the issue for me as well.

**Comment by Pastafarianist** [comment]
I confirm that after renaming the app folder to "ownnote" the installation completed successfully.

**Comment by qhaz** [comment]
. . . ah! Works now.  Rename to "ownnote" NOT "ownnotes".
cheers

**Comment by Fmstrat** [comment]
Thanks everyone. I've updated the instructions on both apps.owncloud.com and in the README.
