### ISSUE TITLE
Android: Allow first-sync even if app is suspended

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#100]
... when you establish the first time the connection with the 0.0.11 android version, the app get all notes from the server. 

on my case (1200 Notes with a size of 350MB) the counter increase up to the time the display of my phone (galaxy s4) went off. if you activate the display the counter starts from beginning.

If you accidentaly tab beside the counter, the counter disappears and you have no progress anymore.

**Comment by Fmstrat** [comment]
I will address this in the next version. Thanks for the feedback.

**Comment by Fmstrat** [comment]
Complete for .13
