### ISSUE TITLE
Android: Slow response when using extremely large quantities of notes

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#101]
The current version 0.0.11 works, but with a huge number of notes the device response is pretty bad. i have a high number of categorys (50) and a lot of notes (1200 <>).

**Comment by Fmstrat** [comment]
This is something I'm working through on multiple fronts. It's connected to both https://github.com/Fmstrat/ownnote/issues/73 and https://github.com/Fmstrat/ownnote/issues/98 as well. The features I'm implementing to fix this is selective offline sync, as well as pagination for increased performance. Obviously the search feature in the future will make pagination more bearable, too. Could you let me know what device you use so I can ensure I meet performance goals of that device within the spec? Thanks.

**Comment by apg1980** [comment]
I am using samsung galaxy s4 (lollipop) and samsung galaxy note 10.1 2014 (4.4.2) edition.

**Comment by Fmstrat** [comment]
Perfect, thank you.

**Comment by Fmstrat** [comment]
Pagination, as well as online-only mode has been added for .13 to support this. Selective sync will come in a future version: https://github.com/Fmstrat/ownnote/issues/112

**Comment by Fmstrat** [comment]
Note: to completely clear out data stored, it may be worth "Clearing Data" on the App after installing 0.0.13.
