### ISSUE TITLE
Android: App 0.11 won't log in

### ISSUE THREAD

**Issue by steveriley** [Fmstrat/ownnote#103]
I updated the Android app to 0.11 that appeared in the store on April 17. After that, I could no longer log into my ownCloud notes pages. (Previous versions of the Android client worked.) The following dialog box appears:

Error
The following error has occurred while connecting to the server.
Unknow Error. 500: There was an error with the request

I updated the ownCloud application to the latest version today (moved old one out of apps directory, git cloned a new installation) and the problem persists. I can view and edit notes just fine in a web browser.

I'm using an SSL certificate from StartCom. It is trusted by my device, as the StartCom CA certificates are part of Android. The error even appears if I select "Allow all SSL certificates."

What logs will help troubleshoot? Nothing appears in /var/www/owncloud/data/owncloud.log or /var/log/apache2/ssl_access.log.

**Comment by Fmstrat** [comment]
Hi @steveriley,

Do you have experience pulling the Android logcat with *adb logcat*? If so, set your username to *[DEBUG]username* replacing *username* with your username. After that run *adb logcat |grep Cordo* from the shell/cmd prompt, and send me the output and I can try to figure this out. I did switch API libraries to solve some other issues, but none of my test devices or sites (StartSSL, GeoTrust, and Self-signed) showed any issues like this. Thanks.

**Comment by steveriley** [comment]
Yes, I'm familiar with ADB.

I removed all app data. Then ran the command you requested and started the app. Here's the output of logcat before I created account info:

/CordovaLog(  691): Changing log level to DEBUG(3)
D/CordovaActivity(  691): CordovaActivity.init()
I/dalvikvm(  691): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.CordovaWebView.initWebViewSettings
D/CordovaActivity(  691): CordovaActivity.createViews()
I/dalvikvm(  691): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.CordovaWebViewClient.onReceivedClientCertRequest
I/dalvikvm(  691): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.CordovaChromeClient.onShowFileChooser
D/CordovaWebView(  691): CordovaWebView is running on device made by: samsung
D/CordovaWebView(  691): >>> loadUrl(file:///android_asset/www/index.html)
D/CordovaWebView(  691): >>> loadUrlNow()
D/CordovaActivity(  691): Resuming the App
D/CordovaWebViewClient(  691): onPageStarted(file:///android_asset/www/index.html)
D/CordovaActivity(  691): onMessage(onPageStarted,file:///android_asset/www/index.html)
D/CordovaWebViewClient(  691): onPageFinished(file:///android_asset/www/index.html)
D/CordovaActivity(  691): onMessage(onPageFinished,file:///android_asset/www/index.html)
D/CordovaActivity(  691): onMessage(spinner,stop)
D/CordovaNetworkManager(  691): Connection Type: wifi
D/CordovaNetworkManager(  691): Connection Extra Info: "[ssid redacted]"
D/CordovaNetworkManager(  691): Connection Type: wifi
D/CordovaNetworkManager(  691): Connection Extra Info: "[ssid redacted]"
D/CordovaActivity(  691): onMessage(networkconnection,wifi)
D/CordovaLog(  691): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 39 : SQLitePlugin openargs: {"name":"ownnote.db"}
D/CordovaLog(  691): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 49 : DB opened: ownnote.db
D/CordovaActivity(  691): onMessage(spinner,stop)
D/CordovaActivity(  691): Paused the application!
D/CordovaWebView(  691): Handle the pause
D/CordovaActivity(  691): CordovaActivity.onDestroy()
D/CordovaWebView(  691): >>> loadUrlNow()
I/CordovaLog( 1426): Changing log level to DEBUG(3)
D/CordovaActivity( 1426): CordovaActivity.init()
I/dalvikvm( 1426): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.CordovaWebView.initWebViewSettings
D/CordovaActivity( 1426): CordovaActivity.createViews()
I/dalvikvm( 1426): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.CordovaWebViewClient.onReceivedClientCertRequest
I/dalvikvm( 1426): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.CordovaChromeClient.onShowFileChooser
D/CordovaWebView( 1426): CordovaWebView is running on device made by: samsung
D/CordovaWebView( 1426): >>> loadUrl(file:///android_asset/www/index.html)
D/CordovaWebView( 1426): >>> loadUrlNow()
D/CordovaActivity( 1426): Resuming the App
D/CordovaWebViewClient( 1426): onPageStarted(file:///android_asset/www/index.html)
D/CordovaActivity( 1426): onMessage(onPageStarted,file:///android_asset/www/index.html)
D/CordovaWebViewClient( 1426): onPageFinished(file:///android_asset/www/index.html)
D/CordovaActivity( 1426): onMessage(onPageFinished,file:///android_asset/www/index.html)
D/CordovaActivity( 1426): onMessage(spinner,stop)
D/CordovaNetworkManager( 1426): Connection Type: wifi
D/CordovaNetworkManager( 1426): Connection Extra Info: "[ssid redacted]"
D/CordovaNetworkManager( 1426): Connection Type: wifi
D/CordovaNetworkManager( 1426): Connection Extra Info: "[ssid redacted]"
D/CordovaActivity( 1426): onMessage(networkconnection,wifi)
D/CordovaLog( 1426): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 39 : SQLitePlugin openargs: {"name":"ownnote.db"}
D/CordovaLog( 1426): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 49 : DB opened: ownnote.db
D/CordovaActivity( 1426): onMessage(spinner,stop)

Here's the output of logcat after entered my server's URL, username "[DEBUG]name", and password:

D/CordovaActivity( 1426): Paused the application!
D/CordovaWebView( 1426): Handle the pause
D/CordovaActivity( 1426): Resuming the App
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : setUserPass
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : basicAuth
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : acceptAllCerts:false
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : startSync
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : Set Basic Auth
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : app is online
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : buildLogin

Alas, that doesn't look too helpful :(

Selecting "Allow all SSL certificates" and trying again shows this:

D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : setUserPass
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : basicAuth
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : acceptAllCerts:true
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : startSync
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : Set Basic Auth
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : app is online
D/CordovaLog( 1426): file:///android_asset/www/js/index.js: Line 117 : buildLogin

**Comment by Fmstrat** [comment]
Hrm, it seems with this library a 401 can be interpreted as a 500 error with some servers. A 401 in ownCloud comes from an incorrect password. I assume you've checked that, but I'm mentioning it just in case. I'm going to add that as a separate issue. As for this, could you let me know what version of Android you are running? Thanks.

**Comment by Fmstrat** [comment]
Also, details about your server setup would be helpful.

**Comment by Fmstrat** [comment]
After further investigation, I'm thinking more and more that this has something to do with the way header tokens are transferred and the new library. I even think I've fixed it in the code already, I would just like to be able to recreate your server set up to identify the offending code to be 100% sure. I may just create a new version release for the Android store since the potential fix won't hurt anything else.

**Comment by Fmstrat** [comment]
I am marking this as complete since I'm 90% sure the fix in 0.0.12 that will hit the Play Store tonight will fix this. If not, please create a new ticket. Thanks!
