### ISSUE TITLE
Android: App 0.0.12 won't connect to TLSv1.2

### ISSUE THREAD

**Issue by steveriley** [Fmstrat/ownnote#105]
Following up from issue #103 

I installed version 0.0.12 just now and I'm seeing the same problem. Here's logcat after clearing data and starting the app, before entering debug credentials:

```
I/CordovaLog(20820): Changing log level to DEBUG(3)
D/CordovaActivity(20820): CordovaActivity.init()
I/dalvikvm(20820): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.CordovaWebView.initWebViewSettings
D/CordovaActivity(20820): CordovaActivity.createViews()
I/dalvikvm(20820): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.CordovaWebViewClient.onReceivedClientCertRequest
I/dalvikvm(20820): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.CordovaChromeClient.onShowFileChooser
D/CordovaWebView(20820): CordovaWebView is running on device made by: samsung
D/CordovaWebView(20820): >>> loadUrl(file:///android_asset/www/index.html)
D/CordovaWebView(20820): >>> loadUrlNow()
D/CordovaActivity(20820): Resuming the App
D/CordovaWebViewClient(20820): onPageStarted(file:///android_asset/www/index.html)
D/CordovaActivity(20820): onMessage(onPageStarted,file:///android_asset/www/index.html)
D/CordovaWebViewClient(20820): onPageFinished(file:///android_asset/www/index.html)
D/CordovaActivity(20820): onMessage(onPageFinished,file:///android_asset/www/index.html)
D/CordovaActivity(20820): onMessage(spinner,stop)
D/CordovaNetworkManager(20820): Connection Type: wifi
D/CordovaNetworkManager(20820): Connection Extra Info: "[ssid redacted]"
D/CordovaNetworkManager(20820): Connection Type: wifi
D/CordovaNetworkManager(20820): Connection Extra Info: "[ssid redacted]"
D/CordovaActivity(20820): onMessage(networkconnection,wifi)
D/CordovaLog(20820): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 39 : SQLitePlugin openargs: {"name":"ownnote.db"}
D/CordovaLog(20820): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 49 : DB opened: ownnote.db
D/CordovaActivity(20820): onMessage(spinner,stop)
```

And after entering credentials:

````
D/CordovaLog(20820): file:///android_asset/www/js/index.js: Line 126 : setUserPass
D/CordovaLog(20820): file:///android_asset/www/js/index.js: Line 126 : acceptAllCerts:false
D/CordovaLog(20820): file:///android_asset/www/js/index.js: Line 126 : startSync
D/CordovaLog(20820): file:///android_asset/www/js/index.js: Line 126 : app is online
D/CordovaLog(20820): file:///android_asset/www/js/index.js: Line 126 : buildLogin
```

You asked about my password. Yep, I'm entering it correctly. I have a non-alphanumeric character in my password, could this be the problem?

I'm running ownCloud 8.0.2 on Debian 7.8. It's installed from the openSUSE Build Service.

Other information:
* ownCloud lives in `/var/www/owncloud`
* `www-data:www-data` owns everything in the `./apps`, `./config`, and `./data` subdirectories; `root:root` owns everything else
* My URL for ownCloud is `https://mydomain.tld/owncloud`
* `/etc/apache2/conf.d/owncloud.conf` is a symlink to `/etc/apache2/conf-available/owncloud.conf` and contains the following:
```
Alias /owncloud "/var/www/owncloud/"
<Directory "/var/www/owncloud">
    Options +FollowSymLinks
    AllowOverride All
</Directory>
```

I'm running Android 4.4.4 on a Samsung Note 4.

What else can I tell  you?

**Comment by Fmstrat** [comment]
Is there anything else specific to your install, such as running nginx as a proxy, apache2 proxying, htaccess configurations, etc?

**Comment by Fmstrat** [comment]
Also, while standard non-alpha-numerics won't cause an issue. I have not tested alt-characters, but you would need a special android keyboard to enter those anyway.

**Comment by Fmstrat** [comment]
Another question, how do you have your SSL and host/virtualhost set up? Specifically, have you tried:

    https://mydomain.tld/owncloud

vs:

    https://www.mydomain.tld/owncloud

Or any other combination that may be specified in the cert, apache config, or in the trusted_hosts for OC?

**Comment by steveriley** [comment]
I would think that my installation is fairly basic. It's Apache 2.2, as that's what Debian 7 has. I'm not running any sort of proxy. I'm using the MPM Event flavor and using PHP5-FPM to handle PHP; this is perhaps a little unusual but I doubt it's the source of the problem.

`/var/www/owncloud` has the following `.htaccess` file:
```
# Version: 8.0.2
<IfModule mod_fcgid.c>
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
</IfModule>
</IfModule>
</IfModule>
<IfModule mod_php5.c>
php_value upload_max_filesize 513M
php_value post_max_size 513M
php_value memory_limit 512M
php_value mbstring.func_overload 0
php_value always_populate_raw_post_data -1
<IfModule mod_env.c>
  SetEnv htaccessWorking true
</IfModule>
</IfModule>
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R]
RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R]
RewriteRule ^apps/calendar/caldav\.php remote.php/caldav/ [QSA,L]
RewriteRule ^apps/contacts/carddav\.php remote.php/carddav/ [QSA,L]
RewriteRule ^remote/(.*) remote.php [QSA,L]
RewriteRule ^(build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
RewriteRule ^(\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>
<IfModule mod_mime.c>
AddType image/svg+xml svg svgz
AddEncoding gzip svgz
</IfModule>
<IfModule mod_dir.c>
DirectoryIndex index.php index.html
</IfModule>
AddDefaultCharset utf-8
Options -Indexes
<IfModule pagespeed_module>
        ModPagespeed Off
</IfModule>
<IfModule mod_headers.c>
  <FilesMatch "\.(css|js)$">
    Header set Cache-Control "max-age=7200, public"
  </FilesMatch>
</IfModule>
```
Here is my `/var/www/owncloud/config/config.php`:
```
<?php
$CONFIG = array (
  'instanceid' => '[redacted]',
  'passwordsalt' => '[redacted]',
  'secret' => '[redacted]',
  'trusted_domains' => 
  array (
    0 => 'm92p',
    1 => 'rileyz.net',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://m92p/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '[redacted]',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'postmaster',
  'mail_domain' => 'rileyz.net',
  'theme' => '',
  'maintenance' => false,
);
```
Internally, the DNS name of the machine is `m92p.rileyz.net`. The CN on the machine's certificate is the same. The certificate also has a SAN of simply `rileyz.net`, and this is what I'm entering in the app: `https://rileyz.net/owncloud`. I access this server from outside my home network routinely over HTTPS and other protocols just using the name `rileyz.net`. `www` is not defined in my DNS external view.

There is no `.htaccess` in `/etc/apache2` or `/var/www`. 

I wonder if it's a problem with cipher suites? I'm allowing only TLS 1.1 and 1.2 and narrowing the range of suites offered. Here what I've defined in `/etc/apache2/sites-enabled/default-ssl`:
```
        SSLProtocol +TLSv1.2 +TLSv1.1 -TLSv1 -SSLv3 -SSLv2
        SSLCipherSuite 'ECDH+AESGCM:DH+AESGCM:ECDH+AES:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS:!3DES'
        SSLHonorCipherOrder On
        Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
```

This all worked with the 0.0.10 client. Something in the new library you've switched to seems not to like something in my config. Weird!

**Comment by Fmstrat** [comment]
OK, thanks for the all the info, it looks like I'm going to have to set up a debian host to track this down. Thanks.

**Comment by JohannesTress** [comment]
I think I have exactly the same problem. I use a hosted webspace (german provider strato) and can't login to the ownnote app on my tablet.

**Comment by Fmstrat** [comment]
@johannesTress Are you seeing the exact same signs? There are a number of things that could potentially cause errors, so I want to confirm it's the same issue. Do you know the system specifications of your hosting provider?

**Comment by Fmstrat** [comment]
Found it. It's a bug in the new HTTP library. Tracking things here: https://github.com/wymsee/cordova-HTTP/issues/48

**Comment by steveriley** [comment]
That's it -- I enabled TLSv1 in my Apache configuration and I can now log in with the Android client.

**Comment by Fmstrat** [comment]
Great. Depending on the response I get over there, I may push this out to the next version. Have to wait and see.

**Comment by Fmstrat** [comment]
OK, as you can see if the references above, this bug actually appears to have far-reaching effects to potentially thousands of apps. I'm using a cordova-HTTP plugin, which uses the http-request library which is what does not have TLSv1.2 enabled, which is used by a LOT of apps.

I'm marking this complete for v0.0.13 as I've incorporated my own fix, and submitted fixes via pull requests to both cordova-HTTP and http-request, which will hopefully expedite things for other developers.

**Comment by Fmstrat** [comment]
@steveriley I should also note that once 0.0.13 rolls, out, you can remove TLSv1 support from apache again. Just note that android versions older than 4.2 (I believe) will not be able to connect (this would be true of any Android app to your server, not just ownNote).

**Comment by steveriley** [comment]
Nice. Thanks for looking into this.
