### ISSUE TITLE
Android: Notes shifted to next category down

### ISSUE THREAD

**Issue by TheBready** [Fmstrat/ownnote#106]
The contains of the notes are shifted so that the current note got the title from the one above. 
On the server everything is fine. 
Device: Find 7, Nameless Rom 5.1 (19.04.15), Android 5.1

Here is the Log:
04-20 11:11:42.353 I/ActivityManager(973): START u0 {act=android.intent.action.VIEW dat=https://play.google.com/store/apps/details?id=com.nowsci.ownnote&reviewId=Z3A6QU9xcFRPRzZrakczc2ttZUxFUm1NVXZjbHlkMjRiZUVlYW02MlNOdXhxTEk5ZFhBSkhjYUFaeGZqN0hPNGk3T1RrQklsbkpwdWxBMDJXdjB4VDJs flg=0x80000 cmp=android/com.android.internal.app.ResolverActivity (has extras)} from uid 10067 on display 0
04-20 11:11:45.359 I/ActivityManager(973): START u0 {act=android.intent.action.VIEW dat=https://play.google.com/store/apps/details?id=com.nowsci.ownnote&reviewId=Z3A6QU9xcFRPRzZrakczc2ttZUxFUm1NVXZjbHlkMjRiZUVlYW02MlNOdXhxTEk5ZFhBSkhjYUFaeGZqN0hPNGk3T1RrQklsbkpwdWxBMDJXdjB4VDJs flg=0x13080000 cmp=com.android.vending/com.google.android.finsky.activities.MainActivity (has extras)} from uid 10067 on display 0
04-20 11:12:36.272 I/ActivityManager(973): START u0 {act=android.intent.action.VIEW dat=https://play.google.com/store/apps/details?id=com.nowsci.ownnote&reviewId=Z3A6QU9xcFRPRzZrakczc2ttZUxFUm1NVXZjbHlkMjRiZUVlYW02MlNOdXhxTEk5ZFhBSkhjYUFaeGZqN0hPNGk3T1RrQklsbkpwdWxBMDJXdjB4VDJs flg=0x80000 cmp=android/com.android.internal.app.ResolverActivity (has extras)} from uid 10067 on display 0
04-20 11:12:38.778 I/ActivityManager(973): START u0 {act=android.intent.action.VIEW dat=https://play.google.com/store/apps/details?id=com.nowsci.ownnote&reviewId=Z3A6QU9xcFRPRzZrakczc2ttZUxFUm1NVXZjbHlkMjRiZUVlYW02MlNOdXhxTEk5ZFhBSkhjYUFaeGZqN0hPNGk3T1RrQklsbkpwdWxBMDJXdjB4VDJs flg=0x13080000 cmp=com.android.vending/com.google.android.finsky.activities.MainActivity (has extras)} from uid 10067 on display 0
04-20 11:12:42.842 I/ActivityManager(973): START u0 {act=android.intent.action.VIEW dat=https://play.google.com/store/apps/details?id=com.nowsci.ownnote&reviewId=Z3A6QU9xcFRPRzZrakczc2ttZUxFUm1NVXZjbHlkMjRiZUVlYW02MlNOdXhxTEk5ZFhBSkhjYUFaeGZqN0hPNGk3T1RrQklsbkpwdWxBMDJXdjB4VDJs flg=0x80000 cmp=android/com.android.internal.app.ResolverActivity (has extras)} from uid 10067 on display 0
04-20 11:12:46.964 I/ActivityManager(973): START u0 {act=android.intent.action.VIEW dat=https://play.google.com/store/apps/details?id=com.nowsci.ownnote&reviewId=Z3A6QU9xcFRPRzZrakczc2ttZUxFUm1NVXZjbHlkMjRiZUVlYW02MlNOdXhxTEk5ZFhBSkhjYUFaeGZqN0hPNGk3T1RrQklsbkpwdWxBMDJXdjB4VDJs flg=0x13080000 cmp=org.mozilla.firefox/.App (has extras)} from uid 10067 on display 0
04-20 11:53:23.712 I/Timeline(3508): Timeline: Activity_launch_request id:com.nowsci.ownnote time:38368727
04-20 11:53:23.712 I/ActivityManager(973): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.nowsci.ownnote cmp=com.nowsci.ownnote/.MainActivity bnds=[15,1803][297,2228] (has extras)} from uid 10014 on display 0
04-20 11:53:24.228 I/Timeline(973): Timeline: Activity_windows_visible id: ActivityRecord{37be6658 u0 com.nowsci.ownnote/.MainActivity t636} time:38369243
04-20 11:53:42.701 W/PackageManager(2546): Failure retrieving resources for com.nowsci.ownnote: Resource ID #0x0
04-20 11:53:45.424 V/WindowManager(973): Adding window Window{3ee87597 u0 Starting com.nolanlawson.logcat} at 29 of 33 (after Window{5f507e9 u0 com.nowsci.ownnote/com.nowsci.ownnote.MainActivity})

**Comment by Fmstrat** [comment]
Hi,

I'm not sure I understand exactly what you are describing above. Can you provide more details and/or a screenshot? Thanks.

**Comment by TheBready** [comment]
Hey Fmstrat,
I will try to explain it. 
For I got three notes:
Names
Cities
Colors
The contain of the notes on the server are :
Names {Peter, Steve, Tom}
Cities  {London,Berlin, Tokyo}
Colors { red, blue, green}
But I in the OwnNote app I got some thing like that:
Names { red, blue, green}
Cities   {Peter, Steve, Tom}
Colors {London,Berlin, Tokyo}

It´s shifted and I don´t know why.

cheers

Bready

**Comment by Fmstrat** [comment]
Well that's definitely a new one. I haven't seen this occur yet, so let's see if a couple more questions will help:
- How many of the notes were created in the Web App vs. the Android App?
- How many were assigned to groups on the Web App vs. the Android App?
- What version of the Android App are you running?
- Have you tried clearing data on the Android App, or logging out and logging back in?

If the logout/login doesn't work, I'll walk you through a debug mode to get more information.

**Comment by TheBready** [comment]
How many of the notes were created in the Web App vs. the Android App?
>  10 vs. 11
    How many were assigned to groups on the Web App vs. the Android App?
> 10 vs. 0
    What version of the Android App are you running?
> 0.0.12
    Have you tried clearing data on the Android App, or logging out and logging back in?
> not yet, will try it now.

**Comment by TheBready** [comment]
Deleted appdata and startet from a scratch and now everything is fine. Maybe something went wrong on the initial sync. 
Thanks and keep on improving.

**Comment by Fmstrat** [comment]
OK, great. If this happens again, please let me know so I can track it down. Thanks!
