### ISSUE TITLE
Android: Invalid username and/or password.

### ISSUE THREAD

**Issue by marcocarnazzo** [Fmstrat/ownnote#107]
I can't login into my ownCloud 8.0.2 from ownNote Android.
Error is "Invalid username and/or password".
Username and password are right. As server I wrote my ownCloud base url (https://owncloud.carnazzo.it) and I checked "Allow all SSL certificates".

Server log reports:
"Login failed: '<myusername> (Remote IP: 'xxx.xxx.xxx.xxx', X-Forwarder-For:'')

Can someone help me?

**Comment by Fmstrat** [comment]
Could you provide me any other log entries surrounding that message, such as access logs? I need to see what is being hit right before the error occurs. Also, what version of the Android app are you running and did this just start happening for you, or was it happening prior to version 0.0.11? Thanks.

**Comment by marcocarnazzo** [comment]
Sorry: I had 0.0.10 version. I believe in auto-upgrade :) .
Now it works. I had to:
1. Upgrade app manually (by Google Play).
2. Clean data (by Android settings / Applications).
3. Restart app.

**Comment by Fmstrat** [comment]
Glad that worked for you, thanks!
