### ISSUE TITLE
Delete notes => 100% cpu

### ISSUE THREAD

**Issue by LIyoai** [Fmstrat/ownnote#11]
When I try to delete a note Apache and Mysql uses 100% cpu and ownCloud stop to respond.
After restarting Apache ownCloud works again but note still exists

**Comment by Fmstrat** [comment]
That's very odd. ownNote doesn't use a database at all, as it uses the files in the Notes folder. If you go into the Notes folder and delete the file in the Files web interface, does it delete? Anything specific that makes this particular note unique (characters in the filename, etc)? Thanks.

**Comment by LIyoai** [comment]
When I delete file in filesystem in disappear in web interface.
There was nothing special on this note. Name was just "test" and "private" without any content.

**Comment by Fmstrat** [comment]
Very odd. Like I said, no DB usage at all so the only thing firing up mysql is owncloud core when it saves the file. Can you try completely removing the Notes folder, then going to the Notes app? It should create a new Notes folder and then let me know if the problem represents itself.

**Comment by LIyoai** [comment]
Deleted folder. New folder is created.
Problem still exists.
Restarting Apache helps to reduce cpu on Apache and Mysql to a normal level. But file is not deleted.

**Comment by Fmstrat** [comment]
OK, I'll need the ownCloud version, OS, and list of activated plugins to recreate your setup, then I'll keep attempting to repeat. I have a feeling there may be another plugin with overlapping JS commands.

**Comment by LIyoai** [comment]
Debian 7.8 (Stable - Wheezy)

ownCloud 7.0.4 (http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud)

Internal Apps:
Activity
Calendar
Contacts
Deleted files
First Run Wizard
Full Text Search
ownCloud dependencies info
PDF Viewer
Share Files
Text Editor
Updater
Versions
Video Viewer

3rd Party Apps:
App Framework 0.104
Music 0.3.4
News 4.3.0
Old Menu 1.2.1
OwnNote 0.0.2
Turn Off App Codechecker 1.0

**Comment by Fmstrat** [comment]
I know this is an old issue, but I still haven't been able to reproduce this. I set up a virtual machine with the above setup, and no luck. My next step is to fix the OC8 issue. If, after you upgrade to OC8, this issue still exists, please request this ticket reopened and I'll attempt to readdress it then, too.
