### ISSUE TITLE
Android:  0.0.12 : Still impossible to edit notes

### ISSUE THREAD

**Issue by lemagoup** [Fmstrat/ownnote#110]
Same problem than with ticket #91 

All app data cleaned, I start the app, I create a new note, and a blank screen appear once I click on the edit button. I cannot do anything. Then when going back, the following error : "TypeError: Cannot read property 'body' of undefined" pops up.

**Comment by Fmstrat** [comment]
What language is your device set to, and when you create the note, are there any errors on the server?

**Comment by lemagoup** [comment]
My device is set to French language, but I get the same behaviour with English language.
When I create the note on the Android app, I can see it and edit it on the server. I cannot see any error message related to the ownnote module on the server.

**Comment by Fmstrat** [comment]
OK, this latest version has a hidden debug option built into it. Are you familiar with out to pull an **adb logcat** fom Android? If so, I can walk you through enabling debug mode.

**Comment by lemagoup** [comment]
Yes I am familiar with debugging through logcat.

**Comment by Fmstrat** [comment]
Great. Let's try standard debugging first. All you have to do is login with *[DEBUG]username* instead of *username*. Then: *adb logcat |grep Cordo* and paste the output here. It would be helpful to delete the note on the server, create a note on the server, then provide a log from opening the App after that so that I can see if anything odd is happening during the synchronization of the note, not just when it is opened to be edited. Thanks.

**Comment by lemagoup** [comment]
//Login to the app, no notes on the server

D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : setUserPass
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : acceptAllCerts:false
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : startSync
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : app is online
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : syncAllNotes
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : syncnotesin:0
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : syncnotesout:0
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : checkForDuplicates
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : syncCheckNote
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : About to finish
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : syncFinished
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : Localnotes: 0
D/CordovaLog( 2524): file:///android_asset/www/js/index.js: Line 126 : buildListing

// Create a note on the server, then re launch the app

I/CordovaLog( 2830): Changing log level to DEBUG(3)
D/CordovaActivity( 2830): CordovaActivity.init()
I/dalvikvm( 2830): Could not find method android.webkit.WebView.setWebContentsDebuggingEnabled, referenced from method org.apache.cordova.CordovaWebView.enableRemoteDebugging
I/dalvikvm( 2830): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.CordovaWebView.initWebViewSettings
I/webkit/webview_proxy( 2830): WebView() constructor=org.apache.cordova.CordovaWebView@41b71438
D/CordovaActivity( 2830): CordovaActivity.createViews()
I/dalvikvm( 2830): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.CordovaWebViewClient.onReceivedClientCertRequest
I/dalvikvm( 2830): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.CordovaChromeClient.onShowFileChooser
D/CordovaWebView( 2830): CordovaWebView is running on device made by: Enspert
I/CordovaWebView( 2830): Disabled addJavascriptInterface() bridge since Android version is old.
D/CordovaWebView( 2830): >>> loadUrl(file:///android_asset/www/index.html)
D/CordovaWebView( 2830): >>> loadUrlNow()
D/CordovaActivity( 2830): Resuming the App
D/CordovaWebViewClient( 2830): onPageStarted(file:///android_asset/www/index.html)
D/CordovaActivity( 2830): onMessage(onPageStarted,file:///android_asset/www/index.html)
D/CordovaWebViewClient( 2830): onPageFinished(file:///android_asset/www/index.html)
D/CordovaActivity( 2830): onMessage(onPageFinished,file:///android_asset/www/index.html)
D/CordovaActivity( 2830): onMessage(spinner,stop)
V/InputMethodManager( 2830): Starting input: view=org.apache.cordova.CordovaWebView@41b71438
V/InputMethodManager( 2830): START INPUT: org.apache.cordova.CordovaWebView@41b71438 ic=android.webkit.WebViewClassic$WebViewInputConnection@41bfed68 tba=android.view.inputmethod.EditorInfo@41bff618 controlFlags=#100
D/CordovaNetworkManager( 2830): Connection Type: 4g
D/CordovaNetworkManager( 2830): Connection Extra Info: orange
D/CordovaNetworkManager( 2830): Connection Type: 4g
D/CordovaNetworkManager( 2830): Connection Extra Info: orange
D/CordovaActivity( 2830): onMessage(networkconnection,4g)
D/CordovaLog( 2830): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 39 : SQLitePlugin openargs: {"name":"ownnote.db"}
D/CordovaLog( 2830): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 49 : DB opened: ownnote.db
D/CordovaActivity( 2830): onMessage(spinner,stop)

// Login

D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : setUserPass
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : acceptAllCerts:false
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : startSync
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : app is online
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncAllNotes
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : New Remote Note found
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 155 : New Note:
D/CordovaLog( 2830): name: L-newNote R-newNote
D/CordovaLog( 2830): group:  
D/CordovaLog( 2830): mtime: 1429707708 1429707708 - Same mtime
D/CordovaLog( 2830): deleted: 0 0
D/CordovaLog( 2830): id: 250 250
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncnotesin:1
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncnotesout:0
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : checkForDuplicates
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncCheckNote
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncnotesin
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : Getting note
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncGotNote
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncCheckNote
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : About to finish
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : syncFinished
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : Localnotes: 1
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : buildListing

// The "newNote" appears in the list, I click on it
 
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : tinymceinited: false
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : updateViewer
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : resizeImages
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : makeLinks

// Then I click on Edit
 
D/CordovaLog( 2830): file:///android_asset/www/js/index.js: Line 126 : Caught link tap
D/CordovaLog( 2830): file:///android_asset/www/js/tinymce/themes/modern/theme.min.js: Line 1 : Uncaught TypeError: Object #<BarInfo> has no method 'split'

// -> it seems that there is an error with the BarInfo object (no method 'split')

**Comment by Fmstrat** [comment]
OK, that's definitely odd. Somehow on your device the code that grabs external links from notes and opens a browser is running when you tap them is firing when you press the Edit button. At least I know where this is coming from now so I should be able to find a way to recreate and remedy it. Thanks.

**Comment by lemagoup** [comment]
You're welcome.

**Comment by Fmstrat** [comment]
By the way, any interest in providing translations for French?

**Comment by lemagoup** [comment]
Yes why not. Will you release an open source version of your Android application ?

**Comment by Fmstrat** [comment]
I plan to once bug reporting slows to a crawl and the iOS version is out. Rational for why it's not out now can be found here: https://github.com/Fmstrat/ownnote/issues/53

If you are interested, I will supply you with a form that contains all the current strings in it for translation. Thanks again.

**Comment by lemagoup** [comment]
Thank you for the explanation (#53). I am in for helping you on the translations, waiting for the form :-)

**Comment by Fmstrat** [comment]
Great, thanks again. This bug has been fixed and will roll into regression testing with the large note bugs for v0.0.13 so I'm closing it out.

For translations, here is the form: https://docs.google.com/spreadsheets/d/1O61kZ0RbUFbnQuj8_EduZ76g5xleYxG66RakmN7AQ0c/edit?usp=sharing

And here is the open ticket you can continue to follow on it: https://github.com/Fmstrat/ownnote/issues/56
