### ISSUE TITLE
Android: Trim url to remove spaces

### ISSUE THREAD

**Issue by flemssound** [Fmstrat/ownnote#111]
Yes ownnote work fine on serverside in the wegGUI.

**Comment by Fmstrat** [comment]
Hi, 

Thanks for moving the conversation here.

> The request url /owncloud/index.php/apps/ownnote/api/ownnote/remoteindex was not found on this server. 

Based on the above, I *think* you may be entering the wrong server URL in the android App. Make sure you are entering your root ownCloud URL, such as:

    https://domain.tld/owncloud

and not:

    https://domain.tld/owncloud/index.php/apps/ownnote

Or any other combination that ends with ownnote.

If that doesn't fix it, I'd like to understand your server setup and what's been entered a bit so I can either help, or record this for a bug entry. A few questions:

- What is the root URL of your ownCloud instance? (De-identifing it is fine, I'm just trying to understand directory structure)
- What URL are you putting in the server setting for Android? (same as above)
- What version of the Android app are you running?
- Did this happen for you in a previous version of the Android App?

**Comment by flemssound** [comment]
my url is like this https://domain.tld/owncloud 
2. yes same as above
3. the newest verson from the play store 
4. i havn't tried it yet

**Comment by flemssound** [comment]
now it works. i had a space after the url :D

**Comment by Fmstrat** [comment]
Great. Switching this to an enhancement to trim spaces on the URL field in the Android app. Thanks.

**Comment by Fmstrat** [comment]
Complete for 13.
