### ISSUE TITLE
Android api error 

### ISSUE THREAD

**Issue by jinnstar** [Fmstrat/ownnote#114]
Unknow Error. 404;
Sabre\DAV\Exception\NotFound File with name
index.php/apps/ownnote/api/v0.2/ownnote/remoteindex
could not be located
![screenshot_2015-05-04-12-49-51](https://cloud.githubusercontent.com/assets/118368/7457745/ec5fbece-f25c-11e4-87a1-b72b3a3a39ab.png)

**Comment by jinnstar** [comment]
That did the trick. I'm not sure why I didn't think of that. Thank you very much for a quick resolution.

**Comment by Fmstrat** [comment]
Great, glad we could help. Don't forget to rate us in the Play Store and/or + us on apps.owncloud.org if you feel so inclined. Thanks!
