### ISSUE TITLE
Bulk deletion of notes

### ISSUE THREAD

**Issue by enekux** [Fmstrat/ownnote#115]
Hello,

I would like to bulk delete my notes ~2000. Is there any option to select all notes and delete?

Thank you.

**Comment by enekux** [comment]
Where is the ownote db stored? I would like to delete it...

The thing is that I tried to import my Evernote notes ~2000. The import did not work ok (most of my notes are webclips).

Then I tried to delete so to start from scratch, so I deleted all the notes from the /Notes folder.

But they come back... and I guess this is happening because the notes are in the database (.htm files).

So in admin panel I have changed the "How would you like to store your notes?" to "Database only" and now the /Notes folder is blank but the notes are still shown in my server.

That is why I would like to delete the notes in bulk or just wipe out the database.

How can I do that?

Thank you.

**Comment by Fmstrat** [comment]
Assuming you leave the devault oc_ prefix, all notes are stored in oc_ownnote and oc_ownnote_parts. You can delete all notes for a user with something like:

    delete from oc_ownnote_parts where id in (select id from oc_ownnote where uid = 'USERNAME');
    delete from oc_ownnote where uid = 'USERNAME';

If this doesn't work, let me know, otherwise feel free to close this issue. Thanks!

**Comment by enekux** [comment]
The first table "oc_ownnote_parts" is not existing in my db.
The second command did the trick.

Thank you very much for the fast response, I will be testing further the importing of Evernote notes...

**Comment by Fmstrat** [comment]
Ahh yes, sorry. The second table will exist in the next release of oN.
