### ISSUE TITLE
Android: Login 500 error

### ISSUE THREAD

**Issue by sbr9150** [Fmstrat/ownnote#120]
I installed android app today. First time login, I got a 500 error. What shall I do now?

**Comment by Fmstrat** [comment]
Hi, happy to help. First lets make sure it's not something simple, and then I can assist with debugging:

- What URL are you using? Make sure it's the same URL you would enter to log into owncloud, such as "https://www.site.ext/owncloud" and not anything more. Also, there is a bug outstanding where ending in a trailing slash fails, so make sure there isn't one until the next release rolls out.
- Are you using a self-signed cert? If so, you'll need to check the Accept all certs box.

Thanks.

**Comment by sbr9150** [comment]
Add "https://" in front of URL solve the problem. Thanks.

**Comment by Fmstrat** [comment]
Glad that worked. I've been adding code to "clean" URLs that are entered for the next version. I think I'll add this one, too.
