### ISSUE TITLE
index.php/apps/ownnote/api/v0.2/ownnote/remoteindex was not found on this server

### ISSUE THREAD

**Issue by shafik69** [Fmstrat/ownnote#124]
My Andoid device always produces this error.
Unknown Error. 404 
NOT FOUND

I looked up in the ftp and really there is no such folder /api in the apps/ownnote folder.
What could be the problem?
my path on the web is https//ssl-account.com/mydomain/owncloud/
I entered that in android.

**Comment by Fmstrat** [comment]
What specifically are you putting in the URL to connect? There have been a couple of issues logged that will be fixed in the next version, the most annoying being that if you include a trailing slash it fails (can't believe I missed that in testing). Try this:

    https://ssl-account.com/mydomain/owncloud

And see if that works.

**Comment by shafik69** [comment]
ok worked out

2015-05-15 21:53 GMT+02:00 Fmstrat <notifications@github.com>:

**Comment by Fmstrat** [comment]
Glad that helped.
