### ISSUE TITLE
How to import HTML file into Onwnote?

### ISSUE THREAD

**Issue by hitam4450** [Fmstrat/ownnote#128]
Well, how to import a HTML file into ownnote? I do not see any chances resp. menu item to do like this!

Regards, hitam4450

**Comment by Fmstrat** [comment]
Hi,

You'll need your server set to `Files and Database` for storage, at least while you do this. You can set it back to `Database only` afterwards. The full instruction set is in the README on the main screen of this repository: https://github.com/Fmstrat/ownnote

Thanks!

**Comment by hitam4450** [comment]
Hi, in the README.md there is no information at all, you are talking resp. writiing about!

Regards, hitam4450

**Comment by Fmstrat** [comment]
I don't understand what you mean. If you scroll down on that link to: https://github.com/Fmstrat/ownnote#importing-from-evernote-or-other-html-notes there is an entire section labeled "Importing from Evernote or other HTML Notes"?

**Comment by Fmstrat** [comment]
> There is no information in the README.md provided how to set server set to Files and Database for storage

Ahh, now I understand. Login to ownCloud as your Admin user, and go to the Admin screen where you can change settings for ownCloud. There will be an ownNote section, and you can configure ownNote there. Thanks.

**Comment by hitam4450** [comment]
Ok, Thanks1
