### ISSUE TITLE
Can't save note if name changed

### ISSUE THREAD

**Issue by lmann99** [Fmstrat/ownnote#13]
If the name of a note is edited in the "Name:" field the 'Save' button doesn't do anything even if there are changes to the note content.  

If you revert the changes to the note name the 'Save' button functions normally and will save the note if the contents have been edited.

**Comment by Fmstrat** [comment]
Hmm.. Did another note exist with the same name?

**Comment by lmann99** [comment]
No, only have two notes...

FYI I've relooked at httpd logs and found the cause of issue.  I have dokuwiki installed on system and have the owncloud dokuwiki plugin installed.  I use for common authentication but plugin also allows dokuwiki media files to be accessed from owncloud and it looks like the plugin adds some checks on system file methods.  I've removed the plugin and both name and category are working as expected now!
