### ISSUE TITLE
Server: How to upgrade ownnote?

### ISSUE THREAD

**Issue by nicocans** [Fmstrat/ownnote#132]
hello,
i would like to upgrade from 0.0.5 to 0.0.8., with my existing notes.
thx.

**Comment by Fmstrat** [comment]
This is a very simple process. Simply replace the app/ownnote folder with the latest version, then visit ownCloud with your browser and you'll see a maintenance window with an update button. Click it, and you're in business.

**Comment by nicocans** [comment]
still not working, my notes don't appear.

**Comment by Fmstrat** [comment]
When you say your notes don't appear, do you mean the Notes app doesn't show up, or the list of notes inside it is empty? Can you provide an `ls -lR /path/to/owncloud/app/ownnote`?

**Comment by nicocans** [comment]
The list of notes is empty, whereas my old notes are still present in apps/files?dir=%2FNotes.

Part of the command result:
total 8
-rw-rw-r-- 1 www-data www-data 213 May 18 19:17 dialog.html
-rw-rw-r-- 1 www-data www-data 658 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/example_dependency:
total 4
-rw-rw-r-- 1 www-data www-data 73 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/fullpage:
total 8
-rw-rw-r-- 1 www-data www-data 6291 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/fullscreen:
total 4
-rw-rw-r-- 1 www-data www-data 1540 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/hr:
total 4
-rw-rw-r-- 1 www-data www-data 322 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/image:
total 8
-rw-rw-r-- 1 www-data www-data 5187 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/importcss:
total 4
-rw-rw-r-- 1 www-data www-data 1872 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/insertdatetime:
total 4
-rw-rw-r-- 1 www-data www-data 1978 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/jbimages:
total 60
drwxrwxr-x 4 www-data www-data 4096 May 28 12:23 ci
-rw-rw-r-- 1 www-data www-data 4218 May 18 19:17 config.php
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 css
-rw-rw-r-- 1 www-data www-data 1491 May 18 19:17 dialog.htm
-rw-rw-r-- 1 www-data www-data 1153 May 18 19:17 dialog-v4.htm
-rw-rw-r-- 1 www-data www-data  877 May 18 19:17 editor_plugin.js
-rw-rw-r-- 1 www-data www-data 2980 May 18 19:17 editor_plugin_src.js
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 img
-rw-rw-r-- 1 www-data www-data  787 May 18 19:17 is_allowed.php
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 js
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 langs
-rw-rw-r-- 1 www-data www-data 1040 May 18 19:17 plugin.js
-rw-rw-r-- 1 www-data www-data  510 May 18 19:17 plugin.min.js
-rw-rw-r-- 1 www-data www-data  351 May 18 19:17 readme

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci:
total 16
drwxrwxr-x 8 www-data www-data 4096 May 28 12:23 application
-rw-rw-r-- 1 www-data www-data 6356 May 18 19:17 index.php
drwxrwxr-x 6 www-data www-data 4096 May 28 12:23 system

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application:
total 28
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 config
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 controllers
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 errors
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 helpers
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html
drwxrwxr-x 5 www-data www-data 4096 May 28 12:23 language
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 views

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/config:
total 80
-rw-rw-r-- 1 www-data www-data  3088 May 18 19:17 autoload.php
-rw-rw-r-- 1 www-data www-data 12818 May 18 19:17 config.php
-rw-rw-r-- 1 www-data www-data  1558 May 18 19:17 constants.php
-rw-rw-r-- 1 www-data www-data  3211 May 18 19:17 database.php
-rw-rw-r-- 1 www-data www-data  1138 May 18 19:17 doctypes.php
-rw-rw-r-- 1 www-data www-data  1781 May 18 19:17 foreign_chars.php
-rw-rw-r-- 1 www-data www-data   498 May 18 19:17 hooks.php
-rw-rw-r-- 1 www-data www-data   114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data  1282 May 18 19:17 migration.php
-rw-rw-r-- 1 www-data www-data  4453 May 18 19:17 mimes.php
-rw-rw-r-- 1 www-data www-data   564 May 18 19:17 profiler.php
-rw-rw-r-- 1 www-data www-data  1579 May 18 19:17 routes.php
-rw-rw-r-- 1 www-data www-data  3295 May 18 19:17 smileys.php
-rw-rw-r-- 1 www-data www-data   264 May 18 19:17 uploader_settings.php
-rw-rw-r-- 1 www-data www-data  5589 May 18 19:17 user_agents.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/controllers:
total 8
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data 3687 May 18 19:17 uploader.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/errors:
total 20
-rw-rw-r-- 1 www-data www-data 1160 May 18 19:17 error_404.php
-rw-rw-r-- 1 www-data www-data 1156 May 18 19:17 error_db.php
-rw-rw-r-- 1 www-data www-data 1147 May 18 19:17 error_general.php
-rw-rw-r-- 1 www-data www-data  288 May 18 19:17 error_php.php
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/helpers:
total 8
-rw-rw-r-- 1 www-data www-data 114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data  88 May 18 19:17 jbimages_helper.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/language:
total 12
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 english
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 french
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 russian

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/language/english:
total 8
-rw-rw-r-- 1 www-data www-data 114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data 271 May 18 19:17 jbstrings_lang.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/language/french:
total 16
-rw-rw-r-- 1 www-data www-data 2592 May 18 19:17 imglib_lang.php
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data  226 May 18 19:17 jbstrings_lang.php
-rw-rw-r-- 1 www-data www-data 2081 May 18 19:17 upload_lang.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/language/russian:
total 16
-rw-rw-r-- 1 www-data www-data 2011 May 18 19:17 imglib_lang.php
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data  347 May 18 19:17 jbstrings_lang.php
-rw-rw-r-- 1 www-data www-data 2117 May 18 19:17 upload_lang.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/application/views:
total 12
-rw-rw-r-- 1 www-data www-data 694 May 18 19:17 ajax_upload_result.php
-rw-rw-r-- 1 www-data www-data 456 May 18 19:17 blank.php
-rw-rw-r-- 1 www-data www-data 114 May 18 19:17 index.html

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/system:
total 20
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 core
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 helpers
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html
drwxrwxr-x 3 www-data www-data 4096 May 28 12:23 language
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 libraries

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/system/core:
total 200
-rw-rw-r-- 1 www-data www-data  2949 May 18 19:17 Benchmark.php
-rw-rw-r-- 1 www-data www-data 11392 May 18 19:17 CodeIgniter.php
-rw-rw-r-- 1 www-data www-data 13417 May 18 19:17 Common.php
-rw-rw-r-- 1 www-data www-data  8157 May 18 19:17 Config.php
-rw-rw-r-- 1 www-data www-data  1567 May 18 19:17 Controller.php
-rw-rw-r-- 1 www-data www-data  4695 May 18 19:17 Exceptions.php
-rw-rw-r-- 1 www-data www-data  4697 May 18 19:17 Hooks.php
-rw-rw-r-- 1 www-data www-data   114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data 18324 May 18 19:17 Input.php
-rw-rw-r-- 1 www-data www-data  3632 May 18 19:17 Lang.php
-rw-rw-r-- 1 www-data www-data 30576 May 18 19:17 Loader.php
-rw-rw-r-- 1 www-data www-data  1190 May 18 19:17 Model.php
-rw-rw-r-- 1 www-data www-data 12935 May 18 19:17 Output.php
-rw-rw-r-- 1 www-data www-data 12394 May 18 19:17 Router.php
-rw-rw-r-- 1 www-data www-data 22006 May 18 19:17 Security.php
-rw-rw-r-- 1 www-data www-data 14443 May 18 19:17 URI.php
-rw-rw-r-- 1 www-data www-data  3584 May 18 19:17 Utf8.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/system/helpers:
total 8
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data 1409 May 18 19:17 language_helper.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/system/language:
total 8
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 english
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/system/language/english:
total 12
-rw-rw-r-- 1 www-data www-data 2011 May 18 19:17 imglib_lang.php
-rw-rw-r-- 1 www-data www-data  114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data 1619 May 18 19:17 upload_lang.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/ci/system/libraries:
total 72
-rw-rw-r-- 1 www-data www-data 37341 May 18 19:17 Image_lib.php
-rw-rw-r-- 1 www-data www-data   114 May 18 19:17 index.html
-rw-rw-r-- 1 www-data www-data 27548 May 18 19:17 Upload.php

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/css:
total 8
-rw-rw-r-- 1 www-data www-data 4069 May 18 19:17 dialog.css
-rw-rw-r-- 1 www-data www-data 1293 May 18 19:17 dialog-v4.css

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/img:
total 8
-rw-rw-r-- 1 www-data www-data  230 May 18 19:17 jbimages-bw.gif
-rw-rw-r-- 1 www-data www-data 1737 May 18 19:17 spinner.gif

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/js:
total 8
-rw-rw-r-- 1 www-data www-data 2754 May 18 19:17 dialog.js
-rw-rw-r-- 1 www-data www-data 2796 May 18 19:17 dialog-v4.js

owncloud/apps/ownnote/js/tinymce/plugins/jbimages/langs:
total 24
-rw-rw-r-- 1 www-data www-data  819 May 18 19:17 en_dlg.js
-rw-rw-r-- 1 www-data www-data  376 May 18 19:17 en.js
-rw-rw-r-- 1 www-data www-data  919 May 18 19:17 fr_dlg.js
-rw-rw-r-- 1 www-data www-data  390 May 18 19:17 fr.js
-rw-rw-r-- 1 www-data www-data 1704 May 18 19:17 ru_dlg.js
-rw-rw-r-- 1 www-data www-data  501 May 18 19:17 ru.js

owncloud/apps/ownnote/js/tinymce/plugins/layer:
total 4
-rw-rw-r-- 1 www-data www-data 2857 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/legacyoutput:
total 4
-rw-rw-r-- 1 www-data www-data 3200 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/link:
total 8
-rw-rw-r-- 1 www-data www-data 4389 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/lists:
total 8
-rw-rw-r-- 1 www-data www-data 7899 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/media:
total 32
-rw-rw-r-- 1 www-data www-data 20017 May 18 19:17 moxieplayer.swf
-rw-rw-r-- 1 www-data www-data  9890 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/nonbreaking:
total 4
-rw-rw-r-- 1 www-data www-data 655 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/noneditable:
total 8
-rw-rw-r-- 1 www-data www-data 4722 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/own_checkbox:
total 4
-rw-rw-r-- 1 www-data www-data 990 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/pagebreak:
total 4
-rw-rw-r-- 1 www-data www-data 1192 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/paste:
total 16
-rw-rw-r-- 1 www-data www-data 15359 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/preview:
total 4
-rw-rw-r-- 1 www-data www-data 1389 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/print:
total 4
-rw-rw-r-- 1 www-data www-data 293 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/save:
total 4
-rw-rw-r-- 1 www-data www-data 1163 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/searchreplace:
total 8
-rw-rw-r-- 1 www-data www-data 6301 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/spellchecker:
total 12
-rw-rw-r-- 1 www-data www-data 9397 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/tabfocus:
total 4
-rw-rw-r-- 1 www-data www-data 1258 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/table:
total 28
-rw-rw-r-- 1 www-data www-data 28320 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/template:
total 8
-rw-rw-r-- 1 www-data www-data 4232 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/textcolor:
total 4
-rw-rw-r-- 1 www-data www-data 3696 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/textpattern:
total 4
-rw-rw-r-- 1 www-data www-data 2751 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/visualblocks:
total 8
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 css
-rw-rw-r-- 1 www-data www-data 1153 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/visualblocks/css:
total 8
-rw-rw-r-- 1 www-data www-data 5070 May 18 19:17 visualblocks.css

owncloud/apps/ownnote/js/tinymce/plugins/visualchars:
total 4
-rw-rw-r-- 1 www-data www-data 1074 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/plugins/wordcount:
total 4
-rw-rw-r-- 1 www-data www-data 908 May 18 19:17 plugin.min.js

owncloud/apps/ownnote/js/tinymce/skins:
total 4
drwxrwxr-x 4 www-data www-data 4096 May 28 12:23 lightgray

owncloud/apps/ownnote/js/tinymce/skins/lightgray:
total 88
-rw-rw-r-- 1 www-data www-data  1082 May 18 19:17 content.inline.min.css
-rw-rw-r-- 1 www-data www-data  1498 May 18 19:17 content.min.css
drwxrwxr-x 2 www-data www-data  4096 May 28 12:23 fonts
drwxrwxr-x 2 www-data www-data  4096 May 28 12:23 img
-rw-rw-r-- 1 www-data www-data 34834 May 18 19:17 skin.ie7.min.css
-rw-rw-r-- 1 www-data www-data 34058 May 18 19:17 skin.min.css

owncloud/apps/ownnote/js/tinymce/skins/lightgray/fonts:
total 112
-rw-rw-r-- 1 www-data www-data 10024 May 18 19:17 tinymce.eot
-rw-rw-r-- 1 www-data www-data 10316 May 18 19:17 tinymce-small.eot
-rw-rw-r-- 1 www-data www-data 21580 May 18 19:17 tinymce-small.svg
-rw-rw-r-- 1 www-data www-data 10128 May 18 19:17 tinymce-small.ttf
-rw-rw-r-- 1 www-data www-data  7848 May 18 19:17 tinymce-small.woff
-rw-rw-r-- 1 www-data www-data 20946 May 18 19:17 tinymce.svg
-rw-rw-r-- 1 www-data www-data  9860 May 18 19:17 tinymce.ttf
-rw-rw-r-- 1 www-data www-data  7664 May 18 19:17 tinymce.woff

owncloud/apps/ownnote/js/tinymce/skins/lightgray/img:
total 16
-rw-rw-r-- 1 www-data www-data   53 May 18 19:17 anchor.gif
-rw-rw-r-- 1 www-data www-data 2608 May 18 19:17 loader.gif
-rw-rw-r-- 1 www-data www-data  152 May 18 19:17 object.gif
-rw-rw-r-- 1 www-data www-data   43 May 18 19:17 trans.gif

owncloud/apps/ownnote/js/tinymce/themes:
total 4
drwxrwxr-x 2 www-data www-data 4096 May 28 12:23 modern

owncloud/apps/ownnote/js/tinymce/themes/modern:
total 8
-rw-rw-r-- 1 www-data www-data 6419 May 18 19:17 theme.min.js

owncloud/apps/ownnote/lib:
total 20
-rw-rw-r-- 1 www-data www-data 16022 May 18 19:17 backend.php
-rw-rw-r-- 1 www-data www-data   346 Mar 20 09:45 setval.php

owncloud/apps/ownnote/templates:
total 8
-rw-rw-r-- 1 www-data www-data 1354 May 18 19:17 admin.php
-rw-rw-r-- 1 www-data www-data  447 May 18 19:17 main.php

**Comment by Fmstrat** [comment]
Hmmm. What are the ownNote settings in the Admin screen? Did it somehow get set to DB only in the admin section?

**Comment by nicocans** [comment]
"Database and folder"
folder name: "Notes"

**Comment by Fmstrat** [comment]
Hmm.. Sorry this isn't an easy one for me. Can you send the output of:

    echo "select id, name, grouping, mtime, deleted from oc_ownnote where uid='<username>';" | mysql owncloud

... replacing <username> with your username (check case)? Also, any entries in the owncloud.log or apache log files?

Lastly, what are your server details? OS? Version of apache (or other http service)? etc. Thanks!

**Comment by nicocans** [comment]
Hello,
I think I found out why ownnote doesn't display my old notes in Notes web app: they are .txt, and new one created are .htm : is there a way to fix it or do I have to copy all my old notes to new format files?

**Comment by Fmstrat** [comment]
How were they labeled as .txt files? Were they from another app? If so, try renaming them to .html, then load the ownNote interface. It will attempt to import them.

**Comment by nicocans** [comment]
yes I did it: remaning to .htm make them appear in ownNote page.
