### ISSUE TITLE
Evernote Import process is stalling

### ISSUE THREAD

**Issue by bodam2005** [Fmstrat/ownnote#144]
I am attempting to import my Evernote notes and the import keeps stalling after a number of imports.  It could do 5 files or 80 but then it stalls.  I see this error repeated in my logs.  Any suggestions?  I am running the latest (0.0.8?) on OwnCloud 8.3.

Error	PHP	DOMDocument::loadHTML() expects parameter 1 to be a valid path, string given at /usr/local/www/owncloud/apps/ownnote/lib/backend.php#48	2015-05-29T00:22:17+00:00
Error	PHP	DOMDocument::loadHTML() expects parameter 1 to be a valid path, string given at /usr/local/www/owncloud/apps/ownnote/lib/backend.php#48	2015-05-29T00:22:17+00:00
Error	PHP	DOMDocument::loadHTML() expects parameter 1 to be a valid path, string given at /usr/local/www/owncloud/apps/ownnote/lib/backend.php#48	2015-05-29T00:22:16+00:00

**Comment by bodam2005** [comment]
I am also seeing this one occasionally:

Exception: {"Message":"Could not obtain lock type 1 on \"\/media\/files\/bodam\/files\/Notes\/ESM - Service Monitoring Issues and Challenge.html\".","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php(44): OCA\\Files_Locking\\Lock->addLock(1, NULL)\n#1 \/usr\/local\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php(80): OCA\\Files_Locking\\LockingWrapper->getLock('files\/Notes\/ESM...', 1)\n#2 \/usr\/local\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(212): OCA\\Files_Locking\\LockingWrapper->file_get_contents('files\/Notes\/ESM...')\n#3 \/usr\/local\/www\/owncloud\/lib\/private\/files\/view.php(838): OC\\Files\\Storage\\Wrapper\\Wrapper->file_get_contents('files\/Notes\/ESM...')\n#4 \/usr\/local\/www\/owncloud\/lib\/private\/files\/view.php(356): OC\\Files\\View->basicOperation('file_get_conten...', 'Notes\/ESM - Ser...', Array)\n#5 \/usr\/local\/www\/owncloud\/lib\/private\/files\/filesystem.php(645): OC\\Files\\View->file_get_contents('Notes\/ESM - Ser...')\n#6 \/usr\/local\/www\/owncloud\/apps\/ownnote\/lib\/backend.php(215): OC\\Files\\Filesystem::file_get_contents('Notes\/ESM - Ser...')\n#7 \/usr\/local\/www\/owncloud\/apps\/ownnote\/controller\/ownnoteapicontroller.php(45): OCA\\OwnNote\\Lib\\Backend->getListing('Notes', false)\n#8 [internal function]: OCA\\OwnNote\\Controller\\OwnnoteApiController->ajaxindex()\n#9 \/usr\/local\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#10 \/usr\/local\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#11 \/usr\/local\/www\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#12 \/usr\/local\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('OwnnoteApiContr...', 'ajaxindex', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#13 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#14 \/usr\/local\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#15 \/usr\/local\/www\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/ownnote\/a...')\n#16 \/usr\/local\/www\/owncloud\/index.php(36): OC::handleRequest()\n#17 {main}","File":"\/usr\/local\/www\/owncloud\/apps\/files_locking\/lib\/lock.php","Line":246}

**Comment by Fmstrat** [comment]
It looks like there are some locking issues with the filesystem. I'm not entirely sure what's happening from the logs as it looks like an error originating from the files_locking app and then being passed through to ownNote. Are you running encryption or any other apps?

**Comment by bodam2005** [comment]
No....could it be the desktop client trying to sync the changes?

**Comment by bodam2005** [comment]
OK...I feel stupid.  There was an app running called "file locking".  I disabled it and the import completed in a few minutes
![selection_0000041](https://cloud.githubusercontent.com/assets/6218673/7876327/e15cfcaa-057e-11e5-90d1-1d16b989346a.png)

**Comment by bodam2005** [comment]
I am new to OwnCloud (two weeks) and I just loaded your OwnNote app today.  I am really hoping to dump Evernote.  Any chance in getting a browser extension to capture text?  I use that a lot.

**Comment by Fmstrat** [comment]
This could certainly be added to the enhancement list. Just create a new ticket with that as a title and please include a link to the one you're using now for Evernote. Thanks.
