### ISSUE TITLE
Android: Application error : TypeError: Cannot read property 'body' of undefined.

### ISSUE THREAD

**Issue by jschuck** [Fmstrat/ownnote#145]
This happens with the current version 0.0.13 from the app store, but only on my Samsung Galaxy S3 Mini, which has Android 4.2.2 and Kernel 3.4.5. 

It happens everytime i try to open a note. Most of the time it just sits there with an empty note-area for a while and then drops me to the login screen with above error message.

Incidentally that does not happen with my Asus MeMo Pad HD 7, which has the same Android Version and the same Kernel version.

Would be nice if you could somehow get that fixed. Tell me what you need from me, if anything, and how i can find the info on the phone in question, so that this error can get sorted.

I would really like to use the app on my phone more so than on the tablet, to be honest.

Thanks.

**Comment by airasim** [comment]
Same issue on Wiko Cink Peax 2 - Android 4.1.2

**Comment by Fmstrat** [comment]
I think this may be related to this issue that I've already fixed and will be rolled out in the next version: https://github.com/Fmstrat/ownnote/issues/129

To validate it, and if you're willing to provide it and not concerend about your note names/groups being pasted here, the following would be extremely helpful:

1) Log into your ownCloud interface
2) Visit `https://<owncloudURL>/index.php/apps/ownnote/api/v0.2/ownnote/remoteindex`
3) Cut and paste the output here

`<owncloudURL>` should be wherever you have ownCloud installed, such as `https://host.ext/owncloud`

**Comment by airasim** [comment]
Hello fmstrat,

thank you for your answer. i hope that it is the same issue. this is my remoteindex:

"[{\"id\":\"4\",\"name\":\"Erstellt mit Owncloud\",\"group\":\"Sonstiges\",\"timestring\":\"6 hours\",\"mtime\":\"1432914736\",\"timediff\":24148,\"deleted\":\"1\"},{\"id\":\"5\",\"name\":\"Firefox-Wiederherstellungs-Schl\\u00fcssel\",\"group\":\"\",\"timestring\":\"1 month\",\"mtime\":\"1429551173\",\"timediff\":3387711,\"deleted\":\"1\"},{\"id\":\"20\",\"name\":\"Iris - Kropf\",\"group\":\"\",\"timestring\":\"1 month\",\"mtime\":\"1429945445\",\"timediff\":2993439,\"deleted\":\"0\"},{\"id\":\"18\",\"name\":\"Iris - Schl\\u00fcssel-Termin\",\"group\":\"\",\"timestring\":\"1 month\",\"mtime\":\"1429945412\",\"timediff\":2993472,\"deleted\":\"0\"},{\"id\":\"17\",\"name\":\"Iris - Termin\",\"group\":\"\",\"timestring\":\"1 month\",\"mtime\":\"1429945411\",\"timediff\":2993473,\"deleted\":\"1\"},{\"id\":\"19\",\"name\":\"Kropf\",\"group\":\"\",\"timestring\":\"1 month\",\"mtime\":\"1429945444\",\"timediff\":2993440,\"deleted\":\"1\"},{\"id\":\"14\",\"name\":\"Mozilla Sync
einrichten\",\"group\":\"\",\"timestring\":\"1 month\",\"mtime\":\"1429643855\",\"timediff\":3295029,\"deleted\":\"0\"},{\"id\":\"2\",\"name\":\"Test Notiz\",\"group\":\"privat\",\"timestring\":\"6 hours\",\"mtime\":\"1432914765\",\"timediff\":24119,\"deleted\":\"1\"},{\"id\":\"23\",\"name\":\"Verbindungen zur Arbeit\",\"group\":\"Arbeit\",\"timestring\":\"6 hours\",\"mtime\":\"1432914862\",\"timediff\":24022,\"deleted\":\"0\"},{\"id\":\"3\",\"name\":\"zweite Notiz\",\"group\":\"Arbeit\",\"timestring\":\"6 hours\",\"mtime\":\"1432914772\",\"timediff\":24112,\"deleted\":\"1\"}]"

Am 29. Mai 2015 22:32:33 MESZ, schrieb Fmstrat <notifications@github.com>:

**Comment by Fmstrat** [comment]
@airasim Unfortunately, it doesn't look like the same issue, though it's probably related. Do you know how to use logcat? If so, could you login with `[DEBUG]username` and pull a logcat with `adb logcat |grep Cordo`?

**Comment by jschuck** [comment]
Nonetheless i will provide you with my remoteindex data as well, it's just a bunch of testing stuff anyway.

"[{\"id\":\"4\",\"name\":\"Another Test\",\"group\":\"Test Group\",\"timestring\":\"19 hours\",\"mtime\":\"1432907305\",\"timediff\":68595,\"deleted\":\"0\"},{\"id\":\"1\",\"name\":\"Test Note\",\"group\":\"\",\"timestring\":\"19 hours\",\"mtime\":\"1432906619\",\"timediff\":69281,\"deleted\":\"0\"}]"

**Comment by jschuck** [comment]
And i'm back with some logcat magic.

This time it showed me the content of the first Note i tried, but dropped me with the error message as soon as i tried to edit it.

Afterwards it just failed with the error trying to open the second note.

Logfile below, personal information has been redacted.

    # adb logcat| grep Cordo
    I/CordovaLog(32425): Changing log level to DEBUG(3)
    D/CordovaActivity(32425): CordovaActivity.init()
    I/dalvikvm(32425): Could not find method android.webkit.WebView.setWebContentsDebuggingEnabled, referenced from method org.apache.cordova.CordovaWebView.enableRemoteDebugging
    I/dalvikvm(32425): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.CordovaWebView.initWebViewSettings
    D/CordovaActivity(32425): CordovaActivity.createViews()
    I/dalvikvm(32425): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.CordovaWebViewClient.onReceivedClientCertRequest
    I/dalvikvm(32425): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.CordovaChromeClient.onShowFileChooser
    D/CordovaWebView(32425): CordovaWebView is running on device made by: samsung
    D/CordovaWebView(32425): >>> loadUrl(file:///android_asset/www/index.html)
    D/CordovaWebView(32425): >>> loadUrlNow()
    D/CordovaActivity(32425): Resuming the App
    D/CordovaWebViewClient(32425): onPageStarted(file:///android_asset/www/index.html)
    D/CordovaActivity(32425): onMessage(onPageStarted,file:///android_asset/www/index.html)
    D/CordovaWebViewClient(32425): onPageFinished(file:///android_asset/www/index.html)
    D/CordovaActivity(32425): onMessage(onPageFinished,file:///android_asset/www/index.html)
    D/CordovaActivity(32425): onMessage(spinner,stop)
    D/CordovaNetworkManager(32425): Connection Type: wifi
    D/CordovaNetworkManager(32425): Connection Extra Info: "[REDACTED]"
    D/CordovaNetworkManager(32425): Connection Type: wifi
    D/CordovaNetworkManager(32425): Connection Extra Info: "[REDACTED]"
    D/CordovaActivity(32425): onMessage(networkconnection,wifi)
    D/CordovaLog(32425): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 39 : SQLitePlugin openargs: {"name":"ownnote.db"}
    D/CordovaLog(32425): file:///android_asset/www/plugins/com.triarc.sqlitePlugin/www/SQLitePlugin.js: Line 49 : DB opened: ownnote.db
    D/CordovaActivity(32425): onMessage(spinner,stop)
    D/CordovaLog(32425): file:///android_asset/www/js/tinymce/themes/modern/theme.min.js: Line 1 : Uncaught TypeError: Object #<BarInfo> has no method 'split'
    D/CordovaLog(32425): file:///android_asset/www/js/index.js: Line 914 : OWNNOTEERROR: TypeError: Cannot read property 'body' of undefined
    D/CordovaLog(32425): file:///android_asset/www/js/index.js: Line 914 : OWNNOTEERROR: TypeError: Cannot read property 'body' of undefined

**Comment by airasim** [comment]
I tried with CatLog but didn't get any logs. could you describe how it works?

**Comment by airasim** [comment]
Hum, i don't have root, so it unfortunately can't work...

Am 30. Mai 2015 01:30:18 MESZ, schrieb Fmstrat <notifications@github.com>:

**Comment by Fmstrat** [comment]
@airasim Yes, you would need root or use adb from a computer. That being said, the logs from @jschuck should help me figure this out. Thanks for the patience everyone.

**Comment by Fmstrat** [comment]
@jschuck So, this appears to be an issue with some content in the tinymce editor plugin vs. my app, but I still need to debug it to create a workaround for you guys. Could you let me know the content of the note titled `Another Test` in the group `Test Group`? You could find this by inspecting the source in your browser when editing the note.

The issue appears to actually be this:

    www/js/tinymce/themes/modern/theme.min.js: Line 1 : Uncaught TypeError: Object #<BarInfo> has no method 'split'

Which is either happening when the toolbar or menus are built, and the `body` error is just a symptom of that failure. I had previously thought that was due to some old code firing, but apparently not.

**Comment by jschuck** [comment]
There's really not much in those notes yet, just some nonsense. And since i'm in Database + File mode i had the note files synced to my desktop anyway, because of my curiosity.

The note in question contains the following:

    <p>M&ouml;glicherweise h&auml;tte ich hier was reinschreiben sollen.</p>
    <p>&nbsp;</p>
    <p>Dann schauen wir mal, was wir sonst noch haben.</p>
    <p style="padding-left: 30px;">This is a test</p>

So not really much. Without knowing anything about the inner workings of the app, i had an inkling that it might be a toolbar issue, since the display of the Samsung S3 Mini is relatively small.

**Comment by Fmstrat** [comment]
@jschuck The screen-size is an interesting angle, but I doubt that's it. To be sure, could you visit ownCloud using the phone's default browser, go to ownNote and see if the editor there causes issues?

**Comment by jschuck** [comment]
Before i start to explain what i see, and if it has anything to do with the problem, here's a screenshot:

[Imgur Link](http://imgur.com/5EC94ns)

**Comment by Fmstrat** [comment]
Yea, it's not display size.. Do you have a different browser set as default on those devices? Also, what is the original browser that came with each device?

**Comment by jschuck** [comment]
Whoops. Sorry, out of habit i used firefox. The pre-installed one is called "internet" and gives me a similar result:

[Second screenshot](http://imgur.com/VgcHJ6Y)

**Comment by airasim** [comment]
are you sure that it's a problem with the content of the notes? 

i just deleted all my notes (app&folder) and tried to generate and fill a new note within the app. i got the same issue...

with androids standard browser and owncloud there are no problems (like jschuck).

**Comment by Fmstrat** [comment]
@airasim No, it's definitely not the note content. It's something to do with the WYSIWYG editor (tinymce). I'm trying to figure out what would be different about each of these devices that would cause it to happen on one but not another. I'm at a bit of a loss there and just trying things right now to see if I can recreate it.

**Comment by airasim** [comment]
ok, thank you. let us know if you need more information about our phones...

**Comment by Fmstrat** [comment]
Huh, pure luck. Think I found it. Undeclared toolbar variable. Since I can't recreate the issue. I can only fix what I think is causing it. I'll release the fix in v1.0 which will come out shortly, and I'd love it if one of you could come back after that and let me know if it fixed things for you.

**Comment by jschuck** [comment]
Sure thing.

**Comment by Fmstrat** [comment]
Great, closing the issue but I'll re-open it if it continues after the 1.0 update. Thanks everyone.

**Comment by airasim** [comment]
issue is cleared with version 1.0 on my phone

**Comment by Fmstrat** [comment]
Great, thanks for the follow-up.

**Comment by jschuck** [comment]
Same here. After updating the phone and the server it works.
