### ISSUE TITLE
Android: Long press doesn't allow pasting on a new note

### ISSUE THREAD

**Issue by hulmgulm** [Fmstrat/ownnote#147]
I often want to copy information from e.g. Chrome into my notes. Unfortunately the editor does not show a paste context menu entry which would allow to paste information from the clipboard.

**Comment by Fmstrat** [comment]
What version of Android and ownNote are you running? If the keyboard is up in the editor, and I hold down my finger, it brings up the paste context for me on my test devices. Thanks.

**Comment by hulmgulm** [comment]
Small update:
I'm using a Nexus 4 device with Android 5.1.1.
I noticed that when I long press my finger into the empty edit field, I always get the context menu like in the web version of OwnNote.
If there's just a single character there, and I long press close to it, then I get the copy and past menu.
So I think this issue is mostly solved.

**Comment by Fmstrat** [comment]
Ahhhh, I can reproduce this now. Thanks.

**Comment by Fmstrat** [comment]
Context menu removed in all instances for next version.
