### ISSUE TITLE
Android: Invalid username and/or password

### ISSUE THREAD

**Issue by Takatango** [Fmstrat/ownnote#149]
Hi.
I have an android with 4.4, a selfhosted owncloud (ownCloud 8.0.3 (stable) / http://owncloud.mydomain.de)) , a selfsigned certificate and these nice app (0.0.13).
If i connect, I have an error "Invalid username and/or password".
I have deleted the app data and deinstalled the app,  then I installed the APP, but the error is the same.
I have deactivated ssl in my owncloud, but the error is the same.
Can everybody tell me a solution?
Thank You

**Comment by Fmstrat** [comment]
This sometimes happens if you don't check the "Accept all certs" box with a self hosted cert. Did you check that box? Logs from the ownCloud server would be helpful as well. Thanks.

**Comment by Fmstrat** [comment]
Also, make sure you're not checking accept all certs and then using an HTTP url. ownCloud also only works on one URL, the main one. If you normally use https://owncloud.mydomain.de and then try to use http://192.168.1.45/, ownCloud will not let you log in (You can confirm this in a browser on a machine separate from the ownCloud server). If you're testing that way, you would have to add the local hostname or IP to the config.php's domains:

      'trusted_domains' => 
      array (
        0 => 'owncloud.mydomain.de',
        1 => 'local.hostname.used',
      ),

**Comment by coolinger** [comment]
Same problem here.

From the Apache logs, it seems auth was successful...

cloud.coolinger.net:443 2002:55b5:31c9:0:8de5:9b53:fd79:d5f -  XXXX [03/Jun/2015:16:58:12 +0200] "GET /index.php/apps/ownnote/api/v0.2/ownnote/remoteindex HTTP/1.1" 302 1162 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.2; SM-N9005 Build/KOT49H)"
cloud.coolinger.net:443 2002:55b5:31c9:0:8de5:9b53:fd79:d5f -  XXXX [03/Jun/2015:16:58:12 +0200] "GET /index.php?redirect_url=%2Findex.php%2Fapps%2Fownnote%2Fapi%2Fv0.2%2Fownnote%2Fremoteindex HTTP/1.1" 200 3092 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.2; SM-N9005 Build/KOT49H)"

**Comment by Fmstrat** [comment]
@coolinger can you provide some specifics of your install? Did you try the above mentioned things such as the "Accept all certs"?

**Comment by Takatango** [comment]
in that config already is this:

 'trusted_domains' => 
  array (
    0 => 'owncloud.mydomain.de',
  ),

here are the last entries if i connectet with android:

Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:42+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:42+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:40+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:40+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:39+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:39+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:39+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:38+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:38+00:00

**Comment by Takatango** [comment]
and this...:

Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:39+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:39+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:38+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:38+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:37+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:37+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:37+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-03T15:15:36+00:00
Error	OC_USER_WEBDAVAUTH	Invalid Url: ""	2015-06-03T13:46:52+00:00
Error	OC_USER_WEBDAVAUTH	Invalid Url: ""	2015-06-03T07:29:53+00:00
Error	PHP	Array to string conversion at /home/www/owncloud/lib/private/l10n/string.php#75	2015-06-02T08:26:29+00:00

**Comment by Fmstrat** [comment]
@Takatango Are you using the "Accept all SSL Certificates" option?

**Comment by Fmstrat** [comment]
@Takatango Also, what URL are you putting into the Android app? I see that the error is for `OC_USER_WEBDAVAUTH` which is the webdav app, and shouldn't be triggered by ownNote.

Are you using the correct syntax:

    https://host.ext:port/owncloud

or webdav, which is incorrect:

    https://host.ext:port/owncloud/remote.php/webdav

Or some other derivative? Just trying to narrow out the easy stuff first.

**Comment by Takatango** [comment]
![screenshot_2015-06-03-15-44-33](https://cloud.githubusercontent.com/assets/12727129/7964019/ef67b3a8-0a15-11e5-8408-1e6099b06b90.png)

...this is all....

**Comment by Fmstrat** [comment]
Very odd.. I can't imagine this is it without me hearing it before, but let me make sure this isn't happening because ownCloud is installed in the root of the webserver. None of my test machines are setup that way. Thanks.

**Comment by Takatango** [comment]
i can deactivate all the other features in icloud....
i have only the plugins from owncloud direct

**Comment by Fmstrat** [comment]
Actually, can you provide me the process you used to move ownCloud to the root folder vs. the default /owncloud folder? This way I can make sure I'm replicating your setup exactly. Thanks.

**Comment by Takatango** [comment]
I created a subdomain an an installed a a preparatory picture from my provider.
then I went through step by step the installation.
All was okay to this point. No problems.
Also the Notes functioned.

**Comment by Fmstrat** [comment]
OK, having ownCloud in the root folder is definitely the issue. ownCloud recommends you not install into the root directory for many reasons, and the official iOS client has issues with it as well. The authentication issue listed above is one of the many issues I see in trackers and forums.

How did both of you force ownCloud into the root folder (The installer doesn't allow you to)? If I know that, I may be able to create a work-around, but no guarantees.

**Comment by Takatango** [comment]
okay. i have all apps deacativated an activated - without errors, and notes complete deleted an uploaded and now: it works :-)
...it works in serverroot :-)
i have only the problem mit certificate, but this is an android-4.4-bug.
:-)
thank you for help
