### ISSUE TITLE
Where to copy the line exactly ?

### ISSUE THREAD

**Issue by doucettom** [Fmstrat/ownnote#15]
Add the following to your owncloud/config/config.php:
'custom_csp_policy' => "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",

Where in the file should I copy it and what is this line doing exactly ? I am wondering because I am unable to copy images directly from clipboard (when printscreening)

**Comment by Fmstrat** [comment]
You should be able to place it anywhere that other lines similar are included. Cut/paste should work, have you tried another browser?

**Comment by doucettom** [comment]
I had it finally working but was unable to copy printscreen to clipboard then paste them in the notes. Copying images directly from website with ctrl+c worked though.

I upgraded to 8.0 and am waiting for 0.3 ;)

**Comment by Fmstrat** [comment]
Sounds good, .4 is out, working through .5 now. Let me know if you have any other issues/questions.
