### ISSUE TITLE
How to search in the notes?

### ISSUE THREAD

**Issue by arm2arm** [Fmstrat/ownnote#150]
hi,
How to search in the notes?
thanks.

**Comment by Fmstrat** [comment]
Unfortunately at the time you can't. I've got two enhancements, one for server https://github.com/Fmstrat/ownnote/issues/29 and one for Android https://github.com/Fmstrat/ownnote/issues/83 which will get implemented soon. v1.0 is on it's way out, so after that, the enhancements list will start to get run through. Thanks!
