### ISSUE TITLE
Android: Wrong note titles

### ISSUE THREAD

**Issue by elektronaut0815** [Fmstrat/ownnote#157]
Hi,

this one has been reported before: https://github.com/Fmstrat/ownnote/issues/106
Although I don't see a pattern here. Note content and titles are a mess on my phone, they don't correspond. 
I created about 15 notes in the web interface and then synchronized my Android phone.
On the server everything is fine. 

Anything I can check?

**Comment by Fmstrat** [comment]
Can you clear the app data on the Android device and re-login? If it's repeatable, I can show you how to login as a DEBUG user and provide a logcat to track it down.

**Comment by elektronaut0815** [comment]
Interesting, clearing the app data fixed it :-)
I did not even have to relogin, apparently I only deleted the notes folder.
Still something that should be inspected, I leave it to you if you want to close this issue.
Thanks for your help!

**Comment by Fmstrat** [comment]
I'm going to close this specific one, but I'm keeping my eye on it during my unit tests to see if I can reproduce. Thanks.
