### ISSUE TITLE
Server: update to 1.0 causes endless upgrade of owncloud (to 8.0.4)

### ISSUE THREAD

**Issue by georgmayer** [Fmstrat/ownnote#158]
Hi,

after installing the new 1.0 version into owncloud/apps/ownnote directory, my owncloud asks for an upgrade to 8.0.4 (which is already installed) - regardless whether I run that upgrade from command line (./occ upgrade) or via web (php), it never stops (did run for hours and hours now - tried that several times). 

I tried to copy 1.0 over the old (0.8) version of onwnnote as well as removing the old version and just copying the new 1.0 version. It's always the same.

Any hints how I can fix this?

Thanks and cheers,
Georg

**Comment by Fmstrat** [comment]
I've seen that happen on ownCloud  installations before. Its unlikely related specifically to ownNote, since there actually isn't anything happening with ownNote in maintenance mode (maintenance runs whenever an app with a DB is updated, even if nothing needs to occur).

A usual fix is to just bounce it out of maintenance mode with occ:  http://blog.jospoortvliet.com/2014/10/owncloud-stuck-in-upgrade.html?m=1

Let me know if that works for you.

**Comment by jancborchardt** [comment]
I have the same or a similar problem (installed ownNote from git): Every time I open ownNote I get a blank app and get logged out of ownCloud. This is the owncloud.log:
```
{"reqId":"MC6G+OQBGmomFO7Kuq9e","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: PHP_AUTH_USER at \/home\/jan\/owncloud\/lib\/private\/appframework\/middleware\/security\/corsmiddleware.php#81","level":0,"time":"2015-06-11T10:37:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ownnote\/api\/v0.2\/ownnote\/ajaxindex?_=1434019029741"}
{"reqId":"MC6G+OQBGmomFO7Kuq9e","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: PHP_AUTH_PW at \/home\/jan\/owncloud\/lib\/private\/appframework\/middleware\/security\/corsmiddleware.php#82","level":0,"time":"2015-06-11T10:37:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ownnote\/api\/v0.2\/ownnote\/ajaxindex?_=1434019029741"}
{"reqId":"MC6G+OQBGmomFO7Kuq9e","remoteAddr":"127.0.0.1","app":"PHP","message":"A session had already been started - ignoring session_start() at \/home\/jan\/owncloud\/lib\/private\/session\/internal.php#90","level":0,"time":"2015-06-11T10:37:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ownnote\/api\/v0.2\/ownnote\/ajaxindex?_=1434019029741"}
{"reqId":"MC6G+OQBGmomFO7Kuq9e","remoteAddr":"127.0.0.1","app":"core","message":"Login failed: '' (Remote IP: '127.0.0.1)","level":2,"time":"2015-06-11T10:37:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ownnote\/api\/v0.2\/ownnote\/ajaxindex?_=1434019029741"}
{"reqId":"MC6G+OQBGmomFO7Kuq9e","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OC\\\\AppFramework\\\\Middleware\\\\Security\\\\SecurityException\",\"Message\":\"CORS requires basic auth\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/middlewaredispatcher.php(92): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#1 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#2 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(107): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#3 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('OwnnoteApiContr...', 'ajaxindex', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(867): OC\\\\Route\\\\Router->match('\\\/apps\\\/ownnote\\\/a...')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/security\\\/corsmiddleware.php\",\"Line\":86}","level":4,"time":"2015-06-11T10:37:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ownnote\/api\/v0.2\/ownnote\/ajaxindex?_=1434019029741"}
```

**Comment by Fmstrat** [comment]
What does your config.php look like? Any custom settings?

**Comment by jancborchardt** [comment]
@Fmstrat this is my config.php:
```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => '[censored]',
  'passwordsalt' => '[censored]',
  'secret' => '[censored]',
  'trusted_domains' => 
  array (
    0 => 'localhorst',
    1 => 'rechenknecht.local',
  ),
  'datadirectory' => '/home/jan/owncloud/data',
  'overwrite.cli.url' => 'http://localhorst/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.6',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
  'app.mail.imaplog.enabled' => true,
  'appstore.experimental.enabled' => true,
);

**Comment by Fmstrat** [comment]
@jancborchardt do you have any browser settings related to not storing cookies or session variables? What browser are you using and does it happen on all browsers?

**Comment by jancborchardt** [comment]
@Fmstrat yes, I always use latest ownCloud master (I’m a core dev). I don’t have any specific browser settings set and it happens for both Firefox and Chrome.

**Comment by simonspa** [comment]
For me the upgrade process worked. I just updated owncloud to 8.0.4, upgrade went smooth. Then I updated ownNote from 0.0.8 to 1.0 (copied over the files) and got the upgrade page again. Then running the upgrade gave me

```
$ ./occ upgrade
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated <ownnote> to 1.0
Turned off maintenance mode
Update successful
```

...and everything went fine afterwards. Let me know if I can provide useful information...

**Comment by t0mcat1337** [comment]
Hi everybody,

I'm not having any problems in upgrading Owncloud/Ownnote to the last versions, BUT suddenly I have absolutly the same behaviour @jancborchardt described:
1) Log in to Owncloud
2) Choose the ownnote app
=> A blank page is displayed
=> This is in the log:
{index} Exception: {"Exception":"OC\\AppFramework\\Middleware\\Security\\SecurityException","Message":"CORS requires basic auth","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/appframework\/middle
ware\/middlewaredispatcher.php(92): OC\\AppFramework\\Middleware\\Security\\CORSMiddleware->beforeController(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#1 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispa
tcher.php(88): OC\\AppFramework\\Middleware\\MiddlewareDispatcher->beforeController(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http
\\Dispatcher->dispatch(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('OwnnoteApiContr...', 'ajaxindex
', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#4 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#5 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object
(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#6 \/var\/www\/owncloud\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/ownnote\/a...')\n#7 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#8 {main}","File":"\/var\/www
\/owncloud\/lib\/private\/appframework\/middleware\/security\/corsmiddleware.php","Line":86}

What I'm wondering about most is this line:
"Message":"CORS requires basic auth"

What needs basic auth and why?? 

Anyway... I hacked a little to make Apache use basic auth for owncloud... Now my Notes are displayed again, BUT:
When I want to open one or create a new one nothing happens. Then this is in owncloud.log:
ownCloud[9237]: {no app in context} CSRF check failed

and as Firebug shows,  Firefox gets an HTTP 500 error...

My environment:
Ubuntu 14.04.2 LTS
Owncloud stable from official repository:
http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/
current version 8.1.0-1
Nothing special in ownclouds config.php
Browser: Firefox 39

Any hint?

**Comment by Fmstrat** [comment]
@t0mcat1337 - Update to 1.02.

**Comment by Fmstrat** [comment]
@jancborchardt - Since you have the same issue (not the infinate update), I should mention that for you as well. Try updating to 1.02 as that bug was fixed.

**Comment by Fmstrat** [comment]
@georgmayer - Are you still having this issue? If not, I'd like to close this out. Thanks.

**Comment by jancborchardt** [comment]
Works fine for me now! :)
