### ISSUE TITLE
Simple question, what is the Server path to ownnote?

### ISSUE THREAD

**Issue by m-frank** [Fmstrat/ownnote#159]
Both on my iOS app and Desktop app I keep getting a error message when trying to connect to server: "Failed to connect to server".
Server path is set to: https://x.x.x.x/owncloud/
I've tried both external and internal IP address.
What am I doing wrong?

**Comment by weipah** [comment]
@m-frank I think you addressed the wrong repo here on github.
This one is for tracking issues about an OwnCloud App called "*ownnote*".

As for your issue I think you should consider diving into the documentation first.
You could start from here: https://doc.owncloud.org/server/8.0/admin_manual/

**Comment by Fmstrat** [comment]
Going to close this out since it's not for ownNote, but based on above I'd bet your issue is that you're using an IP and https. You need to use the hostname setup for the secure cert, and make sure it's the hostname ownCloud is set to use. Thanks.
