### ISSUE TITLE
OC8 Blank Screen

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#16]
I've tryed to use ownnote in OC8, app enabled, there is only a blank screen, unable to use it.

**Comment by apg1980** [comment]
today i tryed with oc 8 final.
after open notes app it will stuck in a blank screen. unable to view the categorys an notes.

**Comment by nethenic** [comment]
I confirm the issue in OC8, with an error in apache's log : "client denied by server configuration: [...]owncloud/data/htaccesstest.txt"
The problem is I don't have a such file ! Interesting...

**Comment by apg1980** [comment]
Can we fix this soon? I need the notes, cannot reverts back to 7.

**Comment by patrick17470** [comment]
The same for me:
 unable to use it.  white page only menu at the top
Do you have a solution ?

**Comment by Fmstrat** [comment]
Hey all. I'm upgrading to OC8 this weekend. I should have a fix out shortly after that.

**Comment by apg1980** [comment]
Are there any News or progress?

**Comment by Fmstrat** [comment]
Fixed in commit: https://github.com/Fmstrat/ownnote/commit/27675334530bd59be3061baac245d80cb757a4cc

Also included is the API for the upcoming mobile apps. New version will be on apps.owncloud.com shortly.
