### ISSUE TITLE
Server: [Feature Request] - Be able to insert pictures already uploaded in OC

### ISSUE THREAD

**Issue by weipah** [Fmstrat/ownnote#160]
The button for embedding images only allows for uploading new ones.

But I guess many ppl have already stored or synced their pictures somewhere in OwnCloud, so it would be nice if we could choose them from there directly.

What do you think?

PS.: Thanks for the app, keep up the good work! (-:

**Comment by Fmstrat** [comment]
I like it, and it's on the list from: https://github.com/Fmstrat/ownnote/issues/31
