### ISSUE TITLE
Auto save feature

### ISSUE THREAD

**Issue by blaskovic** [Fmstrat/ownnote#167]
Hi,

I would really appreciate auto-saving feature. I am just too lazy to click on Quick Save every time.

**Comment by Fmstrat** [comment]
The web interface already auto-saves when you are idle for a period of time. If you sit and watch, the quicksave button will highlight to indicate the autosave. Thanks for the feedback.

**Comment by dalethomas** [comment]
Is there any possibility to change the default time?  I think it is set at 60 seconds?  I would like it to save after 3 or 5 secs.

**Comment by Fmstrat** [comment]
I could look to make this an option in Admin? For now, just change this line: https://github.com/Fmstrat/ownnote/blob/master/js/script.js#L117

**Comment by dalethomas** [comment]
Awesome thank you!  This is great!

**Comment by Fmstrat** [comment]
I should note, you would also need to adjust this line: https://github.com/Fmstrat/ownnote/blob/master/js/script.js#L116

That identifies that it checks for idle every 20 seconds. You could try something like check for idle every 10 seconds, and save every 9, that way it would save on every check (when a change is detected). Not sure how that would work from a load perspective, though.

**Comment by Fmstrat** [comment]
And just to be 100% clear:

checkDuration = The number of seconds between each "check" to see if the user is idle.
saveTime = The number of seconds that the user has to be idle for before the "check" initiates an auto-save

So, in the default, it checks every 20 seconds, and if one of the checks reports idle for longer than 60, it auto-saves. So, the current auto-save is really anywhere from 60-80 seconds, depending on when you went idle between the checks.

**Comment by dalethomas** [comment]
Got it.  That makes sense.  I just tried putting it at 3 seconds and noticed it wasn't auto saving every 3 seconds.  I will take a peak shortly.  

This is a great tool!  Going to give up Evernote!
