### ISSUE TITLE
Server: Add de_DE - OwnNote App not in my language

### ISSUE THREAD

**Issue by weipah** [Fmstrat/ownnote#170]
Hi,

I see there are different language files in /oc/apps/ownnote/l10n/
* *.js
* *.json
* *.php

Although German files are included the OwnNote server app is only in English. The rest of my OC apps appear in German correctly.

Am I missing some kind of switch somewhere?

Thanks in advance.

**Comment by Fmstrat** [comment]
Hi, if you visit this URL, what is displayed:

    http://aruljohn.com/language.php

I'm wondering if your default country code isn't covered in the translator. If that's the problem, it should be an easy fix. Also, what version of ownNote are you running?

**Comment by weipah** [comment]
@Fmstrat first of all, sorry for the late answer.
The following languages were detected:
* de-DE
* de
* en-US
* en

I'm using latest version of Chrome (43.0.2357.130 m), but the same happens in IE11.

**Comment by weipah** [comment]
@Fmstrat I copied all files  from de.* to de_DE.* and now it works.
That was indeed an easy fix.

**Comment by Fmstrat** [comment]
Thanks for the pull request, but I closed it because language files are automatically generated from Transifex. The ownNote Transifex account needs to be updated, which it will be once I address this ticket there.
