### ISSUE TITLE
Server: Cannot enable app on OwnCloud 8.1

### ISSUE THREAD

**Issue by fjc35** [Fmstrat/ownnote#174]
When I try to enable the app, I receive the following error message:
"Archives of type text/html are not supported"

Am I missing some configuration step or third party package ?

Thanks.

**Comment by blaskovic** [comment]
Similar here with 8.0.5.
I can enable it, but I can see just blank page and I am logged out of owncloud.

I think, developer is no longer maintaining this, which is pity..

**Comment by Fmstrat** [comment]
Yes, it is still being maintained, but my paying job has kept me out of town for a month.

These are likely two different t issues that I'll need to investigate when I get back.

The blank screen was something another user saw that they were able to fix on their own, so I'll try to dig that up.

**Comment by africanforest** [comment]
Hi,
I'm also seeing a blank page and reloading the page as well as clicking a link in the menu gets me logged out and redirected to the login page.
(ownCloud 8.1 RC2)

**Comment by StopTrain** [comment]
I can confirm that initial upgrade to 8.1 broke with ownnote enabled.  Disabled the app, downloaded the latest master.zip from git, copied it over, re-enabled it, and get the blank page as well.

Love the app though!  I use it EVERY day!  Keep up the good work.

**Comment by Fmstrat** [comment]
Once I get back this will be the first thing I investigate. Seems a number of people are running into this. Before than, any details that can be provided such as config.php's (minus keys), server OS, apache version, etc, would be helpful.

Also, if there is anything in the ownCloud log, or if you could trace the JS console with something like Firebug to see any JS errors, that would also be extremely handy.

**Comment by hulmgulm** [comment]
I see the following in the browser:
NetworkError: 500 Internal Server Error - http://www.schwubb.com/oc/index.php/apps/ownnote/api/v0.2/ownnote/ajaxindex?_=1436330159493

**Comment by beedaddy** [comment]
Regarding the blank page, this is what owncloud.log says:
>{"reqId":"+ObO5lDKggczYkC8sMJV","remoteAddr":"xxx.xx.xxx.xx","app":"index","message":"Exception: {\"Exception\":\"OC\\\\AppFramework\\\\Middleware\\\\Security\\\\SecurityException\",\"Message\":\"CORS requires basic auth\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/middlewaredispatcher.php(92): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('OwnnoteApiContr...', 'ajaxindex', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(867): OC\\\\Route\\\\Router->match('\\\/apps\\\/ownnote\\\/a...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/security\\\/corsmiddleware.php\",\"Line\":86}","level":4,"time":"2015-07-08T05:53:00+00:00"}

**Comment by beedaddy** [comment]
Perhaps more interesting, the Web Console tells me, that the *Content Security Policy* has blocked loading the ressource (sorry, the message is in German):
>Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://owncloud.my-domain.de 'unsafe-eval'").

**Comment by Fmstrat** [comment]
Looks like they changed the CORS implementation again. It's frustrating that everytime a new OC version rolls around they break the API. A good change on their part for security, but I really wish there was a system for announcements (or maybe there is and I'm unaware of them).

**Comment by Fmstrat** [comment]
Fixed for 1.01 release.

**Comment by fjc35** [comment]
My problem seems solved with 1.01.
Thank you !!!!
Frédéric

**Comment by africanforest** [comment]
Thank you for the fix! Now it works, and that's great!
 The only problem that i'm experiencing is, that embedding images is not possible. It just does nothing except for the cursor jumps to the first line after having clicked the button "Insert". (Btw, the window title should be: "Embed an image").

Thank you,
Michael

**Comment by milancoin-project** [comment]
When I try to enable the app, I receive the following error message:
"Archives of type text/html are not supported"

Am I missing some configuration step or third party package ?

Thanks.

ubuntu 16.04  owncloud 9.1.1
