### ISSUE TITLE
Open Notes directly from files view

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#18]
Everytime open a htm file from files app will open the note within the internal editor.
Is it possible to open directly with the ownnote app?

**Comment by Fmstrat** [comment]
Unfortunately I don't think this is possible without hacking into the files app which isn't possible since it's a built-in function of ownCloud. Sorry.

**Comment by mckaygerhard** [comment]
i have an idea..  when testing i installed the editdoc app and of course any html file are opened with editdoc

a wrapper can be that when a user made a note, and goes to open, the oc api can use the build in editor inside the ownnote!
