### ISSUE TITLE
Android v1.0: login credentials for only one server can be stored

### ISSUE THREAD

**Issue by j-ed** [Fmstrat/ownnote#186]
Currently it is only possible to save login credentials for one server. It is not possible to connect to different ownCloud servers without deleting previously entered login credentials and the need to re-enter them again.
It would be nice to have a dialog from which you can select to which server you want to connect, similar to the ownCloud app.

## Environment
Android v4.4.4

**Comment by Fmstrat** [comment]
Duplicate: https://github.com/Fmstrat/ownnote/issues/50
