### ISSUE TITLE
Android v1.0: unable to create a new group in the groups dialog

### ISSUE THREAD

**Issue by j-ed** [Fmstrat/ownnote#187]
If you select the groups dialog in the lower right corner of the app, all available groups are shown but it is not possible to create new group from that dialog. I think it would be helpful to add this function at that place to be more intuitive.

## Environment:
Android v4.4.4

**Comment by Fmstrat** [comment]
Unfortunately the way the underlying structure of the system is designed, an empty group does not exist, so it's only possible to create groups when a note is being placed there. Easier group creation (such as selecting existing groups) is in the works in another ticket. Thanks for the feeedback.
