### ISSUE TITLE
Server: Class appName does not exist

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#192]
after upgrading to 1.0.1 the logout issue is gone, but no notes appear:

owncloud 8.0.5

Fatal 	index 	Exception: {"Message":"Could not resolve appName! Class appName does not exist","Code":0,"Trace":"#0 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/utility\/simplecontainer.php(93): OC\\AppFramework\\Utility\\SimpleContainer->resolve('appName')\n#1 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/utility\/simplecontainer.php(55): OC\\AppFramework\\Utility\\SimpleContainer->query('appName')\n#2 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/utility\/simplecontainer.php(73): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/utility\/simplecontainer.php(93): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Ownnote\\\\Con...')\n#4 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/app.php(90): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Ownnote\\\\Con...')\n#5 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('OwnnoteAjaxCont...', 'ajaxindex', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/route\/router.php(252): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/base.php(791): OC\\Route\\Router->match('\/apps\/ownnote\/a...')\n#9 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":79} 	2015-07-08T18:17:48+02:00
Debug 	core 	OC\Tags::__construct, tags: Array ( [0] => OC\Tagging\Tag Object ( [owner:protected] => 08598A5C-6FB6-450C-A152-628B33F56156 [type:protected] => files [name:protected] => _$!<Favorite>!$_ [id] => 5 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer ) ) )

**Comment by Fmstrat** [comment]
Crud. Forgot to add the controller so it's only working on some systems. That's what I get for pushing a release remotely. I will update shortly.

**Comment by Fmstrat** [comment]
Added controller.
