### ISSUE TITLE
ON 1.01 on OC 8.0.5 shows empty page

### ISSUE THREAD

**Issue by hulmgulm** [Fmstrat/ownnote#193]
I just updated OwnNotes to 1.01 on my OC 8.0.5 but I still get an empty page and see the following errors in FF console:

Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://blubb 'unsafe-eval'").

"NetworkError: 500 Internal Server Error - http://blubb/oc/index.php/apps/ownnote/ajax/v0.2/ownnote/ajaxindex?_=1436381871138"

OC Log shows the following fatal error:
Exception: {"Message":"Could not resolve appName! Class appName does not exist","Code":0,"Trace":"#0 \/var\/www\/html\/oc\/lib\/private\/appframework\/utility\/simplecontainer.php(93): OC\\AppFramework\\Utility\\SimpleContainer->resolve('appName')\n#1 \/var\/www\/html\/oc\/lib\/private\/appframework\/utility\/simplecontainer.php(55): OC\\AppFramework\\Utility\\SimpleContainer->query('appName')\n#2 \/var\/www\/html\/oc\/lib\/private\/appframework\/utility\/simplecontainer.php(73): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/var\/www\/html\/oc\/lib\/private\/appframework\/utility\/simplecontainer.php(93): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\Ownnote\\Con...')\n#4 \/var\/www\/html\/oc\/lib\/private\/appframework\/app.php(90): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\Ownnote\\Con...')\n#5 \/var\/www\/html\/oc\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('OwnnoteAjaxCont...', 'ajaxindex', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/html\/oc\/lib\/private\/route\/router.php(252): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/html\/oc\/lib\/base.php(791): OC\\Route\\Router->match('\/apps\/ownnote\/a...')\n#9 \/var\/www\/html\/oc\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/html\/oc\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":79}

**Comment by Fmstrat** [comment]
Duplicate of: https://github.com/Fmstrat/ownnote/issues/192

Already fixed and published on apps.owncloud.org as 1.02.

As a note, your unsafe-eval error is likely not from ownNote, but from something else.

**Comment by hulmgulm** [comment]
1.02 works. Thank you!
