### ISSUE TITLE
Server: Latest CSP changes in ownCloud core block base64 images

### ISSUE THREAD

**Issue by africanforest** [Fmstrat/ownnote#194]
When i try to embed an image, it seems that nothing happens, only the cursor jumps up to the very beginning of the content (text for example), but the image that has been inserted, is not visible.

When i save that note and examine it through the files app later, then, surprisingly, i can see the base64 code of the inserted image in the html source.

Obviously ownnote does not decode the base64 code correctly, so that an embedded image doesn't show up?

(ownCloud 8.1, ownnote 1.0.2)

**Comment by Fmstrat** [comment]
Yay, they increased content security policies again without external knowledge. Very frustrating. It looks like ownCloud core is no longer allowing base64 images to be displayed. This is a HUGE issue for any system like ownNote as it requires revamping the entire way images are stored, especially for the mobile application. Next on my list I guess.

**Comment by africanforest** [comment]
Well, that's really bad. Is using base64 a security risk? 
It seems that there is a lack of communication between core developers and app developers. To be able to store images in notes is actually one of the most important features. I have no clue how this is done in evernote...?

**Comment by Fmstrat** [comment]
It's not really a security risk. The problem is that that ownCloud sells the core system with a service contract. So security for them is "limit anything we don't use to be safe."

Don't worry, I've already started a workaround. Its just forcing me to focus on the backend for file attachment sooner than I would have liked, taking me away from iOS.

**Comment by Fmstrat** [comment]
Haha, I spend a ton of time figuring out how to make it work with standard image tags vs. base64, and after digging through the ownCloud core GitHub account figure out the change to CSP allows apps to specify their own CSP. Fixed it with 4 lines of code, just need to finalize testing. Well, I've got the backend for filestorage now.

**Comment by Fmstrat** [comment]
Fixed in 1.03.

**Comment by africanforest** [comment]
Cool! Thanks so much! Works nicely now!
