### ISSUE TITLE
ownnote v1.03 - GUI unaccessible in ownCloud less than 8.1

### ISSUE THREAD

**Issue by j-ed** [Fmstrat/ownnote#198]
## Expected behavior
The ownNote GUI should be accessible from within ownCloud 8.0.5.

## Current behavior
A blanc page is shown in ownCloud 8.0.5 if the ownNote GUI is selected. The following error message is logged:
```
...,"app":"PHP","message":"Class 'OCP\\AppFramework\\Http\\ContentSecurityPolicy' not found at \/var\/www\/htdocs\/owncloud\/apps2\/ownnote\/controller\/pagecontroller.php#42","level":3,"time":"2015-07-10 16:39:59+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ownnote\/"}
```
I assume that the reason for the problem is, that `\OCP\AppFramework\Http\ContentSecurityPolicy` should be loaded although this class is first introduced in ownCloud 8.1.0. (see https://github.com/owncloud/news/issues/822#issuecomment-119829630). Therefore the news app e.g. first checks the existence of the file, before it is loaded. Most likely a similar check need to be added to the ownNote app too:
```
// set csp rules for ownCloud 8.1
if (class_exists('OCP\AppFramework\Http\ContentSecurityPolicy')) {
    $csp = new \OCP\AppFramework\Http\ContentSecurityPolicy();
    ...
```
**A fall-back to v1.02 fixes the problem for me.**

## Steps to repoduce
1. Login to ownCloud 8.0.5
2. Choose the ownNote app

#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.0.5

#### Client Configuration
Browser: Firefox 39.0
Operating system: Windows 7

**Comment by Fmstrat** [comment]
Interesting, something must be wrong with my regression sanity checks. I'll need to put a version check around that. I'll knock that out this weekend. Thanks.

**Comment by apg1980** [comment]
me either:

Whitescreen on oc 8.0.5 after enabling and updating database of 1.0.3:

Debug 	core 	OC\Tags::__construct, tags: Array ( [0] => OC\Tagging\Tag Object ( [owner:protected] => 08598A5C-6FB6-450C-A152-628B33F56156 [type:protected] => files [name:protected] => _$!<Favorite>!$_ [id] => 5 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer ) ) ) 	2015-07-10T17:34:56+02:00
Error 	PHP 	Class 'OCP\AppFramework\Http\ContentSecurityPolicy' not found at /OWNCLOUD-DATA/opt/bitnami/apps/owncloud/htdocs/apps/ownnote/controller/pagecontroller.php#42 	2015-07-10T17:34:37+02:00
Debug 	core 	OC\Tags::__construct, tags: Array ( [0] => OC\Tagging\Tag Object ( [owner:protected] => 08598A5C-6FB6-450C-A152-628B33F56156 [type:protected] => files [name:protected] => _$!<Favorite>!$_ [id] => 5 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer ) ) ) 	2015-07-10T17:34:31+02:00
Debug	core	OC\Tags::__construct, tags: Array ( [0] => OC\Tagging\Tag Object ( [owner:protected] => 08598A5C-6FB6-450C-A152-628B33F56156 [type:protected] => files [name:protected] => _$!<Favorite>!$_ [id] => 5 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer ) ) ) 	2015-07-10T17:34:31+02:00
Error	PHP	Class 'OCP\AppFramework\Http\ContentSecurityPolicy' not found at /OWNCLOUD-DATA/opt/bitnami/apps/owncloud/htdocs/apps/ownnote/controller/pagecontroller.php#42

**Comment by Fmstrat** [comment]
This is fixed.

As a note, if you are running 8.0.5, image insertion will not work. ownCloud core developers made a change in 8.0.5 that locked down the use of inline base64 images, but did not include an API to allow them until 8.1. For images to work, you must upgrade to 8.1 or downgrade.

**Comment by blue-bean** [comment]
Mmh - really?
I'm still on ownCloud 8.0.5 and installed ownNote 1.0.3 (with manually revoked commit https://github.com/Fmstrat/ownnote/commit/d95879db247ec0f7d3d8ab2293e167fe2278039f , i.e. an ownNote 1.0.2). I can insert an resize pictures.

**Comment by Fmstrat** [comment]
Then 1.04 should work for you. It's possible the reports I got from users were wrong, but my understanding was the CSP changes started in the minor version. In any event, if revoking that commit works for you, then 1.04 will, too.

**Comment by blue-bean** [comment]
Confirmed - version 1.04 works with ownCloud 8.0.5 without problems in my case (ownCloud fresh installation).

**Comment by j-ed** [comment]
```
As a note, if you are running 8.0.5, image insertion may not work. It has been reported (but not fully confirmed) that ownCloud core developers made a change in 8.0.5 that locked down the use of inline base64 images, but did not include an API to allow them until 8.1. For images to work, you may need to upgrade to 8.1 or downgrade.
```
What do you exactly mean? I've upgrade ownNote to v1.05 on ownCloud 8.0.5 and I'm still able to insert picture without a problem.

**Comment by Fmstrat** [comment]
@j-ed It seems this is a non issue and the reports I received were incorrect. I will revise the release notes on apps.owncloud.org.
