### ISSUE TITLE
[Solved] No wysiwyg editor after creation of new note

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#2]
I've installed the app and also added the line:
'custom_csp_policy' => "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
to the config.php.
i can open the ownnote app and are able to create new notes. i cannot open the new note and i am unable to get the editor.
sync client is downloading new html files after creation of new note.
i am also unable to add a category.

owncloud logs:
Error 	PHP 	Use of undefined constant listing - assumed 'listing' at /data/opt/bitnami/apps/owncloud/htdocs/apps/ownnote/ajax/listing.php#26 

* ownCloud 7.0.4
* PHP 5.4.35
* ubuntu 14.4 *bitnami

[Sollution] It's working fine if asset-pipeline.enabled is false within config.php

**Comment by Fmstrat** [comment]
Thanks. If I see this error come up from any other users, I will add it to the instructions.
