### ISSUE TITLE
Server: Support embedding local media files

### ISSUE THREAD

**Issue by oparoz** [Fmstrat/ownnote#205]
### Workflow

1. User clicks on "insert image" icon
2. File picker lets user pick any media file supported by the system
3. App sends request to core to get thumbnail
4. App embeds thumbnail

#### Caveats

* Thumbnail is never updated and won't reflect the true content of the file, but that's the same for any embedded media currently. One has to delete and re-add images which were updated if he wants his not to be up to date

*Note: I did search, but couldn't find any similar requests*

**Comment by Fmstrat** [comment]
I'm a little confused on if this is a request or a bug report I'm not understanding. Right now, a file picker doesn't display if you click on an image in the web interface for me. Is it for you? If so, what browser are you using? Thanks.

**Comment by oparoz** [comment]
It's a feature request. I've updated the OP, because it wasn't clear. The first step is to click on the image icon which is used to insert images in a note.

**Comment by Fmstrat** [comment]
Got it, thanks. So, this isn't exactly a duplicate, but I'm marking it as one because this workflow will be covered in https://github.com/Fmstrat/ownnote/issues/191 and https://github.com/Fmstrat/ownnote/issues/31.

**Comment by oparoz** [comment]
Yep, that's correct, thanks.
