### ISSUE TITLE
Server: PHP error when $HTTP_RAW_POST_DATA is not populated

### ISSUE THREAD

**Issue by fumazu** [Fmstrat/ownnote#206]
After setting *always_populate_raw_post_data* to *-1* in the php.ini, as it is encouraged in the [PHP documentation](https://secure.php.net/manual/de/ini.core.php#ini.always-populate-raw-post-data), I started getting PHP errors when accessing the notes app while the announcement was displayed.

`Error PHP Undefined variable: curl1 at /var/www/owncloud/apps/ownnote/lib/backend.php#30`
`Error PHP curl_setopt() expects parameter 1 to be resource, null given at /var/www/owncloud/apps/ownnote/lib/backend.php#30`

Dismissing the announcement and reversing the php.ini change suppressed the error messages.

**Comment by Fmstrat** [comment]
Fixed for next release.
