### ISSUE TITLE
Groups in sidebar as drop-down with direct acces to the notes

### ISSUE THREAD

**Issue by batzillm** [Fmstrat/ownnote#209]
Is it possible to show and access the notes directly in the left sidebar and make the groups shown in the sidebar expandable similar to the RSS News Reader of owncloud. Accessing notes would be faster and one would save a unnecesary click.

**Comment by Fmstrat** [comment]
There is a full redesign planned for v2 leveraging a side menu once all the base features are in place. While this isn't exactly what will happen, there will be some changes to the groupings. Thanks for the feedback.
