### ISSUE TITLE
Server: ownNotes doesn't open notes, when asset pipeline is enabled

### ISSUE THREAD

**Issue by africanforest** [Fmstrat/ownnote#210]
'asset-pipeline.enabled' => true,

While the list of notes does show up, notes can't be opened, all i get is a blank page.
(Firefox, Safari on MacBook)

**Comment by awardzone** [comment]
hi, 
same problem OC 8.1
I've checked web root (and subfolder) ownership and is ok. 
Any hint?

**Comment by africanforest** [comment]
Just want to add that the editor is also gone of course.
Since that app is a quite important one, i hope this will be fixed soon.

**Comment by Fmstrat** [comment]
Duplicate: https://github.com/Fmstrat/ownnote/issues/70

Unfortunately the way asset pipeline works in OC it doesn't take into account plugins that reference other JS files, and there is no reliable programmatic way to determine if it's running. While this gap in coverage doesn't affect many apps, it does effect the WYSUWYG plugin, meaning I have to rewrite someone else's code to fix it. That being said, it's on the list, however.
