### ISSUE TITLE
 SSL certificate error SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by BenS89** [Fmstrat/ownnote#212]
Sometimes, I get this error in ownNote 1.0.5: curl failed: SSL certificate problem, verify that the CA cert is OK, Details: error: 14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.

I have a valid SSL-certificate from StartSSL which is accepted by all modern browsers. In addition, I get an A+-Rating from SSL-Labs (for more details, see this link here: https://www.ssllabs.com/ssltest/analyze.html?d=benschnarr.com&hideResults=on). Therefore, my SSL is configured properly. I disabled SSLv3 because of poodle.

I use a QNAP NAS System with embedded Linux (QTS 4.1.4). Maybe, it could be a platform specific problem because of an old curl version?

In addition, I have those two errors in the ownCloud logs:

<code>Undefined variable: curl1 at /share/MD0_DATA/Web/owncloud/apps/ownnote/lib/backend.php#30</code>

<code>curl_setopt() expects parameter 1 to be resource, null given at /share/MD0_DATA/Web/owncloud/apps/ownnote/lib/backend.php#30</code>

Thank you very much

**Comment by Fmstrat** [comment]
When you say "sometimes" what do you mean? Is there a specific task causing that, or does it happen all the time, or on specific clients?

The error being reported by OC is definitely a bug which I will address, but I don't think it's causing the SSL issue since it's for the announcement in the server app: https://github.com/Fmstrat/ownnote/issues/206

I'll start to look at the certificate results above and compare to my StartSSL server. Could you supply your apache config?

**Comment by BenS89** [comment]
This error does not occur in the Android app, but in the ownCloud webinterface, look at this screenshot: https://benschnarr.com/owncloud/index.php/s/q5oLt3NqubpoQu6

This is my apache-ssl.conf

```xml
LoadModule ssl_module modules/mod_ssl.so
LoadModule headers_module modules/mod_headers.so

SSLRandomSeed startup file:/dev/urandom 512
Listen 443
AddType application/x-x509-ca-cert .crt
AddType application/x-pkcs7-crl    .crl
SSLPassPhraseDialog  builtin
SSLSessionCache        "shmcb:/usr/local/apache/logs/ssl_scache(512000)"
SSLSessionCacheTimeout  300
SSLMutex  "file:/usr/local/apache/logs/ssl_mutex"
<Directory />
	Options FollowSymLinks
	AllowOverride None
	Order deny,allow
	Deny from all
	SSLRequire %{SSL_CIPHER} !~ m/^(EXP|NULL)/
</Directory>
<VirtualHost _default_:443>
DocumentRoot "/share/Web"
ErrorLog /dev/null
TransferLog /dev/null
SSLEngine on
SSLHonorCipherOrder on
SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!DH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
SSLProtocol All -SSLv2 -SSLv3
SSLCertificateFile "/etc/stunnel/stunnel.pem"
#SSLCertificateKeyFile "/etc/config/apache/server.key"
SSLCertificateChainFile "/etc/stunnel/uca.pem"
#SSLCACertificatePath "/etc/config/apache/ssl.crt"
#SSLCACertificateFile "/etc/config/apache/ssl.crt/ca-bundle.crt"
#SSLCARevocationPath "/etc/config/apache/ssl.crl"
#SSLCARevocationFile "/etc/config/apache/ssl.crl/ca-bundle.crl"
#SSLVerifyClient require
#SSLVerifyDepth  10

Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"

<FilesMatch "\.(cgi|shtml|phtml|php)$">
    SSLOptions +StdEnvVars
</FilesMatch>
<Directory "/usr/local/apache/cgi-bin">
    SSLOptions +StdEnvVars
</Directory>

BrowserMatch ".*MSIE.*" \
         nokeepalive ssl-unclean-shutdown \
         downgrade-1.0 force-response-1.0

</VirtualHost>        
```

Until now, I could not figure out which operation caused this. It happens rarely. But I am trying to figure this out.

**Comment by Fmstrat** [comment]
Actually, I think I was wrong, I think it is related to the announcement error. It pulls the announcement from GitHub via SSL, and perhaps on your setup curl is throwing an error due to the "curl1" issue. I've already fixed that in master, so after the next release this may go away.

**Comment by BenS89** [comment]
Great! I will test this as soon as the new version gets released.
