### ISSUE TITLE
Cannot install on OC 7.0.7: not allowed call "OC_L10N::"

### ISSUE THREAD

**Issue by mklemme1** [Fmstrat/ownnote#218]
I cannot install this app on my OC 7.0.7 and OC 7.0.6

I go to "Apps", "OwnNode" and press "Activate"
On OC 7.0.7  I get a proper error message
"The application cannot be installed due to not allowed code"

```
Error core Die Applikation kann auf Grund von unerlaubtem Code nicht installiert werden 2015-08-02T09:59:00+00:00
Error core App "ownnote" is using a not allowed call "OC_L10N::". Installation refused. 2015-08-02T09:59:00+00:00 
```

**Comment by Fmstrat** [comment]
Do you have any specific security limitations in your config php?

**Comment by mklemme1** [comment]
I am not aware of any.
Where would I look in config.php?
