### ISSUE TITLE
editable by shared users when in Notes directory a note are shared!

### ISSUE THREAD

**Issue by mckaygerhard** [Fmstrat/ownnote#23]
i made some tests: and theres a little bug:

* goes to Notes app button
* create a note
* made someting and save and close
* now goes to files app button
* goes to notes directory and choose the recently created note
* share the selected file note with some user
* when sharing, does not permit editable to that users (read only permission)
* logout and login with the user that u saherd the file note
* goes to same notes app (of course the shared will be put in same folder due oc7 new api feature)
* open the file in ownnote
* file are editable...!!!!!!!!

**Comment by Fmstrat** [comment]
Since sharing isn't implemented yet, I wouldn't consider this a bug, but I will reference this when I implement sharing into ownNote.

**Comment by mckaygerhard** [comment]
do u see the steps and the results? u'r notes does not respect the permissions!
