### ISSUE TITLE
Anyone asked for a search feature yet?

### ISSUE THREAD

**Issue by tudza** [Fmstrat/ownnote#230]
Can't find a way to search for a string over all notes or even within one note.

**Comment by dhunt84971** [comment]
Agreed.  A search feature would make this MUCH more usable.

**Comment by Fmstrat** [comment]
If you search for search, you find: https://github.com/Fmstrat/ownnote/issues/83

:)

It's definitely on the list. Unfortunately I haven't had as much time as I would like recently to contribute new features to the project, but I'm sure this will hit the list at some point.
