### ISSUE TITLE
Clicking on link to anchor in notes does not take me to that section of the note

### ISSUE THREAD

**Issue by tudza** [Fmstrat/ownnote#234]
When I download the html and open it in a browser clicking on a link takes me to the part of the document I expect, so I have the links correct.

**Comment by Fmstrat** [comment]
Unfortunately I don't think this is a fixable element. When HTML is placed into ownNote, it is rendered and processed by a WYSIWYG editor. This process allows the editor to give you the ability to change content while keeping most of the HTML intact, however a side-effect is that it eliminates some of the functionality, such as anchor links.
