### ISSUE TITLE
Display in Apps inconsistent

### ISSUE THREAD

**Issue by Wrumm** [Fmstrat/ownnote#235]
I used this server app before by directly downloading the app from github. With changing to OC 8.1 I saw in the app overview that it is approved so I deleted the version I had installed in the app overview and installed the approved version under "tools". Now under "tools" I can see, that the approved version is installed. But under "activated" it is telling me again, that is is only "experimental".

**Comment by Fmstrat** [comment]
This is likely because there is a random flag in the ownCloud DB that doesn't reset. I have that happen on my testing machines to, and haven't yet taken the time to report a bug at ownCloud core. I wouldn't worry about it.
