### ISSUE TITLE
[OSX] Integration in OSX-Notes-App

### ISSUE THREAD

**Issue by stonerl** [Fmstrat/ownnote#236]
Is it somehow possible to add ownnote to the OSX-Internet-Accounts to use it with the local Note-App?

**Comment by madmas** [comment]
Would be nice, but #244 adresses basically the same topic; providing a desktop app.

**Comment by stonerl** [comment]
Not quite the same. I did not ask for an app. OSX and also Gnome have a so called Online Account Setting. When you add an account e.g. Google the OAS asks the server what kind of services are provided. E.g. WebDAV/card DAV... Every app that implements this feature is then able to use this account and its features. E.g. on OSX Calendar uses the owncloud Calendars. If the app would provide such a service via remote.php on would simply add the owncloud account and could use whatever app.

**Comment by madmas** [comment]
ah, you're right.
would be nice, I agree. Though, I would expect to run into a format problem. If I understand it correctly, ownnote relies on HTML to format the notes. The MacOSX notes app seems to use just plantext .
Though, would be woth an attempt :) do oyu now a resource with more details on providing a compatible interface for OSX ?

**Comment by Fmstrat** [comment]
Unfortunately I'm going to close this request out. While I would love to do this, the default OS notes apps don't have the same backend HTML functionality that ownNote does. A separate desktop app will be required.
