### ISSUE TITLE
[FEATUREREQUEST] prove browseable files from owncloud (code are yet done)

### ISSUE THREAD

**Issue by mckaygerhard** [Fmstrat/ownnote#24]
i see that ownnote uses base64 for store images inside the html file---

in app.owncloud.org theres the edit doc app.. now for oc7.. this has some code for use the files from sotrage user...

the feature reques its to use the broseable files of user storage in the notes files ...
the usage of base 64 for storing inside the images are great but users cannot manage those files.. 

of course, the code are crappy.. theres many errors using the api but  i tested puting the owncloud instalation in root html directory of webserver and works nice..

**Comment by Fmstrat** [comment]
I considered creating a seperate store for images instead of base64, but base64 still proves to be the most reliable way in OC. 

Are you also requesting to have an option to "import" an image from the users files directory into the note?

**Comment by mckaygerhard** [comment]
yes indeed! of course the base64 implementation are very brave idea!

**Comment by Fmstrat** [comment]
This is going to be handled in the file attachment enhancement when that rolls around, so I'm closing out this request.
