### ISSUE TITLE
Server: can't change storage setting

### ISSUE THREAD

**Issue by D4nielB** [Fmstrat/ownnote#240]
I can't change the storage method from "Database and Filesystem" to "Database only" (I'm using the german translation, so sorry if the above isn't exactly what it might say in the english version). When choosing the new setting in the dropdown list, it's accepted and the field is greyed out again, but it doesn't seem to get stored. When reloading the admin interface, it shows "Database and Filesystem" again, and a testnote still gets stored in the file system.

**Comment by D4nielB** [comment]
Running OC 8.1.3 and ON 1.05

**Comment by Tsuroerusu** [comment]
I have a possibly related issue where I cannot change the folder name from "Notes" to "Notater" (Danish).

**Comment by Fmstrat** [comment]
Is anything displayed in the owncloud log file?

**Comment by necken** [comment]
I have the same issue, nothing in log files.
Can't change storage, folder or announcements

**Comment by D4nielB** [comment]
Nothing to see in the OC logfile accessible from the OC admin panel. Anywhere else I could look?

**Comment by Fmstrat** [comment]
Enough people are seeing this that I'm going to log it. I'm using the same configuration saving method as others, but for some reason it's not working here. I'll just add a "Save" button.

Out of curiosity, is anyone logged out when they try to change the setting? I've seen some weird CORS issues cause that in the past.

**Comment by team4music** [comment]
Same here i can't also change the storage method. Isn't there any update on this =/

**Comment by palto42** [comment]
I have the same issue, can't change any of the ownNote settings in the Admin page. 
Observed the problem already in ownCloud 8.2 and just upgrades to latest OC 9.0.1 - no change.
App version is latest 1.07, running ownCloud on Raspberry Pi Debian Jessie with Nginx 1.6.2-5 and php5-fpm 5.6.19.

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/ownnote/commit/1f0a01710326b15316d496397877038ba32ed417

**Comment by tudza** [comment]
Thanks for the fix.

I was pleased to see that notes I created while in Database only mode had files created for them immediately after I updated the app.
