### ISSUE TITLE
MyOwnNotes Android app: "Not getting correct JSON from server. Server OK?"

### ISSUE THREAD

**Issue by msiep** [Fmstrat/ownnote#242]
OwnNote seems to be working fine on my OwnCloud 8.1 server, but the MyOwnNotes Android app (from F-Droid.org) says "Not getting correct JSON from server. Server OK?"

**Comment by improti** [comment]
With the latest updates the error for me changed to something like "URL doesn't seem to exist". Using the same URL works in the browser though and the self-signed certificate known to Android. For me this is on Cyanogen 12 btw.

**Comment by dradux** [comment]
I am getting the same error. 
Exact error message is: "Not getting correct JSON from server. Server OK?"
Versions
* MyOwnNotes: 1.6 (installed from f-droid.org)
* OwnNote: 1.05

**Comment by improti** [comment]
Oh, to clarify above the above ... If I use the URL as I enter it in the settings, I get to owncloud and can use it in the browser. If I, however, use the URL from logcat, it only seems to work (no error), but gives only a blank page.

**Comment by steppenhahn** [comment]
the only serverapp that works with myownnotes is "Notes" by Bernhard Posselt and Jan-Christoph Borchardt.
you have to use it in order to use myownnotes.

**Comment by improti** [comment]
Hm, looking for that I found https://apps.owncloud.com/content/show.php/Notes?content=155599 - last updated 2013 and "not yet compatible with OC 5" or something. Seems to be something old that never got removed. There is a comment pointing to https://github.com/owncloud/notes as the new version, so that's probably what steppenhahn meant. Will try that next ...

**Comment by msiep** [comment]
@steppenhahn thank you!  I was trying to use it with OwnNote 1.05 by Ben Curtis (AGPL-licensed) which is offered within OwnCloud.  Now that I followed the installation and enabling instructions at https://github.com/owncloud/notes and am using the correct Notes app on OwnCloud, MyOwnNotes is syncing with it just fine.

Evidently I'm not the only one who has been confused about which server app MyOwnNotes is supposed to work with.  How about updating the error message "Not getting correct JSON from server. Server OK?" to help others avoid similar confusion in future?  How about this:

"Not getting correct JSON from server. Is the app at https://github.com/owncloud/notes installed and enabled?"

**Comment by Fmstrat** [comment]
@msiep Yes, they're two different apps. The Notes app is the original plain-text only application, while ownNote supports images and formatted content. Sorry for the confusion.
