### ISSUE TITLE
still Android-Client Version 1.0 via google play store. V1.05 released!?

### ISSUE THREAD

**Issue by RalfWW** [Fmstrat/ownnote#245]
Hi,

I see here in github, that version 1.05 is available. But there is no update from Version 1.0 in google's play store for the Android client available!?

I'm hoping that the issue "offline notes not possible" (sceduled for V 1.01) is solved with 1.05!?

Gruss

Ralf

**Comment by milankni** [comment]
@RalfWW: What makes you believe that version numbering of the Android and Server apps is the same? Android client source code does not seem to exist in GitHub.

**Comment by RalfWW** [comment]
@milankni: ... wrong thinking :-/
Software is not a public one.

I want to get rid of the annoying restriction not to add a note offline. This is - at least - a permanent problem with one of my devices....
