### ISSUE TITLE
Any chance to breathe some life back into Shorten?

### ISSUE THREAD

**Issue by cs39** [Fmstrat/ownnote#247]
I would love to see Shorten revived with YOURLS support. Is there any chance of making that happen? Thanks in advance.

**Comment by Fmstrat** [comment]
Closing this since this is already listed in the Shorten repository. Shorten is still alive and well, with YOURLS support on the future list. In fact, it just hit v0.0.12 today.

**Comment by Fmstrat** [comment]
As a note, this was added in v13 today.
