### ISSUE TITLE
[IMPORTANTCHANGE] change category system to directory equivalent as oc does

### ISSUE THREAD

**Issue by mckaygerhard** [Fmstrat/ownnote#26]
naming sheme of the files notes shows that group are inside the name of the file, so renaming makes complicated if changes both thins at same time.. also remains in problems with sharing...

a directory based category system will enable and solve sharing issues:

currently owncloud uses same behabior for users files.. and makes sense... when user has the client app in desktop.. this also helps for the qownnotes app usage

if u using directories system, for categories.. u can made that two actions at same time... due are differents actions, separately and changes will not afected to users when sharing....

and then later use the database only for speedup...

he problem if u sing database for categories are the performance.. u can gain performance if data directory are around a shared network mount.. bt loses data organization.. u could see how oc does:

app will not be fault tolerant across data backup of users.. and users will lose all ur' customised 

os stores in db only path hash and in each load regenerate it if necesary..

**Comment by Fmstrat** [comment]
I'm not sure I follow everything being typed above. However, I did not use folder storage because I will likely implement tagging into grouping, meaning each note would need to support more than one group.

Sharing is going to need to be implemented within the ownNote app vs. as individual files, since DB support will be added as a storage option.

**Comment by mckaygerhard** [comment]
umm in some way u have right! but of course only if we separate the things: tasggin are not sme as category!

u must consider that storage on db are not the way that oc uses for the files! in db only saves hases around the file paths!

**Comment by Fmstrat** [comment]
Since this is about the same thing as this: https://github.com/Fmstrat/ownnote/issues/10 I'm marking it as closed. Sharing is also covered in another ticket.
