### ISSUE TITLE
deleting a note does not work

### ISSUE THREAD

**Issue by tessus** [Fmstrat/ownnote#264]
oc 8.2.1
OwnNote 1.0.5

When I delete a note from my file system, the sync process shows it as deleted (and it's gone from my file system). But it actually isn't deleted on the server. So after a while it shows up on my client again.
This only happens with files in the Notes folder, so it must have to do with the ownNote app.

Update: This also happens, when you rename a file locally. Then you have 2 notes which are the same, but one with the old and the other with the new name.

**Comment by tessus** [comment]
@Fmstrat any update on this?

**Comment by tessus** [comment]
@Fmstrat any update? it's basically not possible to delete or rename notes via the file sytem, because your app re-creates them.

**Comment by aviret** [comment]
The database is the master of the Notes, if you delete a note from the file system, it's restored from the database (it's done in the function getListing of the file :  https://github.com/Fmstrat/ownnote/blob/master/lib/backend.php).
The idea is that we have to consider that the deleted notes from the file system must be marked as delete in the database (column deleted must be different from 0).
