### ISSUE TITLE
is this app dead?

### ISSUE THREAD

**Issue by tessus** [Fmstrat/ownnote#265]
Is this app still in development? Does anybody work on resolving the bugs?
I haven't seen a commit for 6 months and the list of bugs is getting longer and longer....

**Comment by Fmstrat** [comment]
Nope, not dead. Just the only contributer is myself, and I'm busy on my company job a lot these days. Always open to other contributors, but no one has jumped on the ship yet. I plan on tackling a number of the issues after the holidays.

**Comment by tessus** [comment]
thx for the info and great to hear it. I really like the app.
