### ISSUE TITLE
Server: Option for auto save on specific time interval

### ISSUE THREAD

**Issue by ajira86** [Fmstrat/ownnote#27]
It will be great to save automatically the note each time defined by user

**Comment by mckaygerhard** [comment]
this implits a cron job and the cron system in oc has many issues yet! specially with the search lucene (the future replacement of normal search)

**Comment by ajira86** [comment]
couln't we simply have a sleep while in javascript only when file is opne ? somehting like using the setInterval method I mean ?

**Comment by mckaygerhard** [comment]
umm u talk about delegate this to the browser.. and this are less funtional for my large network of users.. , in my case, i not do that!, in office employes need to work focused on the task if any opther will cause extra loading on the os and the browser.. will pain in performance.. i'll not pay for new hardwaere if my hardware works as expected.

**Comment by Fmstrat** [comment]
I will add this as an enhancement. The JS overhead for this would be extremely minimal.

**Comment by GLock-PPC** [comment]
Would be nice to have autosave everytime a note is updated also on the android version

**Comment by Fmstrat** [comment]
Autosave on android will be covered in a separate ticket.

**Comment by Fmstrat** [comment]
Complete. Auto-saves on 60 seconds of idle if the content of the note has changed.

See: https://github.com/Fmstrat/ownnote/commit/80ae82274de4f1032dae38757928d87b96f8e649

Will be included in next release.
