### ISSUE TITLE
Support there?

### ISSUE THREAD

**Issue by KuenzelIT** [Fmstrat/ownnote#276]
Hi,

I really like the idea of this owncloud extension and also the android app. I would just like to know if this is going to be supported and developed in the future?

Thank you!

**Comment by enoch85** [comment]
Me too!

**Comment by steve-s-71** [comment]
+1

**Comment by aproposnix** [comment]
+1

**Comment by mikebabb** [comment]
Would love to know this too! I'd switch from Evernote if ownNote is in active development.

**Comment by enoch85** [comment]
Guys, latest commit was just a few days ago: https://github.com/Fmstrat/ownnote/commit/6ddcacf84967d972d65d6198dcd8f7c99bfc5924 So I would say the development is there - but I also agree that more work should be put into this. cc @Fmstrat

**Comment by KuenzelIT** [comment]
I asked this quite a while ago. In any case thanks for your work, it's just important to know if it has a future, since switchting is quite some work every time.

**Comment by Fmstrat** [comment]
It's in semi-active development. Always open to collaborators forking off, too. Releasing a bug-fix soon.
