### ISSUE TITLE
PHP7/OC 9.0beta1: undefined method OC_L10N

### ISSUE THREAD

**Issue by tflidd** [Fmstrat/ownnote#278]
I'm running some tests with debian 8, apache, php 7.0.3 (from dotdeb) and owncloud 9.0 (nightly, currently: `$OC_Build = '2016-02-17T04:42:01+00:00 c6b24573066cfc87b73b1b61b41032b8c5a406cf;'`
Owncloud works fine, no errors, until I activate ownnote 1.0.5 from the app-store, then I only get a white screen and this error:
````
{"reqId":"gbrxkGZpkJKW68xhn3Hb","remoteAddr":"myip","app":"PHP","message":"Error: Call to undefined method OC_L10N::get() at \/var\/www\/owncloud\/apps\/ownnote\/appinfo\/app.php#34","level":3,"time":"2016-02-20T22:15:14+00:00","method":"GET","url":"\/owncloud\/"}
````

**Comment by timscha** [comment]
I can confirm this issue with OC 9 final. Looks like the app will no longer work with OwnCloud,

**Comment by enoch85** [comment]
This is on stable as well. @Fmstrat PLEASE FIX.

Workaround: `//    'name' => \OC_L10N::get('ownnote')->t('Notes')`

**Comment by Fmstrat** [comment]
Will merge once I do regression tests against old versions. On vacation this weekend so I plan to use some time over the next couple of days to get showstoppers like this fixed for 9.x. Thanks everyone, especially @tflidd for providing the fix.
