### ISSUE TITLE
Save and continue edit

### ISSUE THREAD

**Issue by ajira86** [Fmstrat/ownnote#28]
Each time you save, you close the document, not really nice if you want to regulary save your work

**Comment by Fmstrat** [comment]
Good point. I'm thinking the auto-save I build will save after a certain idle count, but I will likely create a save button separate from close, and perhaps a Cntrl-S shortcut.

**Comment by ajira86** [comment]
Yes it will be great and easier to start with an additional button :)

**Comment by Fmstrat** [comment]
Added in https://github.com/Fmstrat/ownnote/commit/5405c0ab5ea0d17809b293f44de6c06e2091c019
