### ISSUE TITLE
Error: this app cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by jschfr** [Fmstrat/ownnote#282]
I get this error message when I try to enable ownnote 1.05 after update to owncloud 9. With oc 8.2 it worked fine.

**Comment by tflidd** [comment]
You need to download it manually (from github or apps.owncloud.com), unpack it to your `apps/`-folder and apply this patch: https://github.com/Fmstrat/ownnote/pull/279/files

**Comment by tflidd** [comment]
Or wait until the owner has merged the fix and published a new version.

duplicate of https://github.com/Fmstrat/ownnote/issues/278
