### ISSUE TITLE
Fix version in XML

### ISSUE THREAD

**Issue by enoch85** [Fmstrat/ownnote#283]
@Fmstrat You might want to fix this: `App can't be installed because the version in info.xml/version is not the same as the version reported from the app store`

![deepinscreenshot20160310220024](https://cloud.githubusercontent.com/assets/4511254/13684369/adb60ee0-e70b-11e5-88ed-b4f6c7c35a2d.png)

**Comment by Fmstrat** [comment]
Updated zips again, should work now.

**Comment by enoch85** [comment]
Yes, issue solved. Thanks for your quick response! And please - it would be super cool if you could start working on this app again, there are a lot of unsolved issues. Thanks again.
