### ISSUE TITLE
Android App not able to login after upgrade to OC 9

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#286]
After the Update to OC 9 the android app is throwing "401 {"mesage":"CORS requires basic auth"}

Latest Android App.
Apache to 2.4.17
PHP to 5.5.29
MySQL to 5.6.25

any sollution for that issue?
on oc 8.2.2 everything was working well.

**Comment by Fmstrat** [comment]
Fixed in 1.07.

**Comment by fbartels** [comment]
Hi Fmstrat,

while removal of cors works around the issue, this makes the app vulnerable to CSRF attacks according to https://github.com/owncloud/news/issues/936#issuecomment-195716374 .

I will see if I can raise an according issue at owncloud core.
