### ISSUE TITLE
database & folder

### ISSUE THREAD

**Issue by tony5** [Fmstrat/ownnote#287]
it seems with OC 9.0 and  OwnNote 1.07 that you can not select database & folder in the admin page.
no errors in the logs.

even "Disable announcements" can't be set.

**Comment by treuss** [comment]
Same behaviour here, too.

**Comment by mikebabb** [comment]
There are no errors in ownCloud's log, but when trying to change from database to database + folder and entering a folder name in ownCloud settings, after a second or so a JavaScript error is logged by the browser (405 Method not allowed). The named folder is never created, and the user's database/database+folder selection is not saved.

**Comment by Danie10** [comment]
I'm a new users and had the same problem.  Without this my Mac client is not able to connect and sync notes it seems.

**Comment by shieldsit** [comment]
I have the same issue.  I'm try to use this editor for PC: https://github.com/ThomasDaheim/ownNoteEditor  I think it needs my notes in a folder to work.

**Comment by ThomasDaheim** [comment]
@shieldsit: Correct, the PC editor works on the files in the ownCloud directory. I have never tried to make it work with the database, since I wanted to avoid the corresponding hit to the response time :-)

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/ownnote/commit/1f0a01710326b15316d496397877038ba32ed417
