### ISSUE TITLE
Cannot change Database (only) to include Folder

### ISSUE THREAD

**Issue by lister171254** [Fmstrat/ownnote#295]
Running 8.2.3 production of owncloud, with OwnNote 1.07.

While I see the option of "Database and folder" in the drop down for storage, can select this option and enter the folder name, the change does not get saved (should there be a save button)

Also, does the folder have to exists?

Great app and thanks

**Comment by Phill93** [comment]
Me too

**Comment by daboss84** [comment]
Same here, Owncloud 8.2.2 and OwnNote 1.07

In Firefox, the console outputs: Error 405 - Method Not Allowed for https://<domain>/index.php/apps/ownnote/api/v0.2/ajaxsetval

The POST-Body is: field=folder&value=Notes

![headers](https://cloud.githubusercontent.com/assets/18015530/13967118/dbb9f0d6-f075-11e5-8ea1-32a5af13d8eb.png)
![post](https://cloud.githubusercontent.com/assets/18015530/13967124/dfa15162-f075-11e5-89be-5013197e37ec.png)

**Comment by mrfind** [comment]
Same here, Owncloud 9.0.0 and OwnNote 1.07.

Thanks for the App!!

**Comment by Fmstrat** [comment]
Related to Oc9 core changes and a fix that went in place for new API. Will fix this as I update that. Sorry folks.

**Comment by jazi4** [comment]
OC v9.0.0 and ownNote v1.07
Thanks for creating ownNote.
While waiting for your Fix , tried to force 'Database and Folders' as default by changing
apps/ownnote/admin.php 
replacing
$tmpl->assign('folder', OCP\Config::getAppValue('ownnote', 'folder', ''));
with
$tmpl->assign('folder', OCP\Config::getAppValue('ownnote', 'folder', 'Notes'));
But still no files Appearing in 'Notes' Folder which was manually added to
/apps/files/
Is there something else that should be changed because of this Edit?
Will your update be coming soon?
Also , any progress with iOS version?

**Comment by psychedup** [comment]
@jazi4 I was able to force it to use a folder by manually setting it in mysql:

`insert` into oc_appconfig ( appid, configkey, configvalue ) values ( 'ownnote', 'folder', 'ownnote' );

Of course this only works if you're using mysql.

**Comment by mikebabb** [comment]
@psychedup Thanks very much for your workaround! I wasn't able to get it to work running it as a command for some reason, but manually inserting a row in to oc_appconfig using the parameters you specified has updated the database & folder setting in ownNote and enabled me to complete my migration from Evernote. Cheers!

**Comment by fabiendelmas** [comment]
@psychedup Thanks, works fine !

**Comment by fabiendelmas** [comment]
@mikebabb i migrated also from evernote, works fine, but the Android Apps is crashing when loading the notes after 175, did you face the same issue ? how many notes do you have ?

**Comment by mikebabb** [comment]
@fabiendelmas I don't have that many notes, closer to 60 or so, but I've noticed that the Android app is a little unstable at times and prone to hanging and crashing when opening large notes.

**Comment by fabiendelmas** [comment]
@mikebabb Thanks for your feedback, 
then i opened a new issue #298

**Comment by cdamken** [comment]
ownCloud 8.2.2 
ownNote 1.07

I did this:

> While waiting for your Fix , tried to force 'Database and Folders' as default by changing
> apps/ownnote/admin.php
> replacing
> $tmpl->assign('folder', OCP\Config::getAppValue('ownnote', 'folder', ''));
> with
> $tmpl->assign('folder', OCP\Config::getAppValue('ownnote', 'folder', 'Notes'));
> But still no files Appearing in 'Notes' Folder which was manually added to

And this: (Changing the ownnote to Notes in the config value)

> @jazi4 I was able to force it to use a folder by manually setting it in mysql:
> 
> insert into oc_appconfig ( appid, configkey, configvalue ) values ( 'ownnote', 'folder', 'ownnote' );
> 
> Of course this only works if you're using mysql.

In the Android app are the notes displayed now, but in the WebUI I just get all empty notes. even if they are show on the left column

![ownnotes1](https://cloud.githubusercontent.com/assets/7264495/14488931/e5bff76e-016a-11e6-9a23-ec0414f492eb.png)

In my Notes folder they are all the notes with the information.

Then I remember I have Redis and I have to clear the cache is clear and restart the Apache server too
(Weird that the Androind worked without problems before I did that)

Now all the Notes are there. the workaround work so far.

Thanks for the workaround information and also @Fmstrat  great app

**Comment by cdamken** [comment]
Now I notice that the problem was not to restart the server. I have some parameters in the oC that does now work with this app:
```
 'asset-pipeline.enabled' => true,
 'assetdirectory' => '/var/www/html/owncloud',
```

**Comment by blvb** [comment]
Is there a problem with finishing up this app and fixing this?

**Comment by wayneward** [comment]
i was thinking the same :(
been sat waiting for the fix ...

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/ownnote/commit/1f0a01710326b15316d496397877038ba32ed417

**Comment by ejouvin** [comment]
In Owncloud, applications can be deployed anywhere else than sub folder "apps", if this is configured.
For example :
```
  /**
   * Use the ``apps_paths`` parameter to set the location of the Apps directory,
   * which should be scanned for available apps, and where user-specific apps
   * should be installed from the Apps store. The ``path`` defines the absolute
   * file system path to the app folder. The key ``url`` defines the HTTP web path
   * to that folder, starting from the ownCloud web root. The key ``writable``
   * indicates if a web server can write files to that folder.
   */
  'apps_paths' => array(
    array(
      'path'=> '/var/opt/owncloud/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    array(
      'path'=> '/var/opt/owncloud/owncloud/exapps',
      'url' => '/exapps',
      'writable' => true,
    )
  ),

```

Then the built link is something like : http://SERVEUR/owncloud/exindex.php/apps/ownnote/ajax/v0.2/ajaxsetval
instead of the expected one http://SERVEUR/owncloud/index.php/apps/ownnote/ajax/v0.2/ajaxsetval

Change the way to build the link as done in the pull request #312

**Comment by swdrumm** [comment]
+1 on this issue.  Any ETA on the official fix to saving notes in the database and a folder?  Thanks!
