### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by hannesa2** [Fmstrat/ownnote#3]
I like your app with the idea of text formatting !
A great enhancement would be a 
* category 
* sharing 
* a left overview list like in https://github.com/owncloud/notes
* REST Api

When there is an API, I think about to write a optional password protected Android App

**Comment by Fmstrat** [comment]
- category: For category, there is already a "group" function. 
- sharing: This will be on the short list, as I should be able to use ownCloud's built in sharing system
- left overview: I *might* implement this. The standard with other apps like contacts/calendar is a static list, so I'll need to evaluate it a bit more.
- REST: Again, this will be a *might* feature, and would either come as part of, or after, the mobile apps

**Comment by Fmstrat** [comment]
Sharing is listed in other entries, as well as left hand lists. Closing this out since the Android app is out.
