### ISSUE TITLE
Support for Nextcloud

### ISSUE THREAD

**Issue by enoch85** [Fmstrat/ownnote#324]
I'm thinking of moving to Nextcloud and I want to be sure that this app supports it before I do. 

Is this supported, or will it be in the future?

**Comment by ThomasDaheim** [comment]
Didn't have any issues after migrate and seems to work. But I do most of my editing with https://github.com/ThomasDaheim/ownNoteEditor these days ;-)

**Comment by enoch85** [comment]
@ThomasDaheim Great news, will try. Btw, you should publish that App somewhere. :)

**Comment by enoch85** [comment]
Just tested moving my whole ownCloud instance to a new testing domain to be sure everything works before I run it in production, and it seems like it fails. This is what's happening when trying to login on Nextcloud:

```

Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68	2016-10-26T00:25:47+02:00	daniel@en0ch.se
Error	PHP	Missing argument 1 for OCP\AppFramework\App::__construct(), called in /var/www/nextcloud/ocs/routes.php on line 104 and defined at /var/www/nextcloud/lib/public/AppFramework/App.php#67	2016-10-26T00:25:47+02:00	daniel@en0ch.se
Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68	2016-10-26T00:25:47+02:00	daniel@en0ch.se
Error	PHP	Missing argument 1 for OCP\AppFramework\App::__construct(), called in /var/www/nextcloud/lib/private/Route/Router.php on line 369 and defined at /var/www/nextcloud/lib/public/AppFramework/App.php#67	2016-10-26T00:25:47+02:00	daniel@en0ch.se
Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68	2016-10-26T00:25:47+02:00	daniel@en0ch.se
Error	PHP	Missing argument 1 for OCP\AppFramework\App::__construct(), called in /var/www/nextcloud/lib/private/Route/Router.php on line 369 and defined at /var/www/nextcloud/lib/public/AppFramework/App.php#67	2016-10-26T00:25:50+02:00	daniel@en0ch.se
Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68	2016-10-26T00:25:50+02:00	daniel@en0ch.se
Error	PHP	Missing argument 1 for OCP\AppFramework\App::__construct(), called in /var/www/nextcloud/ocs/routes.php on line 104 and defined at /var/www/nextcloud/lib/public/AppFramework/App.php#67	2016-10-26T00:25:50+02:00	daniel@en0ch.se
Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68	2016-10-26T00:25:50+02:00	daniel@en0ch.se
Error	PHP	Missing argument 1 for OCP\AppFramework\App::__construct(), called in /var/www/nextcloud/lib/private/Route/Router.php on line 369 and defined at /var/www/nextcloud/lib/public/AppFramework/App.php#67	2016-10-26T00:25:50+02:00	daniel@en0ch.se
Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68	2016-10-26T00:25:49+02:00	daniel@en0ch.se
Error	PHP	Missing argument 1 for OCP\AppFramework\App::__construct(), called in /var/www/nextcloud/ocs/routes.php on line 104 and defined at /var/www/nextcloud/lib/public/AppFramework/App.php#67	2016-10-26T00:25:49+02:00	daniel@en0ch.se
Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68	2016-10-26T00:25:49+02:00	daniel@en0ch.se
Error	PHP	Missing argument 1 for OCP\AppFramework\App::__construct(), called in /var/www/nextcloud/lib/private/Route/Router.php on line 369 and defined at /var/www/nextcloud/lib/public/AppFramework/App.php#67	2016-10-26T00:25:49+02:00	daniel@en0ch.se
Error	PHP	Undefined variable: appName at /var/www/nextcloud/lib/public/AppFramework/App.php#68
```

@Fmstrat Could you please fix this? Many people are using Nextcloud now, and I think it would be a good idea to fix this if you want to make more money from the app.

**Comment by enoch85** [comment]
Btw, it works in the Nextcloud GUI, but the mobile app fails.

**Comment by Tamsy** [comment]
ownnote used to work well with Nextcloud up to version 10.0.2.

Today we updated our servers to Nextcloud 11.0.0 but the ownnote app can not be activated anymore:

_"Server version 10 or lower is required."_

What a pity! Especially since we have paid for _ownNote - Notes for ownCloud_ from the PlayStore.

I'm afraid ownnote might be a zombie project by now since the latest commit dbadf53 happened on 11 May 2016 ...

**Comment by enoch85** [comment]
@Tamsy There is a hacky workaround. Change info.xml to maxversion 12 and it will work.

**Comment by Tamsy** [comment]
@enoch85 

Just did it and it works now. Thank you for the hint.
I was afraid the file integrity check for this app will fail if I tamper with the code. But it doesn't. Works as expected again now (also the Android client).

**Comment by enoch85** [comment]
@Tamsy Glad I could help. :)

**Comment by Fmstrat** [comment]
Thanks for jumping in @enoch85. As mentioned in the other issue I'll get that merged in once I get Nextcloud set up.

**Comment by enoch85** [comment]
Thank *you* @Fmstrat for showing that you are alive. ;) This app would really need some love. It has great potential.

Besides that maybe you should consider letting someone in on this as you don't even have time to (obviously) merge simple PRs. And what I mean by "letting in" is giving someone you trust merge permissions.

**Comment by Fmstrat** [comment]
@enoch85 - Totally open to that. I've even asked for contributors in the past but no-one wanted to help take on the work. If you (or anyone else with a similar background working with ownCloud/NextCloud already) would like to step in and help, I'm very, very open to granting access to this repo.

**Comment by enoch85** [comment]
@Fmstrat I don't know PHP that well, but I know enough to see if the code are good or not. What I can offer are to merge simple PRs like translations and typos and stuff. I won't merge things I don't understand or haven't tested. 

So let me in and I'll help you. :) This doesn't mean in any way that you should relax about this app, there are still 143 issues to be solved as we speak. IMHO.

**Comment by enoch85** [comment]
@Fmstrat Check my contact information here: https://www.techandme.se/contact/ Please send me an email so that I can reach you.

Thanks!

**Comment by julienval** [comment]
Thanks @enoch85 for the workaround. Altering info.xml allowed me to activate Ownnote again on my NextCloud 11 setup.
However, the Android app cannot synchronise. I get the following error when updating:
`Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 240 path  $.ocs.data`

Any hint on how to fix this issue?

Cheers,
Julien

**Comment by enoch85** [comment]
ping @Fmstrat

**Comment by Tamsy** [comment]
Well, it only works sort of. When trying to edit a note through the web interface of NC 11 and upload pictures to that note, nothing gets saved...

**Comment by enoch85** [comment]
@Tamsy Hmm... Is it saved locally if you do it from your phone?

**Comment by julienval** [comment]
Just noticed that I cannot edit my notes (the editor screen is blank, I just see the "save" / "cancel" ... commands in the upper part of the screen)

Julien

**Comment by Tamsy** [comment]
Nope, it doesn't work. I just tried to edit one of my notes through my phone (SGS7, Android 6.01). It didn't saved but instead the note itself is gone (empty).

Seems that the ownnote app is broken with NC 11.

**Comment by Japhys** [comment]
> Just noticed that I cannot edit my notes (the editor screen is blank, I just see the "save" / "cancel" ... commands in the upper part of the screen)
Julien

Exact same problem here

**Comment by Japhys** [comment]
Any news on a possible update?

**Comment by q4z1** [comment]
check https://github.com/Fmstrat/ownnote/issues/333 for the blank editor screen issue (tinymce vs CSP) ;)

**Comment by q4z1** [comment]
@Tamsy pic upload with browser based web interface works for me now after implementing the CSP workaround. Pic upload with the ownNote app on Android 4.2.2 works for me too.

**Comment by Tamsy** [comment]
@q4z1 

Thank you for the hint.

I have patched #333 for the blank editor screen issue. While ownnote now works on Android 6.01 (creating and editing notes) the web interface through the web browser doesn't let me edit any notes (creating new notes works though). The whole ribbon/tool bar for editing notes is not visible anymore.

Server: Ubuntu 16.04
Webserver: Apache 2.4.25 with PHP 7.0.14
Certificate: Official Comodo PositiveSSL
Web browsers: Pale Moon 27.03 (x64) on Win 10 Pro 64 Bit and Microsoft Edge 38.14393.0.0

**Comment by q4z1** [comment]
@Tamsy 

I see ... Edge does not support CSP Level 2 (see https://content-security-policy.com/). You have to patch a nextcloud-core file then:(

* file **lib/public/AppFramework/Http/EmptyContentSecurityPolice.php** - line 354:

replace
`$policy = "default-src 'none';";`

with
`$policy = "default-src 'self';";`

... and - weird issue - you have to additionally patch tinymce.min.js again because the global var nextNonce is not known in tinymce in Edge.

line 2734 - just before the other patched line:

insert
`if (typeof nextNonce === 'undefined') nextNonce = "";`

... just tested it with Edge - it works for me now.

**Comment by enoch85** [comment]
Can someone make a PR for this workaround --^ or does @Fmstrat have a better idea?

**Comment by q4z1** [comment]
I can put the ownnote changes into my fork and create a pull request if needed. Just let me know.

But for Microsoft Edge I did not find a better solution than changing a nextcloud core file = not inside of this repo(!) - as it is in my eyes more a bug from nextcloud not setting CSP directive default-src to 'self' instead of 'none' for browsers which do not support CSP Level 2 with the nonce hash mechanism.

**Comment by Tamsy** [comment]
@enoch85 

Thank you for the follow-up.

Edge is not really the web browser of my choice but Pale Moon is. Unfortunately ownnote is not working correctly on both browsers.

To avoid failures with the file integrity checks with NC I refrain from patching the NC-core. I am very much hoping that the NC-devs will come up with a solution to the CSP Level 2 matter.

**Comment by q4z1** [comment]
@Tamsy 

I made some tests with Palemoon (Portable-27.0.3.win64).

Regarding https://content-security-policy.com/browser-test/ it supports CSP Level 2 - and the nonce hash mechanism works as expected for me with the https://github.com/Fmstrat/ownnote/issues/333 patch.

Also editing existing notes, adding pictures and removing them works as expected for me.
Editor Menu Bar always shows up in a proper way for me.

Can you maybe open Inspector and post console errors for the issues you have?

**Comment by Tamsy** [comment]
@q4z1 

Thank you again for your continuous support.

I just re-downloaded the file ./apps/ownnote/templates/main.php from GIT and patched that file again using the #333 patch.

There must have something gone wrong with the first patch. Now ownnote is working well again with Pale Moon 27.03 (x64): I can create, edit, upload notes as it should be.

Many thanks again!

**Comment by vve1505** [comment]
Where is this "info.xml" file to alter and make ownnote work? I can't seem to find it.

**Comment by enoch85** [comment]
@vve1505 https://github.com/Fmstrat/ownnote/blob/master/appinfo/info.xml

**Comment by vve1505** [comment]
@enoch85 - thanks for the reply. I'm not well versed in these things, so once I modify that file, where am I supposed to put it? I just upgraded to Nextcloud 11 yesterday and ownnote was one of my big "must have" apps. Guess I should have researched a little more. Thx.

**Comment by vve1505** [comment]
@enoch85 - thank you very much. I was running the "find" command in my apps directory, but it didn't find it for some reason. Know now!

**Comment by enoch85** [comment]
This has been forked and the work will continue in https://github.com/brantje/ownnote Please join!
