### ISSUE TITLE
Error after owncloud update

### ISSUE THREAD

**Issue by ruddyconsult** [Fmstrat/ownnote#331]
I did another owncloud update. Afterwards I was told Ownnote was disabled. So, I tried to install it again, but got the following Error Msg:
App directory already exists
and it apparently was not installed.

My db is still visible under Android, but the app there cannot connect any more to my server.

Please advise.

**Comment by napi-goethe** [comment]
Instead of reinstalling, have you tried just activating the app again (click on "deactivated apps" in apps overview)? Usually that worked for me, at least during previous upgrades.
