### ISSUE TITLE
ownnote broken on nextcloud 11

### ISSUE THREAD

**Issue by jiml8** [Fmstrat/ownnote#332]
NC11 refused to enable ownnote because max version for ownnote was too low.  I manually altered the xml file to change the max version.

Ownnote opens its window, and shows existing stored notes.  When clicking on a note, the contents of the note are not shown; the text entry window does not appear.  Similarly when creating a new note; the note is shown as being created but there is no text entry window.

When trying to access the server from the android client, an error message appears: "TypeError:  Cannot read property 'name' of undefined.

**Comment by jiml8** [comment]
I find that the android client will successfully create notes and store them on the server.

**Comment by aviret** [comment]
Could have a look at the issue #324 ? I think you will find the solution for your issue.

**Comment by enoch85** [comment]
Please close this issue
