### ISSUE TITLE
Ownnote Extention in Nextcloud

### ISSUE THREAD

**Issue by ibexmonj** [Fmstrat/ownnote#339]
I setup the experimental extension of Ownnote in my nextcloud instance.  Is there an easy way to import the evernote files for this extension ? 
I do not see a Notes folder in nextcloud. 

Let me know if this isn't the right place to ask.

**Comment by andyforceno** [comment]
Not sure if this will work with NextCloud, but: I use ownCloud, and I had to manually create the folder in my user's data folder at /var/www/owncloud/data/<user>/files/Notes. I then moved the notes in there, restarted php and my webserver (not sure if that part is necessary). After a couple minutes, the Notes folder appeared in my ownCloud. I had to do this even though I have "Database and folder" set in the ownNote settings, so it should have created the folder automatically.

**Comment by ibexmonj** [comment]
Thank you @andyforceno. I will check this out.

**Comment by enoch85** [comment]
This works now

**Comment by ibexmonj** [comment]
@enoch85 Its still not working for me ? 

I see the Notes folder was created in the data folder once I chose the "database and folder" option. I copied one of the notes exported from Evernote that is in a ".html" format. It is still not showing up in the Notes section in Nextcloud under Ownnote.

**Comment by andyforceno** [comment]
@ibexmonj Does the folder have correct ownership/permissions?

**Comment by enoch85** [comment]
Have a look here: https://github.com/brantje/ownnote

**Comment by ibexmonj** [comment]
@andyforceno i had to chown to the webserver user and now the html files are showing up. 
Any luck getting the png/jpeg images to show up after import ?  

I have a few png/jpeg images in evernote that I tried to import, they have the right permissions now but neither the folder nor the image files are showing up in the UI.

@enoch85 I will check the issues section out there. thanks !

**Comment by andyforceno** [comment]
@ibexmonj Most all of the images showed up for me. I can't figure out why the rest don't show up, the permissions are correct.

**Comment by ibexmonj** [comment]
@andyforceno do you have any .png's that are showing up ?

**Comment by andyforceno** [comment]
@ibexmonj Yes, from what I can tell, all of the .png files show up in the notes.
