### ISSUE TITLE
Standard test suite for ownnote?

### ISSUE THREAD

**Issue by ThomasDaheim** [Fmstrat/ownnote#342]
Hi @Fmstrat ,

I was wondering if there was a standard test suite for ownnote?

I have done a number of changes on my branch that I would like to test before sending out a pull request :-)

- nonce-fix from #335 
- upgraded to tinymce 4.3.13 (as a first step, goal is to go to current version 4.5.*)
- enabled tinymce buttons for foreground & backgroud colors (#340)
- enabled tinymce codesample plugin that uses prism.js to highlight codeblocks

- added an admin option "Folder only" with corresponding support in controllers and backend - owncloud/nextcloud have sufficient support for undelete etc. that database logic isn't need anymore

Works on my installation without issues but I'm sure there are a lot of variations that I don't come across in my standard usage scenarios...

Thanks,
Thomas

**Comment by Silentz0r** [comment]
@ThomasDaheim  There's anyway i can test your changes in my server? 

ownCloud = v9.1.5
QOwnNotes = v17.3.0
QOwnNotes = v17.05.0

Thanks.

**Comment by ThomasDaheim** [comment]
Hi @Silentz0r ,

I could create a pull request for my changes. You should be able to see & use that. So far I would like to avoid creating a fork of this repository... 

Question: You're using QOwnNotes (using markup)? How can this be combined with ownnote (using html)? 

Cheers,
Thomas

**Comment by mikshepard** [comment]
I'd love to see your changes as well and implement them on my server.  Could you post the pull request or a diff patch for us to use?

Nextcloud v12.0
Ownnotes v1.08

Thanks,

**Comment by ThomasDaheim** [comment]
Good to know that I'm not the only one left with ownnote :-)

Will create a pull request with some more details on what I have changed in the next days. With the changes to the version of tinyMCE too many files have changed for a diff patch.

**Comment by ThomasDaheim** [comment]
I have created pull request #346 

Have fun and please let me know any issues you run into
