### ISSUE TITLE
Broken after upgrade from NC11 to NC12

### ISSUE THREAD

**Issue by steve-s-71** [Fmstrat/ownnote#344]
I got this app working with NC11, but now after upgrade to NC12 it entirely disappeared.

After upgrade I have copied all app files from a backup into  /var/www/nextcloud/apps/ownnote
But the app does not show up in app menu  (neither in active apps, nor in inactive apps folder).

Anyone got it working under NC12 – and how?

**Comment by Bellum45** [comment]
You must edited the appinfo/info.xml file again.
Set the max-version from nextcloud to 12 and it's running again.

**Comment by steve-s-71** [comment]
I tried this:

<nextcloud min-version="11.0.0" max-version="12" />

but without success. Is it wrong?

**Comment by Bellum45** [comment]
I have the following:
`<nextcloud min-version="10" max-version="12" />`

**Comment by MichaIng** [comment]
Same worked for me.

**Comment by enoch85** [comment]
This is in the code now
