### ISSUE TITLE
Server: Importing HTML (from OneNote export)

### ISSUE THREAD

**Issue by aimlessadam** [Fmstrat/ownnote#35]
Hello.  I was thrilled to see the import from Evernote (HTML) option, including base64 URI image embedding, though I use OneNote.   Hopefully I am doing something wrong here, but i would really like to get my non-cloud (SMB sync'ed only) OneNote notebooks to my private Owncloud to get close to the Evernote experience.

So OneNote has an option to export to MHTML, and then IE (or Firefox with an addon) can then save that .MHT file as the normal "full HTML" w/ the associated image directory so i gave that a try - 

- creating a simple OneNote entry called "Test" with a few bullets and an image pasted into the file.
-  I did a Save As in OneNote to Test.MHT, and 
- then in FireFox (and IE, just to test) turned that into
  - "Test.html", 
  - a "Test_files" folder, and 
  - "image001.png" in that folder.  
- I uploaded to my "Notes" folder the .HTML file and the _files folder via my local sync folder, 
- made sure it was synced up and was there in the Files app. 
- Switched to the OwnNote app, 
- went back to the Files app, saw the HTML file renamed as HTM, and then 
- tried to view the note in the OwnNote app.  

The image was still ``img src="SimpleTest_files/image001.png`` and actually a broken link (apache reporting a 302 error targetting owncloud/index.php/apps/ownnote/Test_files/image001.png).  In the owncloud.log, either during the conversion to .HTM or the subsequent viewing of the note in the WebUI, i have two ''ownCloud[19408]: {PHP} DOMDocument::loadHTML(): Unexpected end tag : ul in Entity, line: 48 at /path/to/owncloud/apps/ownnote/lib/backend.php#22'' errors. 

I have v0.0.4 installed from apps.owncloud.com on Owncloud 7.0.4 under Centos 6.6 w/ the stock (but Centos-patched up to date) PHP 5.3.3. 

thank you!
adam

**Comment by Fmstrat** [comment]
I imagine this is a valid bug. Can you attach a ZIP of an export after you've converted to full HTML that I can est with?

**Comment by aimlessadam** [comment]
I'm sorry, i found how to upload images to comments but not zip files, so hopefully this link works: http://tinyurl.com/nkzvsm8
Thank you!

**Comment by Fmstrat** [comment]
OK, I will take a look at this in the next web update. I'm working through Android app bugs now.

**Comment by aimlessadam** [comment]
Thank you! 

On 2015-03-24 9:40 am, Fmstrat wrote: 

> OK, I will take a look at this in the next web update. I'm working through Android app bugs now. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/Fmstrat/ownnote/issues/35#issuecomment-85500404

**Comment by aimlessadam** [comment]
Just checking in because the share link expired by now; please holler if you need another (or want me to dump it somewhere specific).  thanks again!

**Comment by Fmstrat** [comment]
Ahh, crud, no I didn't save that locally. Can you repost?

**Comment by aimlessadam** [comment]
definitely.  http://tinyurl.com/odjwaqq

thank you!

**Comment by Fmstrat** [comment]
OK, got it and saved locally. Thanks.

**Comment by Fmstrat** [comment]
While fixing this, I've identified an error in file_get_contents in the core OC code. I've identified it for developers here. https://github.com/owncloud/core/issues/16202

I'll have to find a work-around until they get that sorted out.

**Comment by Fmstrat** [comment]
A workaround is in place, but an error is still placed in the log until the ownCloud developers fix the above.
