### ISSUE TITLE
Error by using Mode : "Database and Folder"

### ISSUE THREAD

**Issue by BFMVFreddy** [Fmstrat/ownnote#351]
I get an Error by using the obove named mode...

> Error: Using $this when not in object context
> /var/www/html/nextcloud/apps/ownnote/lib/backend.php - line 182: OC\Files\Storage\Local opendir('notes')
> /var/www/html/nextcloud/apps/ownnote/controller/ownnoteajaxcontroller.php - line 44: OCA\OwnNote\Lib\Backend->getListing('notes', false)
> [internal function] OCA\OwnNote\Controller\OwnnoteAjaxController->ajaxindex()
> /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
> /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\OwnNote\Controller\OwnnoteAjaxController), 'ajaxindex')
> /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\OwnNote\Controller\OwnnoteAjaxController), 'ajaxindex')
> /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OwnnoteAjaxCont...', 'ajaxindex', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
> [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
> /var/www/html/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
> /var/www/html/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/apps/ownnote/a...')
> /var/www/html/nextcloud/index.php - line 37: OC handleRequest()
> {main}
> Error	PHP	Non-static method OC\Files\Storage\Local::opendir() should not be called statically at /var/www/html/nextcloud/apps/ownnote/lib/backend.php#182

Im using Nextcloud 13...

Best Regards

**Comment by thomas2403** [comment]
I didn't want to create a pull request for a one-line change but this can be fixed by changing line 182 of `lib/backend.php` from
```if ($listing = \OC\Files\Storage\Local::opendir($FOLDER)) {```
to
```
$folderview = new \OC\Files\Storage\Local(array("datadir" => $FOLDER));
if ($listing = $folderview->opendir('.')) {
```

**Comment by BFMVFreddy** [comment]
Thsi works. 
Thanks alot! :)
