### ISSUE TITLE
Note Group Sidebar Display Bug in NC 13

### ISSUE THREAD

**Issue by mikshepard** [Fmstrat/ownnote#352]
In NextCloud 13 with the git version of ownnote (including the latest commit for NC 13) the groups sidebar is not displaying properly.  Every group is in an edit mode and clicking the checkmark does nothing to change this.  You can still select the groups to see the notes assigned to it, but deleting/editing the group itself will not work.  I also tried on a fresh install/server with the same results.

![image](https://user-images.githubusercontent.com/3514599/36273028-cf510b26-1248-11e8-94fa-3109c8e329ba.png)

(See image for example)

This is on a Debian Jessie build, with mysql 5.7 and php 7.1 (also tried with php 5.6).  Please let me know if you need more info.  Nextcloud loglevel 0 does not display any errors with ownnote.  Issue started with upgrade to NC 13 and latest git commit.

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/ownnote/commit/8a98485c4d0c45ac20c86ef4fbf69d5ee3068f69

Please do a `git pull` and things should start working again.

**Comment by mikshepard** [comment]
Working great, thank you!
