### ISSUE TITLE
0.0.5 unable to activate app in oc8 because of no appearing

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#37]
i've uploadet the ownnote folder to apps on oc 8.0.2 and the the app did not appear in apps->notactivated. no error in logfile.

**Comment by Fmstrat** [comment]
Have you checked permissions on the folder and did you have a previously working version?

**Comment by apg1980** [comment]
yepp i went back to recent version and it works. 5 did nit appear

**Comment by apg1980** [comment]
i figured it out. in your master was in appinfo the version file missing.
i've created it with the version info and the app appears.
thanks a lot for your hard work.

**Comment by Fmstrat** [comment]
Interesting, I will add a version file to be safe.

**Comment by Fmstrat** [comment]
Added to master.
