### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#40]
Thanks a lot for your great work.
Today i purchased your app on google play store.
I entered my credentials but the app is never logging on.
On my oc8.2 server i've already installed the latest ownnote app 0.0.5 but the app is never logging on (always the point animation on top).
Btw. i am using user_ldap for user authentication with my activedirectory.
Any suggestions?

**Comment by seal20** [comment]
I cannot even reach the credentials screen. I have a blank screen with a top blue banner written "Notes" and a broken link icon.

My android phone is old: android 2.3 and so perhaps it is not supported, which I would completely understand, but better to mark the app as incompatible in that case.

Setup:
Android 2.3
Owncloud 8.0.2
ownNotes 0.05
Apps installed 2015/03/24
user authentication: owncloud default.

@apg1980 what is your android version perhaps it can helps to troubleshoot.

**Comment by apg1980** [comment]
android 4.4.2

**Comment by delumerlino** [comment]
Hi,
thanks a lot for your great work!
I have bought the Android app, I am able to connect to my OC 8.0.2 server.
I have tried to create a note from the Android (lollipop 5.0), it asks for a name and it generates under the specified group, but after creating it deletes it.
Reverse process (generate a note on the server and syncronized) works.
So, in less words, I am able to edit and save the existing note from Android, but not to generate a new one,

Thank you

Andrea

**Comment by marco9876** [comment]
I'd Love to buy the App but i dont want Google Play. So shut up and take my Money :dancers: 
:) could u sell it any other way, like Threema it does for example?

**Comment by Fmstrat** [comment]
OK, lots of issues here, thanks for responding here so I can get these fixed vs. in Play Store comments! I'm going to try to split this up so I can implement fixes seperately.

@apg1980 
Please see: https://github.com/Fmstrat/ownnote/issues/45

@seal20 
Please see: https://github.com/Fmstrat/ownnote/issues/46

@delumerlino
Please see: https://github.com/Fmstrat/ownnote/issues/47

@marco9876 
Eventually it will be available in Fdroid.
