### ISSUE TITLE
Left panel (Group) but right panel is Blank on ownnote 0.0.5

### ISSUE THREAD

**Issue by osmose99** [Fmstrat/ownnote#44]
I can't get the editor to appear. Android apps works like a charm but unable to edit any notes in owncloud. Version 0.0.4 was working correctly. Thanks
![2015-03-24 08_47_18-notes - owncloud](https://cloud.githubusercontent.com/assets/8710776/6801959/8f193e22-d202-11e4-99fc-61d47684623a.png)

**Comment by Fmstrat** [comment]
Hmm. Is there an apps/ownnote/appinfo/version file?

Can you pull up the JS console and let me know if it is reporting an error?

**Comment by osmose99** [comment]
There was no version file but, unfortunately, adding it doesn't make the trick. 

For the JS Console from chromium:

example.com/:262 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-iine' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

script.js?v=712bcb927fca0ff8008e53398d3eca29:425 Uncaught ReferenceError: disableAnnouncement is not defined
/core/vendor/jquery/dist/jquery-migrate.min.map:1 GET https://example.com/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)

**Comment by osmose99** [comment]
I found the solution. I made an error when I add the line :
'custom_csp_policy' => "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *", to the config.php. 
I corrected it and now everything works. 

Thanks a lot for the help and your wonderful apps.
