### ISSUE TITLE
Android: Login shows animation but never logs in

### ISSUE THREAD

**Issue by Fmstrat** [Fmstrat/ownnote#45]
Referenced from:
https://github.com/Fmstrat/ownnote/issues/40

@apg1980
> Thanks a lot for your great work.
> Today i purchased your app on google play store.
> I entered my credentials but the app is never logging on.
> On my oc8.2 server i've already installed the latest ownnote app 0.0.5 but the app is never logging on (always the point animation on top).
> Btw. i am using user_ldap for user authentication with my activedirectory.
> Any suggestions?

> Android 4.4.2

**Comment by Fmstrat** [comment]
What version of ownNote are you running on the server? Are you running a valid or self-signed certificate? And lastly, what device are you using?

**Comment by Fmstrat** [comment]
Another thought, try clearing data on the android app in settings. See if that fixes things.

**Comment by apg1980** [comment]
already did. it was by the way a fresh Installation so no data and Cache exists.

**Comment by Fmstrat** [comment]
OK, there is a likely an error occurring during the initial communication to the server on the notes listing since nothing is displayed. Do you have the ability to do a logcat? If so, I'm going to release a new version soon to fix a bunch of Android 2.3 issues. I can create a setting in their for debugging which will print a ton of information to the logcat. This would certainly help me narrow this down.

**Comment by GLock-PPC** [comment]
I have a similar problem, the app syncs only after the first installation or after purging the data and cache and re-entering the login details after a force close, in all other conditions it shows as loading and never updating / downloading new notes.

**Comment by Fmstrat** [comment]
Hmm, I wonder if there is a local storage issue in the App. I will investigate further.

**Comment by Fmstrat** [comment]
Hi all,

Please watch the Play Store for the release of version 0.0.7. This will not fix your issues, but it has additional debug code that should bail-out and put a message up on screen indicating the error that you're having. If the above bug continues without an error message, then it is most likely a communication issue between the client and server, instead of a stand-alone app issue. If this is the case, I'll need to move on to checking other things.

Please let me know how things turn out, and what error(s) you receive in the outputs from 0.0.7. Thanks.

**Comment by apg1980** [comment]
Ok, i've installed the 0.0.7 android app and got the following error:

An application error has occured.
QuotaExeededError: An attempt was made to add something to storage that exeeded the quota.

I have no quota on my oc storage configure (unlimited for my user).

**Comment by Fmstrat** [comment]
Wow, never would have expected that as an error. At least now I know it's an issue communicating with the server. Do you have ownNote setup to use Database and a Folder?

**Comment by apg1980** [comment]
yay the default setting.
Db and files with Folder Notes

**Comment by Fmstrat** [comment]
Annnndd I may be wrong, it's a quota issue on the device potentially since I use localStorage: http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st#23453866

Do you have any type of security settings on your phone that disables cookies or forces private browsing mode? Are you running a ROM with any Privacy Guards enabled? Thanks again.

**Comment by Fmstrat** [comment]
It could also be a note size issue. I think I'm going to ditch local storage and use sdcard storage. That means this won't be an issue for any device in the future. I'll keep you posted.

**Comment by apg1980** [comment]
i am using stock rom. no other Browser or settings

**Comment by Fmstrat** [comment]
Great, thanks. I'm ditching localStorage, it's too flaky. I'll post here as soon as I revert to something else.

**Comment by Fmstrat** [comment]
Hopefully this is resolved with the migration away from localStorage. If not, please re-open this issue after trying 0.0.8 once it hits the Play Store.
