### ISSUE TITLE
Android: Blank screen on start

### ISSUE THREAD

**Issue by Fmstrat** [Fmstrat/ownnote#46]
Reference issue https://github.com/Fmstrat/ownnote/issues/40

@seal20
> I cannot even reach the credentials screen. I have a blank screen with a top blue banner written "Notes" and a broken link icon.
> 
> My android phone is old: android 2.3 and so perhaps it is not supported, which I would completely understand, but better to mark the app as incompatible in that case.
> 
> Setup:
> Android 2.3
> Owncloud 8.0.2
> ownNotes 0.05
> Apps installed 2015/03/24
> user authentication: owncloud default.

**Comment by Fmstrat** [comment]
I will look into the 2.3 issue and see if I can fix in an emulator. Unfortunately I don't have a 2.3 device so it might take some trial and error if you're willing to stick with me on it.

**Comment by Fmstrat** [comment]
Figured this out. Happened to figure out the font size too. I'm not debugging a few other issues in 2.3 then I'll release a new version.

**Comment by seal20** [comment]
Sounds great! Looking forward the new release. I really appreciate the
effort you put in debugging for 2.3
I will translate your app in French and in japanese it should be quite fast
as there are only few strings. I didn't have the time yet to look at the
code so I will come back later. But even if po files are ok it will be
easier if it was on transifex like the rest of owncloud.
Talk later

**Comment by Fmstrat** [comment]
Lots of 2.3 fixes in 0.0.5 just published to the App store. Once it's available in your area, give it a shot. If it doesn't help, please re-open this issue. I'm going to open a couple of remaining 2.3 issues that shouldn't impact overall usage, though, and you're welcome to follow those or see if they happen for you.

**Comment by seal20** [comment]
Thanks for the effort but now I cannot pass the login screen.

However do not spend too much time on compatibility with 2.3, your userbase should not contain much 2.3 users...

**Comment by Fmstrat** [comment]
Give it another shot with 0.0.8 that should be in the Play Store soon. It's running fine on my Nexus One.

**Comment by seal20** [comment]
Thanks working great now!
