### ISSUE TITLE
Android: Sometimes notes are deleted after creation

### ISSUE THREAD

**Issue by Fmstrat** [Fmstrat/ownnote#47]
Referencing issue: https://github.com/Fmstrat/ownnote/issues/40#issuecomment-85376105

@delumerlino
> Hi,
> thanks a lot for your great work!
> I have bought the Android app, I am able to connect to my OC 8.0.2 server.
> I have tried to create a note from the Android (lollipop 5.0), it asks for a name and it generates under > the specified group, but after creating it deletes it.
> Reverse process (generate a note on the server and syncronized) works.
> So, in less words, I am able to edit and save the existing note from Android, but not to generate a new one,
> 
> Thank you
> 
> Andrea

**Comment by Fmstrat** [comment]
Are your dates/times the same between your device and the server? I'm thinking perhaps the server's time is ahead, and it's making the device thing the file was deleted.

**Comment by delumerlino** [comment]
Yes, they are "quite" the same (some seconds, it is impossible to keep them the same).
The server's time is 10 seconds ahead....

**Comment by Fmstrat** [comment]
Yea, 10 seconds shouldn't make a difference. Does this happen with all new notes or notes with the same name as a note that was previously deleted? The next version I release will have a debug mode for printing to logcat. Would you be willing to use that to determine what these issues are?

**Comment by delumerlino** [comment]
Thank you.
I have tried to put ahead the phone clock, anyway, and it does the same.
The issue is on every new note from the phone, everytime I change the name
of the note.
Should it be some permission problem? It works like a charm with
server-side created note...
Andrea
Il 25/mar/2015 20:03 "Fmstrat" <notifications@github.com> ha scritto:

**Comment by Fmstrat** [comment]
I'm unsure at this point what would be causing this. In the next iteration of the app, localStorage is getting replaced with a DB. This may effect things, so I'll ask that you check back after 0.0.8 is in the Play Store.

**Comment by Fmstrat** [comment]
Now that I've fixed https://github.com/Fmstrat/ownnote/issues/60, I think this issue is related. The difference being you're not getting the error thrown, so the re-sync is deleting the note. Try 0.0.8 when it hits the Play Store. If that doesn't fix it, then please re-open this ticket.
