### ISSUE TITLE
Android: invalid username and/or password

### ISSUE THREAD

**Issue by githubfleming** [Fmstrat/ownnote#49]
I've waited a while of this app and bought it immediately. Thanks for you work! Unfortunately, it won't let me log in. It keeps saying 'invalid username and/or password', but when I use the same credentials to access my owncloud notes via the browser there is no problem.

The app is doing this from the start. I use this as server location: 
https://[my server]/owncloud/index.php/apps/ownnote/ 

I've tried logging in with and without the 'Allow all SSL certificates' ticked. 

Hopefully someone has an idea to solve this. Must be something really simple. 

Setup:
Android 4.4.4.
Owncloud 8.0.2
ownNotes 0.05
App installed 2015/03/24

**Comment by Fmstrat** [comment]
Hi,

Just use your owncloud URL such as in the example when the App starts:

https://[my server]/owncloud

That should do it, but if not, let me know.

**Comment by githubfleming** [comment]
Solved. Many thanks!
