### ISSUE TITLE
[FeatureRequest] Possibility to import from evernote

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#5]
Is it possible to import from evernote?
exported evernotes are seperated in html files and images which are in different folders.

**Comment by Fmstrat** [comment]
Set as a future enhancement. I would not expect this soon though, as I need to get the mobile interfaces going first. I'll likely base off something like this:

https://code.google.com/p/evimsync/

**Comment by Fmstrat** [comment]
By the way, have you tried to export Evernote to htm and copy into the Notes directory? Another use also had success cutting and pasting notes.

**Comment by apg1980** [comment]
I allerdings tryed to export but there is only an option to Export to html. 
Problem next is, all embeddet images are with in a subfolder named like the notr itself.
So this is the other reasons  to convert the Images of the im src urls to  base64 content.

**Comment by Fmstrat** [comment]
Got it. I'm going to merge this with another Evernote request.

**Comment by Fmstrat** [comment]
Merged into: https://github.com/Fmstrat/ownnote/issues/7

Please follow that issue for updates.
