### ISSUE TITLE
Android app - small font size

### ISSUE THREAD

**Issue by ptah-alexs** [Fmstrat/ownnote#51]
Hi, 

In your app for android font is too small on my 4.3" phone. Please add settings for font size.

**Comment by Fmstrat** [comment]
Are you using android 2.3? I've got this fixed already and will be released in the next version.

**Comment by ptah-alexs** [comment]
my version 4.2.2. Sorry, I had forgot mention this information.

**Comment by ptah-alexs** [comment]
It's small even on my 9.7" tablet ![screenshot](https://ptah-alexs.info/url/ownnote-fonts)

**Comment by Fmstrat** [comment]
Font size fix in 0.0.5 just published to the App store (should work for 4.x, too). Once it's available in your area, give it a shot. If it doesn't help, please re-open this issue.
