### ISSUE TITLE
Impossible to delete notes with ' marks

### ISSUE THREAD

**Issue by GLock-PPC** [Fmstrat/ownnote#52]
As per the title I have created notes that have a quotation mark (') in the title, now is impossible to delete them, also the group where they reside cannot be deleted.

**Comment by GLock-PPC** [comment]
also, after editing and saving, the note does not retain the saved text

**Comment by Fmstrat** [comment]
Moving this to the top of the list. Thanks for identifying.

**Comment by Fmstrat** [comment]
Resolved in 0.0.6, publishing to apps.owncloud.com shortly.

**Comment by GLock-PPC** [comment]
Fixed, Thank you

**Comment by Fmstrat** [comment]
NP. Android supports them in 0.0.8, which should hit the Play Store soon.
