### ISSUE TITLE
Android: Differentiate app icon for users without icon labels

### ISSUE THREAD

**Issue by srednax** [Fmstrat/ownnote#54]
The android app icon is a cloud, not at all telling what the app does. I suggest you use something more self-explanative and usable. A cloud with a pencil maybe?

**Comment by Fmstrat** [comment]
I may do this, but the cloud is intended to identify with ownCloud to make it easy to locate visually.

**Comment by srednax** [comment]
have the 'official' owncloud app with a very similar icon, just lighter blue. 
And the owncloud news app, uses its icon from owncloud (not good either, as it 
is not very obvious what it means), and more might come, so I hope you can 
find an icon that satisfies both concepts - note and owncloud...

Fredag den 27. marts 2015 07:09:52 skrev Fmstrat:

**Comment by Fmstrat** [comment]
Complete. New icon for 0.0.9 when it hits the Play Store.
