### ISSUE TITLE
Server: Strings are hardcoded in the code making translation not possible

### ISSUE THREAD

**Issue by seal20** [Fmstrat/ownnote#56]
After looking in the code, I see that the strings (example "Create a New Note") are hardcoded in the js files. As a results it is not possible to easily provide different languages of the strings.

I am not a coder but I would like to help in translating the app. However it would need first a refactoring of the code. Sorry for not being more useful.

**Comment by Fmstrat** [comment]
Good idea. Adding to the list.

**Comment by Fmstrat** [comment]
Translation form in place: https://docs.google.com/spreadsheets/d/1O61kZ0RbUFbnQuj8_EduZ76g5xleYxG66RakmN7AQ0c/edit?usp=sharing

**Comment by lemagoup** [comment]
I completed the Mobile App part of the French translation. Server and Google Play in progress.

**Comment by Fmstrat** [comment]
Great, thanks so much for the assistance!

**Comment by pinoggles** [comment]
(offtopic)
I found this thread and added german text to the translation form above, in case you are going to translate the app some day.

**Comment by Fmstrat** [comment]
@pinoggles Amazing, thank you. Translations are on the short list for both the server and the App.

**Comment by Fmstrat** [comment]
Anyone looking to translate from here out, please participate in the Transifex project, which is the standard service for ownCloud: https://www.transifex.com/projects/p/ownnote/

Thank you.

**Comment by Fmstrat** [comment]
Closing this out. Translations are implemented and will be in v1.0 when it rolls out. Anyone who would like to participate in enhancing translations, please use the above link and sign up for Transifex. Thanks.
