### ISSUE TITLE
Server: Investigate strict CSP requirements

### ISSUE THREAD

**Issue by fredericmohr** [Fmstrat/ownnote#57]
I just wanted to say that the setting the Content-Security-Policy (CSP) to the following,

    'custom_csp_policy' => "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *"

as stated in the installation part [here](https://github.com/Fmstrat/ownnote/blob/master/README.md), is bad practice. It took a long time for CSP to be picked up, now please don't encourage users to disable or lower it. The reason why the inline and eval options are named "unsafe-" is because of just that, they're unsafe.

**Comment by Fmstrat** [comment]
I will look into lowering these requirements in the future. The CSP line is what allows TinyMCE to run, and was based off other plugins on apps.owncloud.com.

**Comment by fredericmohr** [comment]
Thanks!

I'm not a dev, but I have a fairly good understanding of CSP, in case you need help there. Maybe we should open a ticket for this at TinyMCE as well.  That would fix the problem at it's source.

**Comment by Fmstrat** [comment]
Hi, would you be willing to try the zip from the CSP branch? https://github.com/Fmstrat/ownnote/archive/csp.zip

Remove the custom CSP line from config.php and let me know if this works for you. It works for me, but I would like to make sure it works with someone else before I push it out.

**Comment by fredericmohr** [comment]
I'll try it out this evening after work and will let you know how it goes.

**Comment by fredericmohr** [comment]
Looks fine to me, I removed the CSP rule I added yesterday and everything still works.

There are still two CSP warnings, but they seem to be on every owncloud page, not just notes
and I didn't notice any problems during my tests.

Owncloud still uses unsafe-eval, but that's [another problem](https://github.com/owncloud/calendar/issues/599). Thanks for fixing this! :)

**Comment by Fmstrat** [comment]
Yea, I've got a couple of warnings originating from other plugins I think. But none originating from ownNote  anymore. Thanks again.
