### ISSUE TITLE
Android: Keep a note open

### ISSUE THREAD

**Issue by GLock-PPC** [Fmstrat/ownnote#58]
A good feature to have is to keep a note open when switching between apps or locking the screen as if I need to take a note from a webpage or a document I have to reselect the note from the list and scroll down to keep editing.

Also an autosave function when changing to another app would make the note taking much more efficient

**Comment by srednax** [comment]
Yes please. Do not navigate away from where the user are. Apps are expected to show up in the state where they were left!

**Comment by Fmstrat** [comment]
Also complete, will be in next version.
