### ISSUE TITLE
.html files not supported

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#6]
is it possible to support .html files.
.html files are not displayed.
this is needed to import exported evernote notes.

**Comment by Fmstrat** [comment]
Could you not rename them to htm? I actually used to allow html, but for consistency I limited to htm only. I could re-enable this, or perhaps make it optional in the settings.

**Comment by apg1980** [comment]
Yay this wohl be perfect to Support both filetypes.

**Comment by Fmstrat** [comment]
OK, what I will likely do is allow it to read in *.html files, but on save (or perhaps even listing), rename to *.htm for consistency. I assume that would work for you?

**Comment by apg1980** [comment]
awesome

**Comment by Fmstrat** [comment]
Also, for the imports, you may have issues with images. See this issue for the progress on that: https://github.com/Fmstrat/ownnote/issues/7

**Comment by Fmstrat** [comment]
Implemented in commit https://github.com/Fmstrat/ownnote/commit/07740ed8cbeb337c7935c02cd675982d65c02cb7

Will be included in next release.
