### ISSUE TITLE
Android: Adjust UX so commands are buttons instead of inside the menu

### ISSUE THREAD

**Issue by biafra23** [Fmstrat/ownnote#61]
Please consider the following two changes. Don't hide primary functionality in the menu. Editing a note should be as easy as tapping into the View. Saving should be automatic. At least make it a Button visible below the editor. Please! 

PS: The Android app developer directed me here for feature requests. https://play.google.com/store/apps/details?id=com.nowsci.ownnote Though this looks like the github repo for the server side. My features do not require any change on the server side.

**Comment by Fmstrat** [comment]
Hi,

Thanks for the feedback. This is the right place. The navigation will be changing in a future version to include bottom nav buttons for editing. I'm also going to include a save popup on back button press as well. Marking this as an enhancement and when it gets on the list it will be flagged for a milestone release.

**Comment by Fmstrat** [comment]
Auto save covered here: https://github.com/Fmstrat/ownnote/issues/63

I'm going to rename this issue to focus on the UX changes.

**Comment by Fmstrat** [comment]
Complete in the version about to go to the Play Store.
