### ISSUE TITLE
Server: No E-Tag received from server, check Proxy/Gateway

### ISSUE THREAD

**Issue by xstrafer** [Fmstrat/ownnote#62]
This error message appeared in desktop sync client, when I have created via web-interface a note with image embedded. The desktop client cannot sync the note created. If creating simple text notes - it goes ok and syncs with desktop as well.

**Comment by Fmstrat** [comment]
Hi, do you mean the web client? Are you sure you're using ownNote and not Notes? There is no released desktop client for ownNote yet. Thanks!

**Comment by xstrafer** [comment]
no, I mean desktop client for owncloud for windows which sincs the owncloud (including Notes folder) to my windows desktop computer.

**Comment by Fmstrat** [comment]
This sounds like an old server issue where the client can't connect to get a file. There are quite a few github  issues listed for this message on the ownCloud client itself. The note that ownNote creates is a standard file, so there is nothing I can do here. Are you running a really old server version with a newer client?

**Comment by xstrafer** [comment]
I use ownCloud 8.0.2 (stable) with nginx and php-fpm on a freenas jail.

**Comment by Fmstrat** [comment]
You're using nginx as a proxy? It's likely an issue between the note sync and there since it's reporting a proxy error. Can you post your nginx.conf files? Perhaps I'll see something that's causing this to flake out.

**Comment by xstrafer** [comment]
No, I Do not use it as a proxy. just an ordinary web server in a jail.

**Comment by xstrafer** [comment]
user www;
worker_processes  2;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip  on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 9;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/x-javascript tex                                                                                         t/xml application/xml application/xml+rss text/javascript;

#owncloud server
    server {
        listen       80;
        server_name  *****************here goes my hostname************************;
        #access_log  logs/host.access.log  main;
        root /usr/local/www/ownCloud;
        index index.php;

        client_max_body_size 2048M; # set maximum upload size

        location = /robots.txt { allow all; access_log off; log_not_found off; }
        location = /favicon.ico { access_log off; log_not_found off; }
        location / {
                index index.php;
                try_files $uri $uri/ /index.php?$args;

                location ~ ^/(?:\.|data|config|db_structure\.xml|README) {
                deny all;
                }

        rewrite ^/apps/([^/]+)/(.+\.(css|php))$ /index.php?app=$1&getfile=$2 las                                                                                         t;
        rewrite ^/remote/(.*)$ /remote.php/$1 last;

        location ~ \.php/? {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php-fpm.sock;
                include fastcgi_params;
                }

        location ~* \.(?:jpg|gif|ico|png|css|js|svg)$ {
                expires max; add_header Cache-Control public;
                }
        }


        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/www/nginx-dist;
        }

    }

**Comment by Fmstrat** [comment]
rewrite ^/apps/([^/]+)/(.+\.(css|php))$ /index.php?app=$1&getfile=$2 las

I can't be sure without testing, but it's looking like that kills the API. Why would you be rewriting the apps folder?

**Comment by xstrafer** [comment]
have commented all rewrites. no changes.

**Comment by xstrafer** [comment]
and it shows error only if I make a note with image embedded... if I make a plain text note - no errors.

**Comment by Fmstrat** [comment]
That's really weird. I've never seen anything like this before. How large is the image? Over 2 meg? I ask because of this:

    client_max_body_size 2048M; # set maximum upload size

**Comment by Fmstrat** [comment]
Actually, first result searching on duckduckgo.com found it: https://github.com/owncloud/client/issues/1291

    NGINX strips off ETags when gzipping. In my case, turning gzip off fixed it.

It's actually a bug in ownCloud server that has resurfaced since 8.0 (last post in that issue). It's probably pure conincidence that the note is triggering it (perhaps something about it's structure during the HTTP server's gzip process). The above quote is not a "true" fix, but a workaround that should get things moving.

Posting in that linked issue may help, but unfortunately there's not a lot I can do from this end.

**Comment by xstrafer** [comment]
thanks for assistance! turning gzip off solved the problem for now. 
will try to find a permanent solution next...

Strange thing, it affected only ownNote functionality.
 
thanks again for your help!

**Comment by RealRancor** [comment]
> It's actually a bug in ownCloud server that has resurfaced since 8.0 (last post in that issue).

Which is absolutely wrong. Your quoted description is telling you why.
