### ISSUE TITLE
Android app - impossible to create new note 

### ISSUE THREAD

**Issue by GLock-PPC** [Fmstrat/ownnote#64]
Since the last update, can't create a new note. Editing of existing notes works fine.
Android 4.4.4 Xiaomi Mi3

**Comment by GLock-PPC** [comment]
No error message given after tapping on "create"

**Comment by Fmstrat** [comment]
Referencing https://github.com/Fmstrat/ownnote/issues/60 as the fix applies here. Will be in next Android release. If the next version (0.0.8) doesn't fix this, please re-open.

**Comment by GLock-PPC** [comment]
Ok
