### ISSUE TITLE
Server: Support ownCloud theming

### ISSUE THREAD

**Issue by alex42ka** [Fmstrat/ownnote#66]
As described above. I wanted to activate my own theming on Owncloud but then ownnote did not work. Beneath the top bar a little window with my activated apps have been shown.

**Comment by Fmstrat** [comment]
Can you provide some Screenshots of what it looks like for you?

**Comment by alex42ka** [comment]
Here comes a screenshot
![bildschirmfoto vom 2015-03-30 17 29 08](https://cloud.githubusercontent.com/assets/5347731/6899691/63ef33aa-d702-11e4-855b-a763f9d6e15e.png)

**Comment by Fmstrat** [comment]
Thanks. Is there a sample theme you can provide that I could use to debug with?

**Comment by alex42ka** [comment]
I've just copied the relevant parts of core to a theming folder. Following the Owncloud documentation (https://doc.owncloud.org/server/8.0/admin_manual/operations/theming.html) these are the folder css, img and js. Then I've activated the theme by adding the name in the config.php. Thats all. 
The app didn't work with a "fresh" theme and an old one.

**Comment by Fmstrat** [comment]
OK, thanks. I will try that out on a test server and let you know how it goes.

**Comment by alex42ka** [comment]
I'm sorry but now it seems to work. Don't know what I've done.
