### ISSUE TITLE
Android app: referenceError: localnote is not defined

### ISSUE THREAD

**Issue by srednax** [Fmstrat/ownnote#69]
Right now, I can not use the android app on my tablet. Everrytime it tries to contact the server, I get an error dialog, quoted above.

**Comment by Fmstrat** [comment]
See: https://github.com/Fmstrat/ownnote/issues/60

Already fixed in 0.0.8. I've published it to the Play Store, but it is still pending. I expect it to release to all locales by the end of the day. Thanks for the feedback!
