### ISSUE TITLE
Android: Can't create new note on specific configurations/devices

### ISSUE THREAD

**Issue by GLock-PPC** [Fmstrat/ownnote#71]
After updating still not able to create a new note
ref https://github.com/Fmstrat/ownnote/issues/64

**Comment by srednax** [comment]
Works for me, with latest version.

**Comment by delumerlino** [comment]
Me too, still not able to create a new note!

**Comment by Fmstrat** [comment]
Hi all,

The app works by creating the note locally, then synchronizing with the server. The only reason I can think of for the note not displaying is that the server has a flag for "delete" that is newer than the "create" on the mobile device. Sorry to repeat these questions, but I want to be sure I'm not missing something easy first:

- For those that are still experiencing this, you are running ownNote for Android 0.0.8 right? 
- Does your server have a different time than your device?
- Is your server in a different timezone?

Thanks.

**Comment by delumerlino** [comment]
Yes you are clear.
Here my replies:
* Latest ownnote both on server and Android
* Time is *quite* the same, only less than 10 seconds
* They are in the same time zone

Thanks a lot,
Andrea

2015-04-01 15:01 GMT+02:00 Fmstrat <notifications@github.com>:

> Hi all,
>
> The app works by creating the note locally, then synchronizing with the
> server. The only reason I can think of for the note not displaying is that
> the server has a flag for "delete" that is newer than the "create" on the
> mobile device. Sorry to repeat these questions, but I want to be sure I'm
> not missing something easy first:
>
>    - For those that are still experiencing this, you are running ownNote
>    for Android 0.0.8 right?
>    - Does your server have a different time than your device?
>    - Is your server in a different timezone?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fmstrat/ownnote/issues/71#issuecomment-88470987>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by Fmstrat** [comment]
Could someone run this command and send me the output (de-identified is fine) along with which note your running into issues with?

     echo "select id,name,grouping,mtime from oc_ownnote where uid='MYUSERNAME'" |mysql owncloud

**Comment by delumerlino** [comment]
Here I am (I have added the string to connect to mysql)

echo "select id,name,grouping,mtime from oc_ownnote where uid='Andrea'"
|mysql owncloud -uroot -p
Enter password:
id      name    grouping        mtime
1       test            1427184478
2       brico           1427722413


2015-04-01 15:19 GMT+02:00 Fmstrat <notifications@github.com>:

> Could someone run this command and send me the output (de-identified is
> fine) along with which note your running into issues with?
>
>  echo "select id,name,grouping,mtime from oc_ownnote where uid='MYUSERNAME'" |mysql owncloud
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fmstrat/ownnote/issues/71#issuecomment-88477658>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by Fmstrat** [comment]
I will continue to investigate this further and have moved it into the milestone for 0.0.9. I may have to enable a very detailed DEBUG feature for the app to help solve this. Would anyone be willing to provide a full logcat to me once it is out?

**Comment by delumerlino** [comment]
Yes sure, keep me informed for testing!
Best regards!
Il 01/Apr/2015 21:38, "Fmstrat" <notifications@github.com> ha scritto:

**Comment by Fmstrat** [comment]
I think I found a new path. Can those having this issue let me know if they are set to Files and Database or just Database for storing notes?

**Comment by delumerlino** [comment]
It is set only to database store...
Il 02/Apr/2015 18:17, "Fmstrat" <notifications@github.com> ha scritto:

**Comment by Fmstrat** [comment]
Yup, that's the problem. It's a combination of Android and the API. For reference and history, a bug has been created/fixed for the next server milestone 0.0.7. This will be released before the Android fix. I will also add the DEBUG option as a hidden feature, so that if it's required we can try that without creating a new release.

**Comment by Fmstrat** [comment]
This has been fixed between 77 and the version about to release in the Play Store. If people still have issues, please post a NEW issue. I've already incorporated a hidden debug trick, so we'll be able to use that. Thanks!

**Comment by delumerlino** [comment]
you are the man!
Thank you, it works now like a charm!

2015-04-03 23:46 GMT+02:00 Fmstrat <notifications@github.com>:

> Closed #71 <https://github.com/Fmstrat/ownnote/issues/71>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fmstrat/ownnote/issues/71#event-273020444>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment
