### ISSUE TITLE
Android: can't add images

### ISSUE THREAD

**Issue by srednax** [Fmstrat/ownnote#72]
I tried put an image in a note on android, this is not possible, because the view switches to the note list by the tie an image is selected in the select file dialog.
The behavior is:
- tap the image button in the editor toolbar
- a dialog shows up with a button to select an image (I find this step questionable, why the extra step)
- tap that button and navigating to a suitable image, and tap it
=> BUG: the app moves to the notes list and the embed dialog shows.
- click insert - now the keyboard shows in the notes list, which is not making sense. Image is not embedded.

Suggested behavior:
- click the image button in the toolbar
- file selector shows immediately. Navigate to an image and tap it
- image is embedded in note.

**Comment by srednax** [comment]
In an additional comment, it would be nice to use an existing service to get an image from the device, if it exists. Most apps also offers the camera as an image source.
Offering images from the owncloud server would also be a valid source.
Maybe a possible replacement from the initial, redundant dialog could be a choice of source?

**Comment by srednax** [comment]
Just tested on web, and here the ability to select from images available in owncloud would be nice as well.

**Comment by Fmstrat** [comment]
This used to work, something I updated in one of the more recent versions may have caused it. I will first look into fixing the current method, and then enhancing it further.

**Comment by HZL-NL** [comment]
I too cannot insert an image. Mine does not return to the notes list, it just says the app stopped working and closes the app (LG Bello Ownnote 0.0.7)...

**Comment by Fmstrat** [comment]
This seems to be happening on only specific devices. Can you all let me know what version of android you are running and if the file management is stock or altered like on some Samsung devices (if you know)?

Thanks

**Comment by HZL-NL** [comment]
I have a LG-D331 with Android 4.4.2 as it comes, no modifications what so-ever. Is saw some mention of missing rights regarding external storage (?) in the error report, don't know if it has anything to do with it or not.

**Comment by srednax** [comment]
Works on my nexus 7 with cyanogenmod 12 (android 4.4)

On my fairphone (android 4.2) it kinda works. When selecting a file using the 
gallery, the filename in the select file dialog is not filled, but pressing 
the insert button inserts the selected image.

Images are not correctly scaled to screen width in edit mode, making the 
application very hard to use with images.

Kindly,
Anders


L�rdag den 4. april 2015 10:44:10 skrev Fmstrat:

**Comment by Fmstrat** [comment]
> I have a LG-D331 with Android 4.4.2 as it comes, no modifications what so-ever. Is saw some mention > of missing rights regarding external storage (?) in the error report, don't know if it has anything to do > with it or not.

I think this may be the problem everyone is having, it's just not being reported the same way. My guess is that on certain devices, such as some LGs or Samsungs where there are customizations to the gallery, the image picker copies images to a temporary location before supplying the URI to the application. In these instances, since ownNote does not request permission to write to third party storage, it fails. This would explain why it works on all the emulators and Nexus devices and/or Cyanogenmod, which are based off AOSP. 

I'm completely rewriting the image picker now, which will include a greater permission set to ensure that doesn't happen anymore. Thanks.

**Comment by Fmstrat** [comment]
The image selector is now completely rewritten for 0.0.11. You will be able to select multiple images from the standard image selection window and they will be embedded all at once.
