### ISSUE TITLE
Android: Support "shrinking" notes for synchronization of large (>100MB) libraries

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#73]
I am using OC8.2 with ownnote 0.0.6 and android Client 0.0.8.
After entering credentials i can see no progress except my Data usage is growing. After a lot of time the login button appear without ability to press.
it seams that the app is downloading all content from notes folder before Start working.
Btw. No error appear.

**Comment by Fmstrat** [comment]
Wow, that is a lot of notes. The app is built for offline use, so it's attempting to synchronize all of your note content. I'm going to flag this as an enhancement to do one of these things:

- Create an online-only mode if notes are larger than X
- Strip BASE64 data from notes larger than Y if total notes are larger than X
    - Display BASE64 data on-demand when online

I'm leaning towards the second option, since it would give you the most content at any point.

**Comment by Fmstrat** [comment]
NOTE: From original title - found with 400MB library.

**Comment by apg1980** [comment]
Sorry I cannot recommend your sollutions.  I suggest to Display all notes subjects and categorys first and then bring a selection for offline sync of the notes that are necessary.

**Comment by Fmstrat** [comment]
I can't do that for all users, it doesn't suit the use case for most of those using this app. I could do that if the notes library is over a certain size, but why would you prefer that over option 2 below? Removing the BASE64 data would keep things pretty small I would think, and then you would at least have the text offline. 

What about option 2, but when viewing a note add in a "Save offline" button that keeps the BASE64 data for that particular note synchronized as well?

**Comment by apg1980** [comment]
Ok that will suit to me thanks

**Comment by apg1980** [comment]
i've tryed with the latest ownnote server and android from tonight.
app is always crashing after a long time and never logging in.
on my 2 android devices (kitkat tablet and lollipop smartphone) i can see a huge wlan traffic.
i've testet 2 ways local ip of my owncloud server and the published external url, everytime same behaviour.
I can see the error: RangeError: Maximum call stack size exceeded.

**Comment by Fmstrat** [comment]
Thanks. The latest version hasn't been updated to support these large notes yet. If you watch to the far right on this page, there is a milestone. Right now it's unspecified, but at some point in the near future that milestone will change to a version number, and that means I've started to work through it. Thanks again for the feedback.

**Comment by Fmstrat** [comment]
I've opened a new issue that you can track for selective sync: https://github.com/Fmstrat/ownnote/issues/112

I'm marking this as resolved as the update to support online-only mode and the counters on loading with background capability will get around this for now. Selective sync will require some bigger changes in the way note selection is made, and I'd rather that be a separate version release to keep .13 moving.

**Comment by Fmstrat** [comment]
Note: to completely clear out data stored, it may be worth "Clearing Data" on the App after installing 0.0.13.
