### ISSUE TITLE
Server: Problem with Firefox and Chrome

### ISSUE THREAD

**Issue by Mr-HeBo** [Fmstrat/ownnote#75]
Hello, 

When I use Firefox or Chrome (latest version), I can not create new notes or view and change existing notes. Internet Explorer and Android App work fine. 

![error-ownnotes](https://cloud.githubusercontent.com/assets/11228598/6943754/674daaec-d890-11e4-9bb2-49aadcb85451.jpg)

All plugins are disabled.

Thanks for your ideas and/or help. 
Regards
Heiko

**Comment by Fmstrat** [comment]
Did you add the custom CSP policy to ownCloud from the instructions? https://github.com/Fmstrat/ownnote/blob/master/README.md

**Comment by Mr-HeBo** [comment]
yes now! I know: rtfm :-)
Thanks for the quick response and solution!!

**Comment by Fmstrat** [comment]
No problem. :) Btw, the next version of ownNote will likely not require the custom CSP change. If you would like to follow that discussion, it is here: https://github.com/Fmstrat/ownnote/issues/57
