### ISSUE TITLE
Change between apps force closing currently opened note

### ISSUE THREAD

**Issue by kriegerse** [Fmstrat/ownnote#76]
Hi,

**first thanks for your great work! Finally, an useable notes app on mobile devices for ownCloud.** 

I would report a bug or request a change of the behaviour described below.

When you have opened a note, it doesn't matter if its in the read only mode or write mode, and do the following:

* screen powers off for energy saving (timeout)
* screen locks due to security 
* change to another app to get some information / data e.g. copy + paste

and you switch back to ownnote then your note opened before isn't open anymore. 
Instead you are landing in the notes overview. 

Also if you don't save your changes before the app switch, your changes will be lost. 

I think this behaviour should be changed, because users don't await the overview, they are expecting the note they opened before and also already writte informations are saved.

I can reproduce this on my two devices:

Phone:  XPeria T (mint)
Android: Android L (CM12 build: cm-12-20150401-NIGHTLY)

Tablet: Nexus 7 
Android: Android L (5.0.2) 

Thank you!
Sebastian

**Comment by Fmstrat** [comment]
First off, thanks for taking the time to provide feedback!

Luckily, all of these are on the list for the next version. Here's the 0.0.9 milestone list: https://github.com/Fmstrat/ownnote/milestones/Android%20-%200.0.9

Thanks again.
