### ISSUE TITLE
Android: Menu doesn't react on Android back button

### ISSUE THREAD

**Issue by kriegerse** [Fmstrat/ownnote#84]
Hi,

I want to report some small usability "bugs". 

If you have opened the Menu in the ownNote App (where the Logout options appears) users might  expect that:

* the back button in the Dock Bar will force to left the menu since it has the focus
* when they tap on an empty part outside the menu, the menu should be left since it has the focus 

This is not the case at the moment. 

Another usability bug I've found in the groups view. If you are there and has the menu open:

* a tap on the back button will go back to the note view, but the focus is on the menu

So the users might expect, that the menu will be closed. But I think this behaviour is related to the one above. 

Thanks for your great work!
Sebastian

**Comment by Fmstrat** [comment]
My hope will be to include this in the next version.

**Comment by Fmstrat** [comment]
Complete.
