### ISSUE TITLE
Android: ownNote logo doesn't save notes

### ISSUE THREAD

**Issue by kriegerse** [Fmstrat/ownnote#85]
Hi,

another small usability bug. 
If you have open a note, and you tap on the ownNote logo you can go back to the notes overview. 
What's missing for this right behaviour is an back arrow or something that indicates it. 

Also I noticed that if you use this way, changes in notes are not saved. Maybe a dialogue asking for saving the changes could be useful here. I think this was the case in an earlier version. 

Thank you!
Sebastian

**Comment by Fmstrat** [comment]
I likely won't add a back arrow, the logo click is really an outdated feature anyway. I will make it autosave, though. Thanks for the feedback.

**Comment by Fmstrat** [comment]
Complete.
