### ISSUE TITLE
Server: MySQL 'max_allowed_packet'

### ISSUE THREAD

**Issue by muramasatheninja** [Fmstrat/ownnote#89]
First I want to say that I have been looking for an app like this for a while and am glad you are working on it.

I started working on my first note and went to work on creating my first document. As I edited the document and added pictures I found that my server was going slower and slower. I finally restarted the server and the notes app stopped working and found that my owncloud was always at 100% cpu usage. After some poking around I found "Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet'" Basically I needed to increase the max allowed packet on my SQL server. My theory is that since the doc I created was 20 MB then the DB needed to be allowed packets of at least that size. After raising the limit my cpu usage went back to normal. I figured this should be mentioned since I imagine others will run into this eventually as well.

**Comment by Fmstrat** [comment]
Good catch, I've hit just below the max packet on my servers, and didn't realize that was going to be a limitation. I'll actually look to split notes into parts vs. forcing users to change their DB config first, and then resort to config changes only if required. Thanks.

**Comment by Fmstrat** [comment]
Note: Check this on Android as well.

**Comment by Fmstrat** [comment]
Updated by splitting out notes into parts so that servers don't have to change config.
