### ISSUE TITLE
Android: Impossible to edit notes

### ISSUE THREAD

**Issue by lemagoup** [Fmstrat/ownnote#91]
I just downloaded the Android app 0.0.10 and tried it with my Ownnote server (0.0.5). I could see the list of the previously created notes but could not display/edit them from the Android app. I could only create a new note.

I then updated my ownnote server to 0.0.7, deleted all the entries in the ownnote database and in the files/Notes directory. I could create a new note but when I try to edit it from the Android app, I get only a blank screen.

This application is unusable for me at the moment.

**Comment by Fmstrat** [comment]
Hi, can you try clearing the data on the Android app from the Android Settings>Apps screen? There may be some underlying issues with the database on the Android device. Thanks.

**Comment by lemagoup** [comment]
I cleared the Android app data and cache and reloaded the application. I still have the same problem. A blank screen appears when I click on the edit button.

**Comment by lemagoup** [comment]
Moreover when I try to go back after the blank screen I get this error : "TypeError: Cannot read property 'body' of undefined"

**Comment by Fmstrat** [comment]
Sorry, hopefully this is the last question before I figure this one out. What version of Android are you running and on what device? Thanks.

**Comment by lemagoup** [comment]
I am using Android 4.1.2 on a Wiko CINK FIVE (French model of the Micromax Canvas HD A116).

**Comment by Fmstrat** [comment]
So I figured out a little bit of Android 2.3 code was firing, but it still shouldn't have caused this. What is the default web browser on your device? I'm curious as to if the web-view used to display the editor is causing a problem.

**Comment by lemagoup** [comment]
I am using Firefox 37.0.1

**Comment by Fmstrat** [comment]
OK, doubted that would be an issue. I'm thinking your device didn't like that 2.3 code running. I'm going to mark this complete with that fix in mind, but once 0.0.11 rolls out, if it happens again, please create a new ticket. Thanks!
