### ISSUE TITLE
Android: Unable to login when using 301 redirects

### ISSUE THREAD

**Issue by hognoodle** [Fmstrat/ownnote#93]
It crashes every time.
I'm using a self-signed cert and /etc/apache2/sites-enabled/owncloud.conf (ubuntu 14.04)  has a redirect to port 443 script so I just login like http://example.com/owncloud/ with "Allow all SSL certificates" checked. I must be doing something wrong.
Should I be using this url for the Server: https://example.com/owncloud/index.php/apps/ownnote/ ?
I tried that and it still crashed anyway.

**Comment by Fmstrat** [comment]
Have you tried to login to:

    https://example.com/owncloud

If this works for you, there may be some issues with the owncloud REST call and the 301 redirect. I may be able to create a hack to get around that for other users who run into this. Can you also post a copy of your owncloud.conf file for apache?

**Comment by hognoodle** [comment]
Unfortunately, https://example.com/owncloud doen't work either:

<VirtualHost 192.168.0.10:80>

#### Redirect to port 443 ###
RewriteEngine on
ReWriteCond %{SERVER_PORT} !^443$
RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R,L]
#### End of Redirection configuration ###

DocumentRoot /var/www/owncloud/
<Directory /var/www/owncloud>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
</Directory>

</VirtualHost>

<VirtualHost 192.168.0.10:443>

####Configuration for SSL #####
SSLEngine on
SSLCertificateFile /etc/apache2/ssl/stofega.net.pem
SSLCertificateKeyFile /etc/apache2/ssl/stofega.net.key
#### End of SSL Configuration ####

DocumentRoot /var/www/owncloud/
<Directory /var/www/owncloud>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
</Directory>
</VirtualHost>

Thanks

**Comment by marco9876** [comment]
I probably have the same or a similiar Issue, so im gonna post here.

System: Ubuntu 14.04 Owncloud Installation with apt-get install
(cant access Webserver to verify the redirect atm  but should be the case)

Problem: Everytime i wanna login it gives me "Internel Server Error". I tried a lot of different urls, also the one described here. Most of the the App says "Bad Password / Username" or Internel...

Owncloud Log:
Exception: {"Message":"The requested uri(\/owncloud\/index.php\/apps\/ownnote\/api\/v0.2\/ownnote\/remoteindex) cannot be processed by the script '\/owncloud\/\/index.php')","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/base.php(767): OC_Request::getRawPathInfo()\n#1 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#2 {main}","File":"\/var\/www\/owncloud\/lib\/private\/request.php","Line":297}

**Comment by Fmstrat** [comment]
@marco9876 Yes, a new topic would be helpful to track and fix your issue seperately. Thanks!

**Comment by Fmstrat** [comment]
This took forever to figure out and turned out to be something really simple. Clearing variables needed to be done, but a temporary fix until 0.0.11 hits the Play Store would be to uncheck and recheck the Allow all certs box, which may temporarily solve things. Otherwise, this bug is fixed and will be in the 0.0.1 release. Thanks!

**Comment by hognoodle** [comment]
That didn't work but I'll just wait for the update, thanks.

**Comment by Fmstrat** [comment]
OK, the new version is releasing today. Hopefully that fixes things. Thanks.

**Comment by RR1991** [comment]
Marco, I cannot find that you have opened a topic for your problem. Yet, I am experiencing the exact same issue, what have you done to resolve the issue?

**Comment by Fmstrat** [comment]
@RR1991 There have been a couple of other random login issues being fixed in .13. That being said, the largest and most obvious is a simple one, make sure you don't have a trailing slash in your URL. It should just be:

    https://www.site.com/owncloud

Or whatever your directory is.

**Comment by RR1991** [comment]
@Fmstrat ah. That is all it took, sorry for the hassle. Thanks for the great work!
