### ISSUE TITLE
Server: After creating a note with ö and / in the title, ownnote stopped working

### ISSUE THREAD

**Issue by reimersjan** [Fmstrat/ownnote#94]
Hey.
I tried to create a note with the german **ö** and a **/** inside the title of the note. It didn't show up in the ownnotes overview, i refreshed the page and now the ownnote-app is blank. The .htm file doesn't show up in my Notes folder either.

owncloud 8.0.2
ownnote version 0.0.7
I'm storing the notes in Database and Files

Here is the *censored* output from the log. This shows up in the log everytime I try to open ownnote.

`
Exception: {"Message":"Could not obtain lock type 2 on \"\/var\/www\/virtual\/censored\/html\/data\/censored\/files\/Notes\/M\u00f6gliche Mods \/r\/censored.htm\".","Code":0,"Trace":"#0 \/var\/www\/virtual\/censored\/html\/apps\/files_locking\/lib\/lockingwrapper.php(44): OCA\\Files_Locking\\Lock->addLock(2, NULL)\n#1 \/var\/www\/virtual\/censored\/html\/apps\/files_locking\/lib\/lockingwrapper.php(93): OCA\\Files_Locking\\LockingWrapper->getLock('files\/Notes\/M\\xC3\\xB6...', 2)\n#2 \/var\/www\/virtual\/censored\/html\/lib\/private\/files\/storage\/wrapper\/wrapper.php(223): OCA\\Files_Locking\\LockingWrapper->file_put_contents('files\/Notes\/M\\xC3\\xB6...', '')\n#3 \/var\/www\/virtual\/censored\/html\/lib\/private\/files\/view.php(834): OC\\Files\\Storage\\Wrapper\\Wrapper->file_put_contents('files\/Notes\/M\\xC3\\xB6...', '')\n#4 \/var\/www\/virtual\/censored\/html\/lib\/private\/files\/view.php(427): OC\\Files\\View->basicOperation('file_put_conten...', 'Notes\/M\\xC3\\xB6gliche...', Array, '')\n#5 \/var\/www\/virtual\/censored\/html\/lib\/private\/files\/filesystem.php(649): OC\\Files\\View->file_put_contents('Notes\/M\\xC3\\xB6gliche...', '')\n#6 \/var\/www\/virtual\/censored\/html\/apps\/ownnote\/lib\/backend.php(335): OC\\Files\\Filesystem::file_put_contents('Notes\/M\\xC3\\xB6gliche...', '')\n#7 \/var\/www\/virtual\/censored\/html\/apps\/ownnote\/lib\/backend.php(224): saveNote('Notes', 'M\\xC3\\xB6gliche Mods ...', '', '')\n#8 \/var\/www\/virtual\/censored\/html\/apps\/ownnote\/controller\/ownnoteapicontroller.php(41): getListing('Notes', false)\n#9 [internal function]: OCA\\OwnNote\\Controller\\OwnnoteApiController->index()\n#10 \/var\/www\/virtual\/censored\/html\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#11 \/var\/www\/virtual\/censored\/html\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'index')\n#12 \/var\/www\/virtual\/censored\/html\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'index')\n#13 \/var\/www\/virtual\/censored\/html\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('OwnnoteApiContr...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/virtual\/censored\/html\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#16 \/var\/www\/virtual\/censored\/html\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/ownnote\/a...')\n#17 \/var\/www\/virtual\/censored\/html\/index.php(36): OC::handleRequest()\n#18 {main}","File":"\/var\/www\/virtual\/censored\/html\/apps\/files_locking\/lib\/lock.php","Line":246} 
`

I assume it's the **/** in the filename.

**Comment by reimersjan** [comment]
Workaround:

I deleted the note via phpmyadmin from the table `oc_ownnote`. Now ownnote is working again

**Comment by Fmstrat** [comment]
Thanks for the feedback. I will get this resolved in the next round.

**Comment by Fmstrat** [comment]
Looks like I'm going to have to convert slashes to dashes in note titles to keep the file system in check.

**Comment by Fmstrat** [comment]
Fixed for next version.

**Comment by reimersjan** [comment]
Nice. Thank you!
