### ISSUE TITLE
Android: Allow for hiding controls in the editor

### ISSUE THREAD

**Issue by retoter** [Fmstrat/ownnote#96]
Hi there,

I am aware of the roadmap towards Evernote (Formatting, Images). But, coming from the ease of SimpleNote, it would be handy people like me to disable these options (in the settings) in order to unclutter the GUI and speed up the application.

Or does the aimed compatibility to the owncloud app (ownnote) prevent this simplicity?

Thanks for reading and considering.

**Comment by Fmstrat** [comment]
Hi, thanks for the feedback. Yes, since this is tied to ownNote, the tools will remain the same. That being said, as in your other post, I could add options for disabling controls in a post 1.0 version. Changing this to an enhancement. Thanks again.

**Comment by retoter** [comment]
Dear Fmstrat

Thanks for your reply. The 0.11-release works like a charm. And I am starting to like the fact that the note is initially displayed in a reading mode. I was not really aware that I was annoyed with simplenote going straight into the edit mode activating the keyboard and hence covering one third of the screen… :-)

Have a great day!
