### ISSUE TITLE
Android: Logout questions on ownNote v0.0.10

### ISSUE THREAD

**Issue by brewha** [Fmstrat/ownnote#97]
I just purchased and installed ownNote on my Samsung Note 3.  I entered by web address and credentials and connect to my owncloud v8.0 server just fine.  I can create/edit/delete files just fine.  If I log out of the app I can simply log back in however, if I kill the app after logging out or if I shut my phone off it does not save my settings.  No other accounts/apps behave this way.  Is there something I may be doing wrong?

**Comment by Fmstrat** [comment]
Hi, why are you logging out? Logging out clears all data as the intent of logging out is to login with another user. If you just leave the app running or kill it, the app will keep your credentials and notes.

If you're one of the few having issues exiting with the back button and/or credentials saving WITHOUT logging out, then 0.0.11 will be hitting the Play Store today, and it fixes those issues.

**Comment by brewha** [comment]
Ok not logging out works fine.  Just kill the app.  Thanks!
